import type { InterfaceLanguage } from "@/lib/language";

export type CppModuleKey = "basics" | "oop" | "stl" | "algorithms";

export type CppDetailCopy = {
  eyebrow: string;
  title: string;
  description: string;
  sections: { title: string; body: string; examples?: string[] }[];
};

const basicsExamples = ["int score = 100;", "cout << 3 + 4;"];
const stlExamples = ["vector<int> a; a.push_back(1);", "map<string, int> count;"];

export const cppDetailCopy: Record<CppModuleKey, Record<InterfaceLanguage, CppDetailCopy>> = {
  basics: {
    en: { eyebrow: "C++ Basics", title: "Syntax And Types", description: "Variables input output branches loops and functions with dense code reading practice.", sections: [{ title: "Core scope", body: "int double char string cin cout if else for while and functions.", examples: basicsExamples }, { title: "Question types", body: "Multiple choice fill blank code reading and output prediction are supported without online execution." }] },
    zh: { eyebrow: "C++ 基础", title: "语法和类型", description: "变量 输入输出 分支 循环 函数 配合密集代码阅读练习", sections: [{ title: "核心范围", body: "int double char string cin cout if else for while 和函数 先把输入 输出 变量变化看清楚", examples: basicsExamples }, { title: "题型", body: "支持选择 填空 代码阅读 输出预测 第一版不做在线运行" }] },
    ja: { eyebrow: "C++ 基礎", title: "構文と型", description: "変数 入出力 分岐 ループ 関数をコード読解と一緒に練習します", sections: [{ title: "中心範囲", body: "int double char string cin cout if else for while 関数を扱い 入力 出力 値の変化を読みます", examples: basicsExamples }, { title: "問題形式", body: "選択 穴埋め コード読解 出力予測を扱います オンライン実行は使いません" }] },
    ko: { eyebrow: "C++ 기초", title: "문법과 타입", description: "변수 입출력 조건 반복 함수와 코드 읽기를 함께 연습합니다", sections: [{ title: "핵심 범위", body: "int double char string cin cout if else for while 함수와 값 변화 읽기", examples: basicsExamples }, { title: "문제 유형", body: "선택 빈칸 코드 읽기 출력 예측을 온라인 실행 없이 연습합니다" }] },
    es: { eyebrow: "Base C++", title: "Sintaxis y tipos", description: "Variables entrada salida ramas bucles funciones y lectura de codigo.", sections: [{ title: "Alcance central", body: "int double char string cin cout if else for while y funciones.", examples: basicsExamples }, { title: "Tipos de pregunta", body: "Opcion multiple espacios lectura de codigo y prediccion de salida sin ejecucion online." }] },
    fr: { eyebrow: "Bases C++", title: "Syntaxe et types", description: "Variables entree sortie conditions boucles fonctions et lecture de code.", sections: [{ title: "Perimetre central", body: "int double char string cin cout if else for while et fonctions.", examples: basicsExamples }, { title: "Types de questions", body: "Choix trous lecture de code et prediction de sortie sans execution en ligne." }] },
    de: { eyebrow: "C++ Grundlagen", title: "Syntax und Typen", description: "Variablen Eingabe Ausgabe Verzweigungen Schleifen Funktionen und Code lesen.", sections: [{ title: "Kernumfang", body: "int double char string cin cout if else for while und Funktionen.", examples: basicsExamples }, { title: "Fragetypen", body: "Auswahl Luecken Code lesen und Ausgabe vorhersagen ohne Online Ausfuehrung." }] },
    pt: { eyebrow: "Base C++", title: "Sintaxe e tipos", description: "Variaveis entrada saida decisoes lacos funcoes e leitura de codigo.", sections: [{ title: "Escopo central", body: "int double char string cin cout if else for while e funcoes.", examples: basicsExamples }, { title: "Tipos de questao", body: "Escolha lacunas leitura de codigo e previsao de saida sem execucao online." }] },
    ru: { eyebrow: "Основы C++", title: "Синтаксис и типы", description: "Переменные ввод вывод ветвления циклы функции и чтение кода.", sections: [{ title: "Ключевой объем", body: "int double char string cin cout if else for while и функции.", examples: basicsExamples }, { title: "Типы вопросов", body: "Выбор пропуски чтение кода и прогноз вывода без онлайн запуска." }] },
    ar: { eyebrow: "أساسيات C++", title: "الصياغة والأنواع", description: "متغيرات وإدخال وإخراج وتفرعات وحلقات ودوال مع قراءة كود مكثفة", sections: [{ title: "النطاق الأساسي", body: "int و double و char و string و cin و cout و if else و for while والدوال مع التركيز على تغير القيم", examples: basicsExamples }, { title: "أنواع الأسئلة", body: "اختيار وملء فراغ وقراءة كود وتوقع مخرجات بدون تشغيل كود على الإنترنت" }] },
    hi: { eyebrow: "C++ आधार", title: "सिंटैक्स और टाइप", description: "वेरिएबल इनपुट आउटपुट शाखा लूप फंक्शन और कोड रीडिंग.", sections: [{ title: "मुख्य दायरा", body: "int double char string cin cout if else for while और functions.", examples: basicsExamples }, { title: "प्रश्न प्रकार", body: "choice fill blank code reading और output prediction बिना online run के." }] },
    id: { eyebrow: "Dasar C++", title: "Sintaks dan tipe", description: "Variabel input output cabang loop fungsi dan baca kode.", sections: [{ title: "Ruang inti", body: "int double char string cin cout if else for while dan fungsi.", examples: basicsExamples }, { title: "Tipe soal", body: "Pilihan isian baca kode dan prediksi keluaran tanpa eksekusi online." }] },
    vi: { eyebrow: "Co ban C++", title: "Cu phap va kieu", description: "Bien nhap xuat nhanh vong lap ham va doc ma.", sections: [{ title: "Pham vi chinh", body: "int double char string cin cout if else for while va ham.", examples: basicsExamples }, { title: "Dang cau hoi", body: "Lua chon dien khuyet doc ma va doan dau ra khong can chay online." }] },
    th: { eyebrow: "พื้นฐาน C++", title: "ไวยากรณ์และชนิด", description: "ตัวแปร อินพุตเอาต์พุต เงื่อนไข ลูป ฟังก์ชัน และอ่านโค้ด", sections: [{ title: "ขอบเขตหลัก", body: "int double char string cin cout if else for while และฟังก์ชัน", examples: basicsExamples }, { title: "ชนิดคำถาม", body: "ตัวเลือก เติมคำ อ่านโค้ด และทำนายผลลัพธ์โดยไม่รันออนไลน์" }] },
    tr: { eyebrow: "C++ temel", title: "Sozdizimi ve tipler", description: "Degisken girdi cikti kosul dongu fonksiyon ve kod okuma.", sections: [{ title: "Ana kapsam", body: "int double char string cin cout if else for while ve fonksiyonlar.", examples: basicsExamples }, { title: "Soru tipleri", body: "Secim bosluk kod okuma ve cikti tahmini online calistirma olmadan." }] },
    it: { eyebrow: "Base C++", title: "Sintassi e tipi", description: "Variabili input output rami cicli funzioni e lettura codice.", sections: [{ title: "Ambito centrale", body: "int double char string cin cout if else for while e funzioni.", examples: basicsExamples }, { title: "Tipi di domanda", body: "Scelta completamento lettura codice e previsione output senza esecuzione online." }] },
    nl: { eyebrow: "C++ basis", title: "Syntaxis en typen", description: "Variabelen input output takken lussen functies en code lezen.", sections: [{ title: "Kernscope", body: "int double char string cin cout if else for while en functies.", examples: basicsExamples }, { title: "Vraagtypen", body: "Keuze invullen code lezen en uitvoer voorspellen zonder online uitvoering." }] },
    pl: { eyebrow: "Podstawy C++", title: "Skladnia i typy", description: "Zmienne wejscie wyjscie warunki petle funkcje i czytanie kodu.", sections: [{ title: "Zakres glowny", body: "int double char string cin cout if else for while i funkcje.", examples: basicsExamples }, { title: "Typy pytan", body: "Wybor luki czytanie kodu i przewidywanie wyjscia bez uruchamiania online." }] },
  },
  oop: {
    en: { eyebrow: "C++ OOP", title: "Object Oriented C++", description: "class object public private constructors members and inheritance.", sections: [{ title: "Core concepts", body: "A class groups state and behavior. Access control decides what outside code can touch." }, { title: "Practice goal", body: "Read class definitions predict object state and understand constructor order." }] },
    zh: { eyebrow: "C++ 面向对象", title: "对象 类和访问控制", description: "class object public private constructor member inheritance 按读代码方式学习", sections: [{ title: "核心概念", body: "class 把状态和行为放在一起 public private 决定外部代码能不能访问成员" }, { title: "练习目标", body: "读懂类定义 判断对象状态 理解构造顺序和成员调用" }] },
    ja: { eyebrow: "C++ OOP", title: "オブジェクト指向 C++", description: "class object public private constructor member inheritance をコード読解で学びます", sections: [{ title: "中心概念", body: "class は状態と動作をまとめます public private は外部コードから触れる範囲を決めます" }, { title: "練習目標", body: "クラス定義を読み オブジェクト状態とコンストラクタ順序を予測します" }] },
    ko: { eyebrow: "C++ OOP", title: "객체 지향 C++", description: "class object public private constructor member inheritance 를 코드로 읽습니다", sections: [{ title: "핵심 개념", body: "class 는 상태와 동작을 묶고 public private 는 외부 접근 범위를 정합니다" }, { title: "연습 목표", body: "클래스 정의를 읽고 객체 상태와 생성자 순서를 예측합니다" }] },
    es: { eyebrow: "C++ OOP", title: "C++ orientado a objetos", description: "class object public private constructor member inheritance con lectura de codigo.", sections: [{ title: "Conceptos centrales", body: "Una class agrupa estado y comportamiento. El control de acceso decide que toca el codigo externo." }, { title: "Objetivo de practica", body: "Leer definiciones de class predecir estado de object y entender orden de constructor." }] },
    fr: { eyebrow: "C++ OOP", title: "C++ oriente objet", description: "class object public private constructor member inheritance en lecture de code.", sections: [{ title: "Concepts centraux", body: "Une class groupe etat et comportement. Le controle d acces decide ce que le code externe touche." }, { title: "Objectif pratique", body: "Lire les definitions de class prevoir l etat objet et comprendre l ordre des constructeurs." }] },
    de: { eyebrow: "C++ OOP", title: "Objektorientiertes C++", description: "class object public private constructor member inheritance durch Code Lesen.", sections: [{ title: "Kernkonzepte", body: "Eine class gruppiert Zustand und Verhalten. Zugriffskontrolle entscheidet was externer Code beruehren darf." }, { title: "Trainingsziel", body: "Klassendefinitionen lesen Objektzustand vorhersagen und Konstruktorreihenfolge verstehen." }] },
    pt: { eyebrow: "C++ OOP", title: "C++ orientado a objetos", description: "class object public private constructor member inheritance lendo codigo.", sections: [{ title: "Conceitos centrais", body: "Uma class agrupa estado e comportamento. Controle de acesso decide o que codigo externo pode tocar." }, { title: "Meta de treino", body: "Ler definicoes de class prever estado do object e entender ordem do constructor." }] },
    ru: { eyebrow: "C++ OOP", title: "Объектный C++", description: "class object public private constructor member inheritance через чтение кода.", sections: [{ title: "Ключевые идеи", body: "class объединяет состояние и поведение. Контроль доступа решает что доступно внешнему коду." }, { title: "Цель практики", body: "Читать class, прогнозировать состояние object и порядок constructor." }] },
    ar: { eyebrow: "كائنية C++", title: "البرمجة الكائنية في C++", description: "class و object و public private و constructor و members و inheritance", sections: [{ title: "المفاهيم الأساسية", body: "class يجمع الحالة والسلوك و public private يحددان ما يمكن للكود الخارجي الوصول إليه" }, { title: "هدف التدريب", body: "اقرأ تعريفات class وتوقع حالة object وافهم ترتيب constructor" }] },
    hi: { eyebrow: "C++ OOP", title: "ऑब्जेक्ट ओरिएंटेड C++", description: "class object public private constructor member inheritance कोड पढ़कर.", sections: [{ title: "मुख्य विचार", body: "class state और behavior को साथ रखता है. access control तय करता है बाहर का code क्या छू सकता है." }, { title: "अभ्यास लक्ष्य", body: "class definition पढ़ना, object state अनुमान लगाना और constructor order समझना." }] },
    id: { eyebrow: "C++ OOP", title: "C++ berorientasi objek", description: "class object public private constructor member inheritance lewat baca kode.", sections: [{ title: "Konsep inti", body: "class menyatukan state dan behavior. Access control menentukan bagian yang bisa disentuh kode luar." }, { title: "Tujuan latihan", body: "Baca definisi class prediksi state object dan pahami urutan constructor." }] },
    vi: { eyebrow: "C++ OOP", title: "C++ huong doi tuong", description: "class object public private constructor member inheritance bang cach doc ma.", sections: [{ title: "Khai niem cot loi", body: "class gom trang thai va hanh vi. Access control quyet dinh code ben ngoai cham duoc gi." }, { title: "Muc tieu luyen tap", body: "Doc dinh nghia class doan trang thai object va hieu thu tu constructor." }] },
    th: { eyebrow: "C++ OOP", title: "C++ เชิงวัตถุ", description: "class object public private constructor member inheritance ผ่านการอ่านโค้ด", sections: [{ title: "แนวคิดหลัก", body: "class รวมสถานะและพฤติกรรม public private กำหนดว่าโค้ดภายนอกเข้าถึงอะไรได้" }, { title: "เป้าหมายฝึก", body: "อ่าน class ทำนายสถานะ object และเข้าใจลำดับ constructor" }] },
    tr: { eyebrow: "C++ OOP", title: "Nesne yonelimli C++", description: "class object public private constructor member inheritance kod okuyarak.", sections: [{ title: "Temel kavramlar", body: "class durum ve davranisi toplar. Access control dis kodun neye dokunabilecegini belirler." }, { title: "Pratik hedefi", body: "Class tanimlarini oku object durumunu tahmin et constructor sirasini anla." }] },
    it: { eyebrow: "C++ OOP", title: "C++ a oggetti", description: "class object public private constructor member inheritance leggendo codice.", sections: [{ title: "Concetti centrali", body: "Una class unisce stato e comportamento. Il controllo accesso decide cosa puo toccare codice esterno." }, { title: "Obiettivo pratica", body: "Leggere definizioni class prevedere stato object e capire ordine constructor." }] },
    nl: { eyebrow: "C++ OOP", title: "Objectgericht C++", description: "class object public private constructor member inheritance via code lezen.", sections: [{ title: "Kernconcepten", body: "Een class groepeert state en gedrag. Access control bepaalt wat externe code mag aanraken." }, { title: "Oefendoel", body: "Class definities lezen objectstatus voorspellen en constructor volgorde begrijpen." }] },
    pl: { eyebrow: "C++ OOP", title: "C++ obiektowy", description: "class object public private constructor member inheritance przez czytanie kodu.", sections: [{ title: "Koncepcje glowne", body: "class laczy stan i zachowanie. Kontrola dostepu decyduje co moze dotknac kod zewnetrzny." }, { title: "Cel treningu", body: "Czytac definicje class przewidywac stan object i rozumiec kolejnosc constructor." }] },
  },
  stl: {
    en: { eyebrow: "C++ STL", title: "STL Containers", description: "vector map set queue stack and common operations.", sections: [{ title: "Containers", body: "vector map set queue and stack cover most beginner storage patterns.", examples: stlExamples }, { title: "Practice", body: "Choose the right container read short snippets and predict output." }] },
    zh: { eyebrow: "C++ STL", title: "STL 容器", description: "vector map set queue stack 以及常见操作", sections: [{ title: "容器", body: "vector map set queue stack 覆盖多数初学者常见存储场景 先学什么时候用 再学怎么读代码", examples: stlExamples }, { title: "练习", body: "选择合适容器 阅读短代码片段 并预测输出结果" }] },
    ja: { eyebrow: "C++ STL", title: "STL コンテナ", description: "vector map set queue stack とよく使う操作を学びます", sections: [{ title: "コンテナ", body: "vector map set queue stack は初級の保存パターンの多くをカバーします 使いどころとコード読解を一緒に練習します", examples: stlExamples }, { title: "練習", body: "適切なコンテナを選び 短いコードを読み 出力を予測します" }] },
    ko: { eyebrow: "C++ STL", title: "STL 컨테이너", description: "vector map set queue stack 과 공통 연산", sections: [{ title: "컨테이너", body: "vector map set queue stack 은 초급 저장 패턴 대부분을 다룹니다", examples: stlExamples }, { title: "연습", body: "맞는 컨테이너를 고르고 짧은 코드를 읽어 출력을 예측합니다" }] },
    es: { eyebrow: "C++ STL", title: "Contenedores STL", description: "vector map set queue stack y operaciones comunes.", sections: [{ title: "Contenedores", body: "vector map set queue y stack cubren la mayoria de patrones iniciales.", examples: stlExamples }, { title: "Practica", body: "Elegir contenedor leer fragmentos cortos y predecir salida." }] },
    fr: { eyebrow: "C++ STL", title: "Conteneurs STL", description: "vector map set queue stack et operations courantes.", sections: [{ title: "Conteneurs", body: "vector map set queue et stack couvrent la plupart des schemas debutants.", examples: stlExamples }, { title: "Pratique", body: "Choisir le bon conteneur lire de courts extraits et prevoir la sortie." }] },
    de: { eyebrow: "C++ STL", title: "STL Container", description: "vector map set queue stack und haeufige Operationen.", sections: [{ title: "Container", body: "vector map set queue und stack decken die meisten Einsteiger Speicherformen ab.", examples: stlExamples }, { title: "Training", body: "Passenden Container waehlen kurze Snippets lesen und Ausgabe vorhersagen." }] },
    pt: { eyebrow: "C++ STL", title: "Containers STL", description: "vector map set queue stack e operacoes comuns.", sections: [{ title: "Containers", body: "vector map set queue e stack cobrem a maioria dos padroes iniciais.", examples: stlExamples }, { title: "Treino", body: "Escolha o container certo leia trechos curtos e preveja a saida." }] },
    ru: { eyebrow: "C++ STL", title: "Контейнеры STL", description: "vector map set queue stack и частые операции.", sections: [{ title: "Контейнеры", body: "vector map set queue и stack покрывают большинство базовых схем хранения.", examples: stlExamples }, { title: "Практика", body: "Выбирать контейнер читать короткий код и прогнозировать вывод." }] },
    ar: { eyebrow: "C++ STL", title: "حاويات STL", description: "vector و map و set و queue و stack والعمليات الشائعة", sections: [{ title: "الحاويات", body: "vector و map و set و queue و stack تغطي معظم أنماط التخزين للمبتدئين", examples: stlExamples }, { title: "التدريب", body: "اختر الحاوية المناسبة واقرأ مقاطع قصيرة وتوقع المخرجات" }] },
    hi: { eyebrow: "C++ STL", title: "STL कंटेनर", description: "vector map set queue stack और सामान्य operations.", sections: [{ title: "कंटेनर", body: "vector map set queue और stack शुरुआती storage patterns को कवर करते हैं.", examples: stlExamples }, { title: "अभ्यास", body: "सही container चुनें छोटे snippets पढ़ें और output अनुमान लगाएं." }] },
    id: { eyebrow: "C++ STL", title: "Container STL", description: "vector map set queue stack dan operasi umum.", sections: [{ title: "Container", body: "vector map set queue dan stack mencakup pola penyimpanan awal.", examples: stlExamples }, { title: "Latihan", body: "Pilih container yang tepat baca snippet pendek dan prediksi keluaran." }] },
    vi: { eyebrow: "C++ STL", title: "Container STL", description: "vector map set queue stack va thao tac thuong gap.", sections: [{ title: "Container", body: "vector map set queue va stack bao phu hau het mau luu tru co ban.", examples: stlExamples }, { title: "Luyen tap", body: "Chon container dung doc doan ma ngan va doan dau ra." }] },
    th: { eyebrow: "C++ STL", title: "คอนเทนเนอร์ STL", description: "vector map set queue stack และงานที่ใช้บ่อย", sections: [{ title: "คอนเทนเนอร์", body: "vector map set queue และ stack ครอบคลุมรูปแบบเก็บข้อมูลพื้นฐานส่วนใหญ่", examples: stlExamples }, { title: "ฝึก", body: "เลือกคอนเทนเนอร์ อ่านโค้ดสั้น และทำนายผลลัพธ์" }] },
    tr: { eyebrow: "C++ STL", title: "STL container", description: "vector map set queue stack ve yaygin islemler.", sections: [{ title: "Container", body: "vector map set queue ve stack baslangic depolama kaliplarinin cogunu kapsar.", examples: stlExamples }, { title: "Pratik", body: "Dogru container sec kisa kod oku ve ciktiyi tahmin et." }] },
    it: { eyebrow: "C++ STL", title: "Container STL", description: "vector map set queue stack e operazioni comuni.", sections: [{ title: "Container", body: "vector map set queue e stack coprono la maggior parte dei pattern iniziali.", examples: stlExamples }, { title: "Pratica", body: "Scegliere il container leggere snippet brevi e prevedere output." }] },
    nl: { eyebrow: "C++ STL", title: "STL containers", description: "vector map set queue stack en veelgebruikte operaties.", sections: [{ title: "Containers", body: "vector map set queue en stack dekken de meeste basis opslagpatronen.", examples: stlExamples }, { title: "Oefening", body: "Kies de juiste container lees korte snippets en voorspel uitvoer." }] },
    pl: { eyebrow: "C++ STL", title: "Kontenery STL", description: "vector map set queue stack i typowe operacje.", sections: [{ title: "Kontenery", body: "vector map set queue i stack pokrywaja wiekszosc podstawowych wzorcow przechowywania.", examples: stlExamples }, { title: "Trening", body: "Wybrac kontener czytac krotkie fragmenty i przewidywac wyjscie." }] },
  },
  algorithms: {
    en: { eyebrow: "C++ Algorithms", title: "Algorithm Basics", description: "Simulation arrays strings searching counting and output prediction.", sections: [{ title: "First scope", body: "Loop simulation array traversal string processing simple search counting and output prediction." }, { title: "Later scope", body: "Online execution judging leaderboards submissions and solution notes can come after the core is stable." }] },
    zh: { eyebrow: "C++ 算法", title: "基础算法", description: "模拟 数组 字符串 搜索 计数和输出预测", sections: [{ title: "第一版范围", body: "循环模拟 数组遍历 字符串处理 简单搜索 计数和输出预测 先把读题和读代码做稳" }, { title: "后续范围", body: "在线运行 自动判题 排行榜 提交记录和题解区等到核心稳定后再加" }] },
    ja: { eyebrow: "C++ アルゴリズム", title: "基礎アルゴリズム", description: "シミュレーション 配列 文字列 探索 カウント 出力予測", sections: [{ title: "初版の範囲", body: "ループシミュレーション 配列走査 文字列処理 簡単な探索 カウント 出力予測を扱います" }, { title: "後で追加する範囲", body: "オンライン実行 自動採点 ランキング 提出履歴 解説エリアは中核が安定した後に追加できます" }] },
    ko: { eyebrow: "C++ 알고리즘", title: "알고리즘 기초", description: "시뮬레이션 배열 문자열 탐색 카운팅 출력 예측", sections: [{ title: "첫 범위", body: "루프 시뮬레이션 배열 순회 문자열 처리 간단 탐색 카운팅 출력 예측" }, { title: "나중 범위", body: "온라인 실행 채점 순위 제출 기록 해설은 핵심이 안정된 뒤 추가합니다" }] },
    es: { eyebrow: "Algoritmos C++", title: "Base de algoritmos", description: "Simulacion arrays strings busqueda conteo y prediccion de salida.", sections: [{ title: "Primer alcance", body: "Simulacion de bucles recorrido de arrays procesamiento de strings busqueda simple conteo y salida." }, { title: "Alcance posterior", body: "Ejecucion online jueces ranking envios y notas de solucion pueden venir despues." }] },
    fr: { eyebrow: "Algorithmes C++", title: "Bases des algorithmes", description: "Simulation tableaux strings recherche comptage et prediction de sortie.", sections: [{ title: "Premier perimetre", body: "Simulation de boucles parcours de tableaux traitement de strings recherche simple comptage et sortie." }, { title: "Perimetre plus tard", body: "Execution en ligne jugement classements soumissions et notes de solution peuvent venir apres." }] },
    de: { eyebrow: "C++ Algorithmen", title: "Algorithmus Grundlagen", description: "Simulation Arrays Strings Suche Zaehlen und Ausgabevorhersage.", sections: [{ title: "Erster Umfang", body: "Schleifensimulation Array Traversal String Verarbeitung einfache Suche Zaehlen und Ausgabe." }, { title: "Spaeterer Umfang", body: "Online Ausfuehrung Bewertung Ranglisten Einreichungen und Loesungsnotizen koennen spaeter kommen." }] },
    pt: { eyebrow: "Algoritmos C++", title: "Base de algoritmos", description: "Simulacao arrays strings busca contagem e previsao de saida.", sections: [{ title: "Primeiro escopo", body: "Simulacao de lacos passagem por arrays processamento de strings busca simples contagem e saida." }, { title: "Escopo posterior", body: "Execucao online juiz ranking envios e notas de solucao podem vir depois." }] },
    ru: { eyebrow: "Алгоритмы C++", title: "Основы алгоритмов", description: "Симуляция массивы строки поиск подсчет и прогноз вывода.", sections: [{ title: "Первый объем", body: "Симуляция циклов обход массивов обработка строк простой поиск подсчет и вывод." }, { title: "Позже", body: "Онлайн запуск проверка рейтинги отправки и заметки решений можно добавить позже." }] },
    ar: { eyebrow: "خوارزميات C++", title: "أساسيات الخوارزميات", description: "محاكاة ومصفوفات وسلاسل وبحث وعد وتوقع مخرجات", sections: [{ title: "نطاق النسخة الأولى", body: "محاكاة الحلقات ومرور المصفوفات ومعالجة السلاسل والبحث البسيط والعد وتوقع المخرجات" }, { title: "نطاق لاحق", body: "تشغيل الكود والتحكيم الآلي والترتيب وسجل الإرسال والشروحات يمكن إضافتها بعد استقرار الأساس" }] },
    hi: { eyebrow: "C++ एल्गोरिदम", title: "एल्गोरिदम आधार", description: "simulation arrays strings searching counting और output prediction.", sections: [{ title: "पहला दायरा", body: "loop simulation array traversal string processing simple search counting और output prediction." }, { title: "बाद का दायरा", body: "online execution judging leaderboard submissions और solution notes बाद में आएंगे." }] },
    id: { eyebrow: "Algoritma C++", title: "Dasar algoritma", description: "Simulasi array string pencarian hitung dan prediksi keluaran.", sections: [{ title: "Ruang awal", body: "Simulasi loop traversal array pemrosesan string pencarian sederhana hitung dan output." }, { title: "Ruang nanti", body: "Eksekusi online penilaian ranking submission dan catatan solusi bisa ditambah setelah stabil." }] },
    vi: { eyebrow: "Thuat toan C++", title: "Co ban thuat toan", description: "Mo phong mang chuoi tim kiem dem va doan dau ra.", sections: [{ title: "Pham vi dau", body: "Mo phong vong lap duyet mang xu ly chuoi tim kiem don gian dem va dau ra." }, { title: "Pham vi sau", body: "Chay online cham diem bang xep hang nop bai va loi giai co the them sau." }] },
    th: { eyebrow: "อัลกอริทึม C++", title: "พื้นฐานอัลกอริทึม", description: "จำลอง อาร์เรย์ สตริง ค้นหา นับ และทำนายผลลัพธ์", sections: [{ title: "ขอบเขตแรก", body: "จำลองลูป เดินอาร์เรย์ จัดการสตริง ค้นหาง่าย นับ และทำนายผลลัพธ์" }, { title: "ขอบเขตภายหลัง", body: "รันออนไลน์ ตรวจคำตอบ อันดับ ส่งคำตอบ และเฉลยเพิ่มได้หลังแกนหลักนิ่ง" }] },
    tr: { eyebrow: "C++ algoritmalar", title: "Algoritma temeli", description: "Simulasyon array string arama sayma ve cikti tahmini.", sections: [{ title: "Ilk kapsam", body: "Dongu simulasyonu array gezme string isleme basit arama sayma ve cikti." }, { title: "Sonraki kapsam", body: "Online calistirma degerlendirme siralama gonderim ve cozum notlari sonra eklenebilir." }] },
    it: { eyebrow: "Algoritmi C++", title: "Basi algoritmo", description: "Simulazione array string ricerca conteggio e previsione output.", sections: [{ title: "Primo ambito", body: "Simulazione cicli attraversamento array trattamento string ricerca semplice conteggio e output." }, { title: "Ambito futuro", body: "Esecuzione online giudizio classifiche invii e note soluzione possono arrivare dopo." }] },
    nl: { eyebrow: "C++ algoritmen", title: "Algoritme basis", description: "Simulatie arrays strings zoeken tellen en uitvoer voorspellen.", sections: [{ title: "Eerste scope", body: "Lus simulatie array traversal string verwerking eenvoudige zoekactie tellen en uitvoer." }, { title: "Latere scope", body: "Online uitvoering beoordeling ranglijsten inzendingen en oplossingsnotities kunnen later." }] },
    pl: { eyebrow: "Algorytmy C++", title: "Podstawy algorytmow", description: "Symulacja tablice stringi szukanie liczenie i przewidywanie wyjscia.", sections: [{ title: "Pierwszy zakres", body: "Symulacja petli przejscie tablic obsluga stringow proste szukanie liczenie i wyjscie." }, { title: "Pozniejszy zakres", body: "Uruchamianie online ocenianie rankingi zgloszenia i notatki rozwiazan mozna dodac pozniej." }] },
  },
};
