import { languageHtmlLang, type InterfaceLanguage } from "@/lib/language";

type StudyPageCopy = {
  directions: {
    english: string;
    cpp: string;
  };
  status: {
    completed: string;
    inProgress: string;
  };
  dashboard: {
    eyebrow: string;
    title: string;
    intro: (email: string) => string;
    today: string;
    wrong: string;
    progress: string;
    completed: string;
    completion: string;
    wrongItems: string;
    englishComplete: string;
    englishCompleteBody: string;
    cppComplete: string;
    cppCompleteBody: string;
    continueEnglish: string;
    continueCpp: string;
    loopEyebrow: string;
    loopTitle: string;
    todayPlan: string;
    todayPlanHint: string;
    wrongBank: string;
    wrongBankHint: string;
    tools: string;
    toolsHint: string;
    recentEyebrow: string;
    recentTitle: string;
    noRecent: string;
  };
  progress: {
    eyebrow: string;
    title: string;
    intro: string;
    completed: string;
    started: string;
    completion: string;
    updated: string;
    empty: string;
    startEnglish: string;
    startCpp: string;
  };
  wrong: {
    eyebrow: string;
    title: string;
    intro: string;
    start: string;
    today: string;
    progress: string;
    all: string;
    loopEyebrow: string;
    step1: string;
    step1Hint: string;
    step2: string;
    step2Hint: string;
    step3: string;
    step3Hint: string;
    backToLesson: string;
    yourAnswer: string;
    noAnswer: string;
    correctAnswer: string;
    explanation: string;
    empty: string;
    goEnglish: string;
    goCpp: string;
  };
};

type LearnPageCopy = {
  path: string;
  open: string;
  completed: string;
  start: string;
  progress: string;
  wrong: string;
  backToPath: (direction: string) => string;
  estimated: (minutes: number) => string;
  exampleCount: (count: number) => string;
  exerciseCount: (count: number) => string;
  notCompleted: string;
  nextLesson: (title: string) => string;
  explanation: string;
  examples: string;
  noExamples: string;
  practice: string;
  noPractice: string;
  previous: string;
  next: string;
  firstLesson: string;
  courseDoneEyebrow: string;
  reviewWrong: string;
  reviewWrongBody: string;
  markStatus: string;
  saveProgress: string;
  markComplete: string;
  saved: string;
  loginFirst: string;
};

const en: StudyPageCopy = {
  directions: { english: "English", cpp: "C++" },
  status: { completed: "Completed", inProgress: "In progress" },
  dashboard: {
    eyebrow: "Continue Learning",
    title: "Your next study step",
    intro: (email) => `${email} can jump back into English, C++, today's plan, and wrong-question review from one place.`,
    today: "Open Today's Plan",
    wrong: "Review Wrong Questions",
    progress: "Full Progress",
    completed: "Completed",
    completion: "Completion",
    wrongItems: "Wrong Items",
    englishComplete: "English path complete",
    englishCompleteBody: "You have completed the published English lessons. Use review and typing practice to keep momentum.",
    cppComplete: "C++ path complete",
    cppCompleteBody: "You have completed the published C++ lessons. Review code-reading and output-prediction questions next.",
    continueEnglish: "Continue English",
    continueCpp: "Continue C++",
    loopEyebrow: "Learning Loop",
    loopTitle: "Today, practice, review",
    todayPlan: "Today Plan",
    todayPlanHint: "Daily entry",
    wrongBank: "Wrong Bank",
    wrongBankHint: "Fix mistakes",
    tools: "AI Tools",
    toolsHint: "Support only",
    recentEyebrow: "Recent Activity",
    recentTitle: "Last touched lessons",
    noRecent: "No saved lesson activity yet. Start with English or C++.",
  },
  progress: {
    eyebrow: "My Progress",
    title: "Learning progress",
    intro: "This page records the lessons you have started and completed. Keep the loop clear: learn, practice, review.",
    completed: "Completed",
    started: "Started",
    completion: "Completion",
    updated: "Updated",
    empty: "No learning record yet",
    startEnglish: "Start English",
    startCpp: "Start C++",
  },
  wrong: {
    eyebrow: "Wrong Questions",
    title: "Review center",
    intro: "Wrong answers are the next study plan. Recall first, read the explanation, then return to the lesson.",
    start: "Start with latest wrong item",
    today: "Back to today",
    progress: "View progress",
    all: "All wrong items",
    loopEyebrow: "Review Loop",
    step1: "1. Hide the answer",
    step1Hint: "Recall once",
    step2: "2. Read explanation",
    step2Hint: "Find the cause",
    step3: "3. Return to lesson",
    step3Hint: "Practice again",
    backToLesson: "Back to lesson",
    yourAnswer: "Your answer",
    noAnswer: "Not recorded",
    correctAnswer: "Correct answer",
    explanation: "Explanation",
    empty: "No wrong items yet. Finish an English or C++ practice set first.",
    goEnglish: "Study English",
    goCpp: "Study C++",
  },
};

function studyCopyFrom(input: {
  directions: StudyPageCopy["directions"];
  status: StudyPageCopy["status"];
  dashboard: Partial<StudyPageCopy["dashboard"]>;
  progress: Partial<StudyPageCopy["progress"]>;
  wrong: Partial<StudyPageCopy["wrong"]>;
}): StudyPageCopy {
  return {
    directions: input.directions,
    status: input.status,
    dashboard: { ...en.dashboard, ...input.dashboard },
    progress: { ...en.progress, ...input.progress },
    wrong: { ...en.wrong, ...input.wrong },
  };
}

const studyCopy: Record<InterfaceLanguage, StudyPageCopy> = {
  en,
  zh: {
    ...en,
    directions: { english: "英语", cpp: "C++" },
    status: { completed: "已完成", inProgress: "学习中" },
    dashboard: {
      ...en.dashboard,
      eyebrow: "继续学习",
      title: "下一步学习",
      intro: (email) => `${email} 可以从这里继续英语 C++ 今日计划和错题复习`,
      today: "打开今日计划",
      wrong: "复习错题",
      progress: "完整进度",
      completed: "已完成",
      completion: "完成率",
      wrongItems: "错题数",
      englishComplete: "英语路径已完成",
      englishCompleteBody: "已完成发布的英语课程 可以继续用复习和打字练习保持节奏",
      cppComplete: "C++ 路径已完成",
      cppCompleteBody: "已完成发布的 C++ 课程 接下来复习代码阅读和输出判断",
      continueEnglish: "继续英语",
      continueCpp: "继续 C++",
      loopEyebrow: "学习闭环",
      loopTitle: "今日 练习 复习",
      todayPlan: "今日计划",
      todayPlanHint: "每日入口",
      wrongBank: "错题本",
      wrongBankHint: "修正错误",
      tools: "AI 工具",
      toolsHint: "辅助学习",
      recentEyebrow: "最近活动",
      recentTitle: "最近学习的课程",
      noRecent: "还没有学习记录 先从英语或 C++ 开始",
    },
    progress: {
      ...en.progress,
      eyebrow: "我的进度",
      title: "学习进度",
      intro: "这里记录你已经开始和完成的知识点 先把学习 练习 复习的闭环跑顺",
      completed: "已完成",
      started: "已开始",
      completion: "完成率",
      updated: "最近更新",
      empty: "还没有学习记录",
      startEnglish: "开始英语",
      startCpp: "开始 C++",
    },
    wrong: {
      ...en.wrong,
      eyebrow: "错题复习",
      title: "错题复习中心",
      intro: "错题不是垃圾桶 是下一轮学习计划 先回忆答案 再看解析 最后回知识点重练",
      start: "从最近错题开始",
      today: "回到今日计划",
      progress: "查看进度",
      all: "全部错题",
      loopEyebrow: "复习闭环",
      step1: "1 先遮住答案",
      step1Hint: "自己回忆一次",
      step2: "2 看解析",
      step2Hint: "找出错因",
      step3: "3 回知识点",
      step3Hint: "重做相关练习",
      backToLesson: "回到知识点",
      yourAnswer: "你的答案",
      noAnswer: "未记录",
      correctAnswer: "正确答案",
      explanation: "解析",
      empty: "还没有错题 先完成一组英语或 C++ 练习",
      goEnglish: "去学英语",
      goCpp: "去学 C++",
    },
  },
  ja: {
    ...en,
    directions: { english: "英語", cpp: "C++" },
    status: { completed: "完了", inProgress: "学習中" },
    dashboard: {
      ...en.dashboard,
      eyebrow: "学習を続ける",
      title: "次の学習ステップ",
      intro: (email) => `${email} は英語 C++ 今日の計画 復習へすぐ戻れます`,
      today: "今日の計画を開く",
      wrong: "間違いを復習",
      progress: "進捗を見る",
      completed: "完了",
      completion: "達成率",
      wrongItems: "間違い",
      englishComplete: "英語パス完了",
      englishCompleteBody: "公開済みの英語レッスンは完了です 復習とタイピングで維持しましょう",
      cppComplete: "C++ パス完了",
      cppCompleteBody: "公開済みの C++ レッスンは完了です 次はコード読解と出力予測を復習しましょう",
      continueEnglish: "英語を続ける",
      continueCpp: "C++ を続ける",
      loopEyebrow: "学習ループ",
      loopTitle: "今日 練習 復習",
      todayPlan: "今日の計画",
      todayPlanHint: "毎日の入口",
      wrongBank: "復習ノート",
      wrongBankHint: "ミスを直す",
      tools: "AI ツール",
      toolsHint: "学習補助",
      recentEyebrow: "最近の活動",
      recentTitle: "最近触れたレッスン",
      noRecent: "まだ学習記録はありません 英語か C++ から始めましょう",
    },
    progress: {
      ...en.progress,
      eyebrow: "進捗",
      title: "学習進捗",
      intro: "開始済み 完了済みのレッスンを記録します 学ぶ 練習する 復習する流れを保ちましょう",
      completed: "完了",
      started: "開始済み",
      completion: "達成率",
      updated: "更新",
      empty: "学習記録はまだありません",
      startEnglish: "英語を始める",
      startCpp: "C++ を始める",
    },
    wrong: {
      ...en.wrong,
      eyebrow: "間違い復習",
      title: "復習センター",
      intro: "間違いは次の学習計画です まず思い出し 解説を読み レッスンに戻ります",
      start: "最新の間違いから始める",
      today: "今日へ戻る",
      progress: "進捗を見る",
      all: "すべての間違い",
      loopEyebrow: "復習ループ",
      step1: "1 答えを隠す",
      step1Hint: "一度思い出す",
      step2: "2 解説を読む",
      step2Hint: "原因を探す",
      step3: "3 レッスンへ戻る",
      step3Hint: "もう一度練習",
      backToLesson: "レッスンへ戻る",
      yourAnswer: "あなたの答え",
      noAnswer: "記録なし",
      correctAnswer: "正解",
      explanation: "解説",
      empty: "間違いはまだありません 英語か C++ の練習を完了してください",
      goEnglish: "英語へ",
      goCpp: "C++ へ",
    },
  },
  ko: studyCopyFrom({
    directions: { english: "영어", cpp: "C++" },
    status: { completed: "완료", inProgress: "학습 중" },
    dashboard: {
      eyebrow: "계속 학습",
      title: "다음 학습 단계",
      intro: (email) => `${email} 계정으로 영어 C++ 오늘 계획과 오답 복습을 이어갈 수 있습니다`,
      today: "오늘 계획 열기",
      wrong: "오답 복습",
      progress: "진도 보기",
      completed: "완료",
      completion: "완료율",
      wrongItems: "오답 수",
      continueEnglish: "영어 계속",
      continueCpp: "C++ 계속",
      loopTitle: "오늘 연습 복습",
      todayPlan: "오늘 계획",
      wrongBank: "오답 노트",
      tools: "AI 도구",
      recentTitle: "최근 학습한 레슨",
    },
    progress: {
      eyebrow: "내 진도",
      title: "학습 진도",
      intro: "시작한 레슨과 완료한 레슨을 기록합니다 배우고 연습하고 복습하는 흐름을 유지하세요",
      completed: "완료",
      started: "시작",
      completion: "완료율",
      updated: "최근 업데이트",
      empty: "아직 학습 기록이 없습니다",
      startEnglish: "영어 시작",
      startCpp: "C++ 시작",
    },
    wrong: {
      eyebrow: "오답 복습",
      title: "복습 센터",
      intro: "오답은 다음 학습 계획입니다 먼저 떠올리고 해설을 읽은 뒤 레슨으로 돌아가세요",
      start: "최근 오답부터 시작",
      today: "오늘로 돌아가기",
      progress: "진도 보기",
      all: "전체 오답",
      loopEyebrow: "복습 루프",
      backToLesson: "레슨으로 돌아가기",
      yourAnswer: "내 답",
      noAnswer: "기록 없음",
      correctAnswer: "정답",
      explanation: "해설",
      empty: "아직 오답이 없습니다 영어나 C++ 연습을 먼저 완료하세요",
      goEnglish: "영어 학습",
      goCpp: "C++ 학습",
    },
  }),
  es: studyCopyFrom({
    directions: { english: "Ingles", cpp: "C++" },
    status: { completed: "Completado", inProgress: "En curso" },
    dashboard: {
      eyebrow: "Continuar aprendizaje",
      title: "Tu siguiente paso",
      intro: (email) => `${email} puede volver a Ingles C++ plan de hoy y repaso de errores desde un solo lugar`,
      today: "Abrir plan de hoy",
      wrong: "Repasar errores",
      progress: "Ver progreso",
      completed: "Completado",
      completion: "Progreso",
      wrongItems: "Errores",
      continueEnglish: "Seguir Ingles",
      continueCpp: "Seguir C++",
      loopTitle: "Hoy practica repaso",
      todayPlan: "Plan de hoy",
      wrongBank: "Banco de errores",
      tools: "Herramientas IA",
      recentTitle: "Ultimas lecciones",
    },
    progress: {
      eyebrow: "Mi progreso",
      title: "Progreso de aprendizaje",
      intro: "Aqui se guardan las lecciones iniciadas y completadas Mantén el ciclo aprender practicar repasar",
      completed: "Completadas",
      started: "Iniciadas",
      completion: "Progreso",
      updated: "Actualizado",
      empty: "Aun no hay registro de aprendizaje",
      startEnglish: "Empezar Ingles",
      startCpp: "Empezar C++",
    },
    wrong: {
      eyebrow: "Repaso de errores",
      title: "Centro de repaso",
      intro: "Los errores son el siguiente plan de estudio Recuerda primero lee la explicacion y vuelve a la leccion",
      start: "Empezar por el ultimo error",
      today: "Volver a hoy",
      progress: "Ver progreso",
      all: "Todos los errores",
      loopEyebrow: "Ciclo de repaso",
      backToLesson: "Volver a la leccion",
      yourAnswer: "Tu respuesta",
      noAnswer: "Sin registro",
      correctAnswer: "Respuesta correcta",
      explanation: "Explicacion",
      empty: "Aun no hay errores Completa primero una practica de Ingles o C++",
      goEnglish: "Estudiar Ingles",
      goCpp: "Estudiar C++",
    },
  }),
  fr: studyCopyFrom({
    directions: { english: "Anglais", cpp: "C++" },
    status: { completed: "Termine", inProgress: "En cours" },
    dashboard: {
      eyebrow: "Continuer",
      title: "Prochaine etape",
      intro: (email) => `${email} peut reprendre Anglais C++ le plan du jour et la revision des erreurs au meme endroit`,
      today: "Ouvrir le plan du jour",
      wrong: "Reviser les erreurs",
      progress: "Voir la progression",
      completed: "Termine",
      completion: "Progression",
      wrongItems: "Erreurs",
      continueEnglish: "Continuer l'anglais",
      continueCpp: "Continuer C++",
      loopTitle: "Aujourd'hui pratique revision",
      todayPlan: "Plan du jour",
      wrongBank: "Erreurs",
      tools: "Outils IA",
      recentTitle: "Dernieres lecons",
    },
    progress: {
      eyebrow: "Ma progression",
      title: "Progression",
      intro: "Cette page garde les lecons commencees et terminees Gardez le cycle apprendre pratiquer reviser",
      completed: "Terminees",
      started: "Commencees",
      completion: "Progression",
      updated: "Mis a jour",
      empty: "Aucune activite pour le moment",
      startEnglish: "Commencer l'anglais",
      startCpp: "Commencer C++",
    },
    wrong: {
      eyebrow: "Revision des erreurs",
      title: "Centre de revision",
      intro: "Les erreurs deviennent le prochain plan de travail Souvenez vous lisez l'explication puis retournez a la lecon",
      start: "Commencer par la derniere erreur",
      today: "Retour au jour",
      progress: "Voir la progression",
      all: "Toutes les erreurs",
      loopEyebrow: "Cycle de revision",
      backToLesson: "Retour a la lecon",
      yourAnswer: "Votre reponse",
      noAnswer: "Non enregistre",
      correctAnswer: "Bonne reponse",
      explanation: "Explication",
      empty: "Aucune erreur pour le moment Terminez d'abord un exercice d'anglais ou de C++",
      goEnglish: "Etudier l'anglais",
      goCpp: "Etudier C++",
    },
  }),
  de: studyCopyFrom({
    directions: { english: "Englisch", cpp: "C++" },
    status: { completed: "Abgeschlossen", inProgress: "In Arbeit" },
    dashboard: {
      eyebrow: "Weiterlernen",
      title: "Dein naechster Schritt",
      intro: (email) => `${email} kann Englisch C++ Tagesplan und Fehlerwiederholung an einem Ort fortsetzen`,
      today: "Tagesplan oeffnen",
      wrong: "Fehler wiederholen",
      progress: "Fortschritt ansehen",
      completed: "Abgeschlossen",
      completion: "Fortschritt",
      wrongItems: "Fehler",
      continueEnglish: "Englisch weiter",
      continueCpp: "C++ weiter",
      loopTitle: "Heute ueben wiederholen",
      todayPlan: "Tagesplan",
      wrongBank: "Fehlerbank",
      tools: "KI Tools",
      recentTitle: "Letzte Lektionen",
    },
    progress: {
      eyebrow: "Mein Fortschritt",
      title: "Lernfortschritt",
      intro: "Hier werden gestartete und abgeschlossene Lektionen gespeichert Der Ablauf bleibt lernen ueben wiederholen",
      completed: "Abgeschlossen",
      started: "Gestartet",
      completion: "Fortschritt",
      updated: "Aktualisiert",
      empty: "Noch kein Lernverlauf",
      startEnglish: "Englisch starten",
      startCpp: "C++ starten",
    },
    wrong: {
      eyebrow: "Fehler wiederholen",
      title: "Wiederholungszentrum",
      intro: "Fehler sind der naechste Lernplan Erst erinnern dann Erklaerung lesen dann zur Lektion zurueck",
      start: "Mit neuestem Fehler starten",
      today: "Zurueck zu heute",
      progress: "Fortschritt ansehen",
      all: "Alle Fehler",
      loopEyebrow: "Wiederholung",
      backToLesson: "Zur Lektion",
      yourAnswer: "Deine Antwort",
      noAnswer: "Nicht gespeichert",
      correctAnswer: "Richtige Antwort",
      explanation: "Erklaerung",
      empty: "Noch keine Fehler Schließe zuerst eine Englisch oder C++ Uebung ab",
      goEnglish: "Englisch lernen",
      goCpp: "C++ lernen",
    },
  }),
  pt: studyCopyFrom({
    directions: { english: "Ingles", cpp: "C++" },
    status: { completed: "Concluido", inProgress: "Em andamento" },
    dashboard: {
      eyebrow: "Continuar aprendendo",
      title: "Seu proximo passo",
      intro: (email) => `${email} pode voltar para Ingles C++ plano de hoje e revisao de erros em um so lugar`,
      today: "Abrir plano de hoje",
      wrong: "Revisar erros",
      progress: "Ver progresso",
      completed: "Concluido",
      completion: "Progresso",
      wrongItems: "Erros",
      continueEnglish: "Continuar Ingles",
      continueCpp: "Continuar C++",
      loopTitle: "Hoje praticar revisar",
      todayPlan: "Plano de hoje",
      wrongBank: "Banco de erros",
      tools: "Ferramentas IA",
      recentTitle: "Ultimas licoes",
    },
    progress: {
      eyebrow: "Meu progresso",
      title: "Progresso de aprendizagem",
      intro: "Aqui ficam as licoes iniciadas e concluidas Mantenha o ciclo aprender praticar revisar",
      completed: "Concluidas",
      started: "Iniciadas",
      completion: "Progresso",
      updated: "Atualizado",
      empty: "Ainda nao ha registro de estudo",
      startEnglish: "Comecar Ingles",
      startCpp: "Comecar C++",
    },
    wrong: {
      eyebrow: "Revisao de erros",
      title: "Centro de revisao",
      intro: "Os erros viram o proximo plano de estudo Lembre primeiro leia a explicacao e volte para a licao",
      start: "Comecar pelo erro mais recente",
      today: "Voltar para hoje",
      progress: "Ver progresso",
      all: "Todos os erros",
      loopEyebrow: "Ciclo de revisao",
      backToLesson: "Voltar para a licao",
      yourAnswer: "Sua resposta",
      noAnswer: "Nao registrado",
      correctAnswer: "Resposta correta",
      explanation: "Explicacao",
      empty: "Ainda nao ha erros Complete primeiro uma pratica de Ingles ou C++",
      goEnglish: "Estudar Ingles",
      goCpp: "Estudar C++",
    },
  }),
  ru: studyCopyFrom({
    directions: { english: "Английский", cpp: "C++" },
    status: { completed: "Готово", inProgress: "В процессе" },
    dashboard: {
      eyebrow: "Продолжить обучение",
      title: "Следующий шаг",
      intro: (email) => `${email} может вернуться к английскому C++ плану на сегодня и разбору ошибок в одном месте`,
      today: "Открыть план",
      wrong: "Разобрать ошибки",
      progress: "Показать прогресс",
      completed: "Готово",
      completion: "Прогресс",
      wrongItems: "Ошибки",
      continueEnglish: "Продолжить английский",
      continueCpp: "Продолжить C++",
      loopTitle: "Сегодня практика повторение",
      todayPlan: "План на сегодня",
      wrongBank: "Ошибки",
      tools: "AI инструменты",
      recentTitle: "Последние уроки",
    },
    progress: {
      eyebrow: "Мой прогресс",
      title: "Прогресс обучения",
      intro: "Здесь сохраняются начатые и завершенные уроки Держите цикл учиться практиковаться повторять",
      completed: "Готово",
      started: "Начато",
      completion: "Прогресс",
      updated: "Обновлено",
      empty: "Пока нет истории обучения",
      startEnglish: "Начать английский",
      startCpp: "Начать C++",
    },
    wrong: {
      eyebrow: "Разбор ошибок",
      title: "Центр повторения",
      intro: "Ошибки становятся следующим планом Сначала вспомните ответ затем прочитайте объяснение и вернитесь к уроку",
      start: "Начать с последней ошибки",
      today: "Назад к сегодня",
      progress: "Показать прогресс",
      all: "Все ошибки",
      loopEyebrow: "Цикл повторения",
      backToLesson: "К уроку",
      yourAnswer: "Ваш ответ",
      noAnswer: "Не записано",
      correctAnswer: "Правильный ответ",
      explanation: "Объяснение",
      empty: "Ошибок пока нет Сначала завершите практику английского или C++",
      goEnglish: "Учить английский",
      goCpp: "Учить C++",
    },
  }),
  ar: {
    ...en,
    directions: { english: "الإنجليزية", cpp: "C++" },
    status: { completed: "مكتمل", inProgress: "قيد التعلم" },
    dashboard: {
      ...en.dashboard,
      eyebrow: "تابع التعلم",
      title: "خطوتك التالية",
      intro: (email) => `${email} يمكنه العودة إلى الإنجليزية و C++ وخطة اليوم والمراجعة من مكان واحد`,
      today: "افتح خطة اليوم",
      wrong: "راجع الأخطاء",
      progress: "عرض التقدم",
      completed: "مكتمل",
      completion: "نسبة الإنجاز",
      wrongItems: "الأخطاء",
      englishComplete: "مسار الإنجليزية مكتمل",
      englishCompleteBody: "أكملت دروس الإنجليزية المنشورة واصل المراجعة والكتابة للحفاظ على الإيقاع",
      cppComplete: "مسار C++ مكتمل",
      cppCompleteBody: "أكملت دروس C++ المنشورة راجع قراءة الكود وتوقع المخرجات",
      continueEnglish: "تابع الإنجليزية",
      continueCpp: "تابع C++",
      loopEyebrow: "حلقة التعلم",
      loopTitle: "اليوم تدريب مراجعة",
      todayPlan: "خطة اليوم",
      todayPlanHint: "مدخل يومي",
      wrongBank: "دفتر الأخطاء",
      wrongBankHint: "إصلاح الأخطاء",
      tools: "أدوات الذكاء الاصطناعي",
      toolsHint: "مساعدة فقط",
      recentEyebrow: "النشاط الأخير",
      recentTitle: "آخر الدروس",
      noRecent: "لا يوجد نشاط محفوظ بعد ابدأ بالإنجليزية أو C++",
    },
    progress: {
      ...en.progress,
      eyebrow: "تقدمي",
      title: "تقدم التعلم",
      intro: "تسجل هذه الصفحة الدروس التي بدأت بها وأنهيتها حافظ على الحلقة تعلم تدرب راجع",
      completed: "مكتمل",
      started: "بدأت",
      completion: "نسبة الإنجاز",
      updated: "آخر تحديث",
      empty: "لا يوجد سجل تعلم بعد",
      startEnglish: "ابدأ الإنجليزية",
      startCpp: "ابدأ C++",
    },
    wrong: {
      ...en.wrong,
      eyebrow: "مراجعة الأخطاء",
      title: "مركز المراجعة",
      intro: "الإجابات الخاطئة هي خطة التعلم التالية تذكر أولا ثم اقرأ الشرح ثم عد إلى الدرس",
      start: "ابدأ بآخر خطأ",
      today: "العودة إلى اليوم",
      progress: "عرض التقدم",
      all: "كل الأخطاء",
      loopEyebrow: "حلقة المراجعة",
      step1: "1 اخف الإجابة",
      step1Hint: "تذكر مرة واحدة",
      step2: "2 اقرأ الشرح",
      step2Hint: "ابحث عن السبب",
      step3: "3 عد إلى الدرس",
      step3Hint: "تدرب مرة أخرى",
      backToLesson: "العودة إلى الدرس",
      yourAnswer: "إجابتك",
      noAnswer: "غير مسجلة",
      correctAnswer: "الإجابة الصحيحة",
      explanation: "الشرح",
      empty: "لا توجد أخطاء بعد أكمل تدريبا في الإنجليزية أو C++ أولا",
      goEnglish: "تعلم الإنجليزية",
      goCpp: "تعلم C++",
    },
  },
  hi: studyCopyFrom({
    directions: { english: "अंग्रेजी", cpp: "C++" },
    status: { completed: "पूरा", inProgress: "चल रहा है" },
    dashboard: { title: "अगला सीखने का कदम", intro: (email) => `${email} अंग्रेजी C++ आज की योजना और गलती दोहराई को एक जगह से जारी रख सकता है`, today: "आज की योजना खोलें", wrong: "गलतियां दोहराएं", progress: "प्रगति देखें", completed: "पूरा", completion: "प्रगति", wrongItems: "गलतियां", continueEnglish: "अंग्रेजी जारी रखें", continueCpp: "C++ जारी रखें", todayPlan: "आज की योजना", wrongBank: "गलती बैंक", tools: "AI उपकरण" },
    progress: { title: "सीखने की प्रगति", intro: "यहां शुरू और पूरे किए गए पाठ सेव होते हैं सीखना अभ्यास दोहराई का क्रम बनाए रखें", completed: "पूरा", started: "शुरू", completion: "प्रगति", updated: "अपडेट", empty: "अभी कोई सीखने का रिकॉर्ड नहीं", startEnglish: "अंग्रेजी शुरू करें", startCpp: "C++ शुरू करें" },
    wrong: { title: "दोहराई केंद्र", intro: "गलत उत्तर अगली सीखने की योजना हैं पहले याद करें फिर व्याख्या पढ़ें और पाठ पर लौटें", start: "नई गलती से शुरू करें", today: "आज पर लौटें", progress: "प्रगति देखें", all: "सभी गलतियां", backToLesson: "पाठ पर लौटें", yourAnswer: "आपका उत्तर", noAnswer: "रिकॉर्ड नहीं", correctAnswer: "सही उत्तर", explanation: "व्याख्या", goEnglish: "अंग्रेजी सीखें", goCpp: "C++ सीखें" },
  }),
  id: studyCopyFrom({
    directions: { english: "Inggris", cpp: "C++" },
    status: { completed: "Selesai", inProgress: "Berjalan" },
    dashboard: { eyebrow: "Lanjut belajar", title: "Langkah berikutnya", intro: (email) => `${email} bisa kembali ke Inggris C++ rencana hari ini dan ulasan salah dari satu tempat`, today: "Buka rencana hari ini", wrong: "Ulas jawaban salah", progress: "Lihat progres", completed: "Selesai", completion: "Progres", wrongItems: "Salah", continueEnglish: "Lanjut Inggris", continueCpp: "Lanjut C++", todayPlan: "Rencana hari ini", wrongBank: "Bank salah", tools: "Alat AI", recentTitle: "Pelajaran terakhir" },
    progress: { eyebrow: "Progres saya", title: "Progres belajar", intro: "Halaman ini menyimpan pelajaran yang dimulai dan selesai Jaga alur belajar latihan ulasan", completed: "Selesai", started: "Dimulai", completion: "Progres", updated: "Diperbarui", empty: "Belum ada catatan belajar", startEnglish: "Mulai Inggris", startCpp: "Mulai C++" },
    wrong: { eyebrow: "Ulas kesalahan", title: "Pusat ulasan", intro: "Jawaban salah menjadi rencana belajar berikutnya Ingat dulu baca penjelasan lalu kembali ke pelajaran", start: "Mulai dari salah terbaru", today: "Kembali ke hari ini", progress: "Lihat progres", all: "Semua kesalahan", backToLesson: "Kembali ke pelajaran", yourAnswer: "Jawabanmu", noAnswer: "Belum tercatat", correctAnswer: "Jawaban benar", explanation: "Penjelasan", goEnglish: "Belajar Inggris", goCpp: "Belajar C++" },
  }),
  vi: studyCopyFrom({
    directions: { english: "Tiếng Anh", cpp: "C++" },
    status: { completed: "Đã xong", inProgress: "Đang học" },
    dashboard: { eyebrow: "Học tiếp", title: "Bước học tiếp theo", intro: (email) => `${email} có thể quay lại tiếng Anh C++ kế hoạch hôm nay và ôn câu sai ở một nơi`, today: "Mở kế hoạch hôm nay", wrong: "Ôn câu sai", progress: "Xem tiến độ", completed: "Đã xong", completion: "Tiến độ", wrongItems: "Câu sai", continueEnglish: "Học tiếp tiếng Anh", continueCpp: "Học tiếp C++", todayPlan: "Kế hoạch hôm nay", wrongBank: "Sổ câu sai", tools: "Công cụ AI", recentTitle: "Bài học gần đây" },
    progress: { eyebrow: "Tiến độ của tôi", title: "Tiến độ học", intro: "Trang này ghi lại bài đã bắt đầu và hoàn thành Giữ vòng học luyện tập ôn lại", completed: "Đã xong", started: "Đã bắt đầu", completion: "Tiến độ", updated: "Cập nhật", empty: "Chưa có lịch sử học", startEnglish: "Bắt đầu tiếng Anh", startCpp: "Bắt đầu C++" },
    wrong: { eyebrow: "Ôn câu sai", title: "Trung tâm ôn tập", intro: "Câu sai là kế hoạch học tiếp theo Hãy nhớ lại trước rồi đọc giải thích và quay lại bài học", start: "Bắt đầu từ câu sai mới nhất", today: "Quay lại hôm nay", progress: "Xem tiến độ", all: "Tất cả câu sai", backToLesson: "Quay lại bài học", yourAnswer: "Câu trả lời của bạn", noAnswer: "Chưa ghi", correctAnswer: "Đáp án đúng", explanation: "Giải thích", goEnglish: "Học tiếng Anh", goCpp: "Học C++" },
  }),
  th: studyCopyFrom({
    directions: { english: "อังกฤษ", cpp: "C++" },
    status: { completed: "เสร็จแล้ว", inProgress: "กำลังเรียน" },
    dashboard: { eyebrow: "เรียนต่อ", title: "ขั้นตอนถัดไป", intro: (email) => `${email} กลับไปเรียนอังกฤษ C++ แผนวันนี้และทบทวนข้อผิดได้จากที่เดียว`, today: "เปิดแผนวันนี้", wrong: "ทบทวนข้อผิด", progress: "ดูความคืบหน้า", completed: "เสร็จแล้ว", completion: "ความคืบหน้า", wrongItems: "ข้อผิด", continueEnglish: "เรียนอังกฤษต่อ", continueCpp: "เรียน C++ ต่อ", todayPlan: "แผนวันนี้", wrongBank: "คลังข้อผิด", tools: "เครื่องมือ AI" },
    progress: { eyebrow: "ความคืบหน้าของฉัน", title: "ความคืบหน้าการเรียน", intro: "หน้านี้บันทึกบทเรียนที่เริ่มและทำเสร็จแล้ว รักษาวงจรเรียน ฝึก ทบทวน", completed: "เสร็จแล้ว", started: "เริ่มแล้ว", completion: "ความคืบหน้า", updated: "อัปเดต", empty: "ยังไม่มีบันทึกการเรียน", startEnglish: "เริ่มอังกฤษ", startCpp: "เริ่ม C++" },
    wrong: { eyebrow: "ทบทวนข้อผิด", title: "ศูนย์ทบทวน", intro: "คำตอบที่ผิดคือแผนเรียนถัดไป ลองจำก่อน อ่านคำอธิบาย แล้วกลับไปบทเรียน", start: "เริ่มจากข้อผิดล่าสุด", today: "กลับไปวันนี้", progress: "ดูความคืบหน้า", all: "ข้อผิดทั้งหมด", backToLesson: "กลับไปบทเรียน", yourAnswer: "คำตอบของคุณ", noAnswer: "ยังไม่บันทึก", correctAnswer: "คำตอบที่ถูก", explanation: "คำอธิบาย", goEnglish: "เรียนอังกฤษ", goCpp: "เรียน C++" },
  }),
  tr: studyCopyFrom({
    directions: { english: "Ingilizce", cpp: "C++" },
    status: { completed: "Tamamlandi", inProgress: "Devam ediyor" },
    dashboard: { eyebrow: "Ogrenmeye devam", title: "Sonraki adim", intro: (email) => `${email} Ingilizce C++ bugunun plani ve hata tekrarina tek yerden donebilir`, today: "Bugunun planini ac", wrong: "Hatalari tekrar et", progress: "Ilerlemeyi gor", completed: "Tamamlandi", completion: "Ilerleme", wrongItems: "Hatalar", continueEnglish: "Ingilizce devam", continueCpp: "C++ devam", todayPlan: "Bugunun plani", wrongBank: "Hata defteri", tools: "AI araclari" },
    progress: { eyebrow: "Ilerlemem", title: "Ogrenme ilerlemesi", intro: "Bu sayfa baslanan ve tamamlanan dersleri tutar Ogren alistir tekrar et dongusunu koru", completed: "Tamamlandi", started: "Basladi", completion: "Ilerleme", updated: "Guncellendi", empty: "Henuz ogrenme kaydi yok", startEnglish: "Ingilizceye basla", startCpp: "C++ basla" },
    wrong: { eyebrow: "Hata tekrari", title: "Tekrar merkezi", intro: "Yanlis cevaplar sonraki calisma planidir Once hatirla sonra aciklamayi oku ve derse don", start: "Son hatadan basla", today: "Bugune don", progress: "Ilerlemeyi gor", all: "Tum hatalar", backToLesson: "Derse don", yourAnswer: "Cevabin", noAnswer: "Kayit yok", correctAnswer: "Dogru cevap", explanation: "Aciklama", goEnglish: "Ingilizce calis", goCpp: "C++ calis" },
  }),
  it: studyCopyFrom({
    directions: { english: "Inglese", cpp: "C++" },
    status: { completed: "Completato", inProgress: "In corso" },
    dashboard: { eyebrow: "Continua", title: "Prossimo passo", intro: (email) => `${email} puo riprendere Inglese C++ piano di oggi e ripasso errori da un solo punto`, today: "Apri piano di oggi", wrong: "Ripassa errori", progress: "Vedi progresso", completed: "Completato", completion: "Progresso", wrongItems: "Errori", continueEnglish: "Continua Inglese", continueCpp: "Continua C++", todayPlan: "Piano di oggi", wrongBank: "Errori", tools: "Strumenti IA" },
    progress: { eyebrow: "Il mio progresso", title: "Progresso di studio", intro: "Questa pagina salva le lezioni iniziate e completate Mantieni il ciclo studia pratica ripassa", completed: "Completate", started: "Avviate", completion: "Progresso", updated: "Aggiornato", empty: "Nessun registro ancora", startEnglish: "Inizia Inglese", startCpp: "Inizia C++" },
    wrong: { eyebrow: "Ripasso errori", title: "Centro ripasso", intro: "Gli errori diventano il prossimo piano di studio Ricorda prima leggi la spiegazione e torna alla lezione", start: "Inizia dall'ultimo errore", today: "Torna a oggi", progress: "Vedi progresso", all: "Tutti gli errori", backToLesson: "Torna alla lezione", yourAnswer: "La tua risposta", noAnswer: "Non registrata", correctAnswer: "Risposta corretta", explanation: "Spiegazione", goEnglish: "Studia Inglese", goCpp: "Studia C++" },
  }),
  nl: studyCopyFrom({
    directions: { english: "Engels", cpp: "C++" },
    status: { completed: "Voltooid", inProgress: "Bezig" },
    dashboard: { eyebrow: "Verder leren", title: "Volgende stap", intro: (email) => `${email} kan Engels C++ het dagplan en foutenherhaling vanaf een plek hervatten`, today: "Open plan van vandaag", wrong: "Fouten herhalen", progress: "Bekijk voortgang", completed: "Voltooid", completion: "Voortgang", wrongItems: "Fouten", continueEnglish: "Verder met Engels", continueCpp: "Verder met C++", todayPlan: "Plan vandaag", wrongBank: "Foutenbank", tools: "AI tools" },
    progress: { eyebrow: "Mijn voortgang", title: "Leer voortgang", intro: "Deze pagina bewaart gestarte en voltooide lessen Houd de cyclus leren oefenen herhalen vast", completed: "Voltooid", started: "Gestart", completion: "Voortgang", updated: "Bijgewerkt", empty: "Nog geen leerrecord", startEnglish: "Start Engels", startCpp: "Start C++" },
    wrong: { eyebrow: "Fouten herhalen", title: "Herhaalcentrum", intro: "Fouten zijn het volgende leerplan Herinner eerst lees de uitleg en ga terug naar de les", start: "Start met laatste fout", today: "Terug naar vandaag", progress: "Bekijk voortgang", all: "Alle fouten", backToLesson: "Terug naar les", yourAnswer: "Jouw antwoord", noAnswer: "Niet opgeslagen", correctAnswer: "Juiste antwoord", explanation: "Uitleg", goEnglish: "Leer Engels", goCpp: "Leer C++" },
  }),
  pl: studyCopyFrom({
    directions: { english: "Angielski", cpp: "C++" },
    status: { completed: "Ukonczone", inProgress: "W trakcie" },
    dashboard: { eyebrow: "Kontynuuj nauke", title: "Nastepny krok", intro: (email) => `${email} moze wrocic do angielskiego C++ planu dnia i powtorki bledow z jednego miejsca`, today: "Otworz plan dnia", wrong: "Powtorz bledy", progress: "Zobacz postep", completed: "Ukonczone", completion: "Postep", wrongItems: "Bledy", continueEnglish: "Kontynuuj angielski", continueCpp: "Kontynuuj C++", todayPlan: "Plan dnia", wrongBank: "Bank bledow", tools: "Narzędzia AI" },
    progress: { eyebrow: "Moj postep", title: "Postep nauki", intro: "Ta strona zapisuje rozpoczete i ukonczone lekcje Utrzymaj cykl nauka praktyka powtorka", completed: "Ukonczone", started: "Rozpoczete", completion: "Postep", updated: "Aktualizacja", empty: "Brak historii nauki", startEnglish: "Zacznij angielski", startCpp: "Zacznij C++" },
    wrong: { eyebrow: "Powtorka bledow", title: "Centrum powtorek", intro: "Bledy sa kolejnym planem nauki Najpierw przypomnij odpowiedz potem przeczytaj wyjasnienie i wroc do lekcji", start: "Zacznij od ostatniego bledu", today: "Wroc do dzisiaj", progress: "Zobacz postep", all: "Wszystkie bledy", backToLesson: "Wroc do lekcji", yourAnswer: "Twoja odpowiedz", noAnswer: "Brak zapisu", correctAnswer: "Poprawna odpowiedz", explanation: "Wyjasnienie", goEnglish: "Ucz sie angielskiego", goCpp: "Ucz sie C++" },
  }),
};

export function getStudyPageCopy(language: InterfaceLanguage) {
  return studyCopy[language];
}

export function formatStudyDate(date: Date, language: InterfaceLanguage) {
  return date.toLocaleString(languageHtmlLang(language));
}

export const learnPageCopy: Record<InterfaceLanguage, LearnPageCopy> = {
  en: {
    path: "Learning Path",
    open: "Open",
    completed: "Completed",
    start: "Start",
    progress: "Progress",
    wrong: "Wrong Bank",
    backToPath: (direction) => `Back to ${direction} path`,
    estimated: (minutes) => `${minutes} min`,
    exampleCount: (count) => `${count} examples`,
    exerciseCount: (count) => `${count} exercises`,
    notCompleted: "Not completed",
    nextLesson: (title) => `Next: ${title}`,
    explanation: "Explanation",
    examples: "Examples",
    noExamples: "No examples yet.",
    practice: "Practice and quiz",
    noPractice: "No practice yet.",
    previous: "Previous lesson",
    next: "Next lesson",
    firstLesson: "This is the first lesson in this course.",
    courseDoneEyebrow: "After this course",
    reviewWrong: "Review wrong bank",
    reviewWrongBody: "When there is no next lesson, return to the wrong bank and redo the weak points.",
    markStatus: "Current status",
    saveProgress: "Save progress",
    markComplete: "Mark completed",
    saved: "Progress saved",
    loginFirst: "Please login first",
  },
  zh: {
    path: "学习路径",
    open: "打开",
    completed: "已完成",
    start: "开始",
    progress: "进度",
    wrong: "错题本",
    backToPath: (direction) => `返回${direction}路径`,
    estimated: (minutes) => `预计 ${minutes} 分钟`,
    exampleCount: (count) => `${count} 个例题`,
    exerciseCount: (count) => `${count} 道练习`,
    notCompleted: "未完成",
    nextLesson: (title) => `下一节 ${title}`,
    explanation: "讲解",
    examples: "例题",
    noExamples: "这个知识点暂时还没有例题",
    practice: "练习与测验",
    noPractice: "这个知识点暂时还没有练习",
    previous: "上一节",
    next: "下一节",
    firstLesson: "这是本课程第一节",
    courseDoneEyebrow: "课程完成后",
    reviewWrong: "去错题本复盘",
    reviewWrongBody: "没有下一节时 优先回到错题本 把这一路的问题重新做一遍",
    markStatus: "当前状态",
    saveProgress: "保存进度",
    markComplete: "标记完成",
    saved: "进度已保存",
    loginFirst: "请先登录",
  },
  ja: {
    path: "学習パス",
    open: "開く",
    completed: "完了",
    start: "開始",
    progress: "進捗",
    wrong: "復習ノート",
    backToPath: (direction) => `${direction} パスへ戻る`,
    estimated: (minutes) => `目安 ${minutes} 分`,
    exampleCount: (count) => `例 ${count} 件`,
    exerciseCount: (count) => `練習 ${count} 問`,
    notCompleted: "未完了",
    nextLesson: (title) => `次 ${title}`,
    explanation: "解説",
    examples: "例題",
    noExamples: "例題はまだありません",
    practice: "練習とクイズ",
    noPractice: "練習はまだありません",
    previous: "前のレッスン",
    next: "次のレッスン",
    firstLesson: "このコースの最初のレッスンです",
    courseDoneEyebrow: "コース完了後",
    reviewWrong: "復習ノートへ",
    reviewWrongBody: "次のレッスンがないときは復習ノートに戻り 苦手な問題を解き直しましょう",
    markStatus: "現在の状態",
    saveProgress: "進捗を保存",
    markComplete: "完了にする",
    saved: "進捗を保存しました",
    loginFirst: "ログインしてください",
  },
  ko: {
    path: "학습 경로",
    open: "열기",
    completed: "완료",
    start: "시작",
    progress: "진도",
    wrong: "오답 노트",
    backToPath: (direction) => `${direction} 경로로 돌아가기`,
    estimated: (minutes) => `예상 ${minutes}분`,
    exampleCount: (count) => `예제 ${count}개`,
    exerciseCount: (count) => `연습 ${count}개`,
    notCompleted: "미완료",
    nextLesson: (title) => `다음 ${title}`,
    explanation: "설명",
    examples: "예제",
    noExamples: "아직 예제가 없습니다",
    practice: "연습과 퀴즈",
    noPractice: "아직 연습이 없습니다",
    previous: "이전 레슨",
    next: "다음 레슨",
    firstLesson: "이 코스의 첫 레슨입니다",
    courseDoneEyebrow: "코스 완료 후",
    reviewWrong: "오답 노트 복습",
    reviewWrongBody: "다음 레슨이 없으면 오답 노트로 돌아가 약점을 다시 풀어보세요",
    markStatus: "현재 상태",
    saveProgress: "진도 저장",
    markComplete: "완료 표시",
    saved: "진도가 저장되었습니다",
    loginFirst: "먼저 로그인하세요",
  },
  es: {
    path: "Ruta de aprendizaje",
    open: "Abrir",
    completed: "Completado",
    start: "Empezar",
    progress: "Progreso",
    wrong: "Errores",
    backToPath: (direction) => `Volver a ${direction}`,
    estimated: (minutes) => `${minutes} min`,
    exampleCount: (count) => `${count} ejemplos`,
    exerciseCount: (count) => `${count} ejercicios`,
    notCompleted: "No completado",
    nextLesson: (title) => `Siguiente ${title}`,
    explanation: "Explicacion",
    examples: "Ejemplos",
    noExamples: "Aun no hay ejemplos",
    practice: "Practica y quiz",
    noPractice: "Aun no hay practica",
    previous: "Leccion anterior",
    next: "Siguiente leccion",
    firstLesson: "Esta es la primera leccion del curso",
    courseDoneEyebrow: "Al terminar el curso",
    reviewWrong: "Revisar errores",
    reviewWrongBody: "Cuando no haya siguiente leccion vuelve a errores y rehace los puntos debiles",
    markStatus: "Estado actual",
    saveProgress: "Guardar progreso",
    markComplete: "Marcar completado",
    saved: "Progreso guardado",
    loginFirst: "Inicia sesion primero",
  },
  fr: {
    path: "Parcours",
    open: "Ouvrir",
    completed: "Termine",
    start: "Demarrer",
    progress: "Progression",
    wrong: "Erreurs",
    backToPath: (direction) => `Retour au parcours ${direction}`,
    estimated: (minutes) => `${minutes} min`,
    exampleCount: (count) => `${count} exemples`,
    exerciseCount: (count) => `${count} exercices`,
    notCompleted: "Non termine",
    nextLesson: (title) => `Suivant ${title}`,
    explanation: "Explication",
    examples: "Exemples",
    noExamples: "Pas encore d'exemples",
    practice: "Pratique et quiz",
    noPractice: "Pas encore d'exercice",
    previous: "Lecon precedente",
    next: "Lecon suivante",
    firstLesson: "C'est la premiere lecon du cours",
    courseDoneEyebrow: "Apres le cours",
    reviewWrong: "Reviser les erreurs",
    reviewWrongBody: "S'il n'y a pas de lecon suivante retournez aux erreurs et refaites les points faibles",
    markStatus: "Etat actuel",
    saveProgress: "Sauver la progression",
    markComplete: "Marquer termine",
    saved: "Progression sauvegardee",
    loginFirst: "Connectez vous d'abord",
  },
  de: {
    path: "Lernpfad",
    open: "Oeffnen",
    completed: "Abgeschlossen",
    start: "Start",
    progress: "Fortschritt",
    wrong: "Fehlerbank",
    backToPath: (direction) => `Zurueck zu ${direction}`,
    estimated: (minutes) => `${minutes} Min`,
    exampleCount: (count) => `${count} Beispiele`,
    exerciseCount: (count) => `${count} Uebungen`,
    notCompleted: "Nicht abgeschlossen",
    nextLesson: (title) => `Weiter ${title}`,
    explanation: "Erklaerung",
    examples: "Beispiele",
    noExamples: "Noch keine Beispiele",
    practice: "Uebung und Quiz",
    noPractice: "Noch keine Uebung",
    previous: "Vorige Lektion",
    next: "Naechste Lektion",
    firstLesson: "Dies ist die erste Lektion dieses Kurses",
    courseDoneEyebrow: "Nach dem Kurs",
    reviewWrong: "Fehlerbank wiederholen",
    reviewWrongBody: "Wenn es keine naechste Lektion gibt zur Fehlerbank zurueckkehren und Schwachstellen wiederholen",
    markStatus: "Aktueller Status",
    saveProgress: "Fortschritt speichern",
    markComplete: "Als abgeschlossen markieren",
    saved: "Fortschritt gespeichert",
    loginFirst: "Bitte zuerst einloggen",
  },
  pt: {
    path: "Trilha de aprendizagem",
    open: "Abrir",
    completed: "Concluido",
    start: "Comecar",
    progress: "Progresso",
    wrong: "Banco de erros",
    backToPath: (direction) => `Voltar para ${direction}`,
    estimated: (minutes) => `${minutes} min`,
    exampleCount: (count) => `${count} exemplos`,
    exerciseCount: (count) => `${count} exercicios`,
    notCompleted: "Nao concluido",
    nextLesson: (title) => `Proximo ${title}`,
    explanation: "Explicacao",
    examples: "Exemplos",
    noExamples: "Ainda sem exemplos",
    practice: "Pratica e quiz",
    noPractice: "Ainda sem pratica",
    previous: "Licao anterior",
    next: "Proxima licao",
    firstLesson: "Esta e a primeira licao deste curso",
    courseDoneEyebrow: "Depois do curso",
    reviewWrong: "Revisar erros",
    reviewWrongBody: "Quando nao houver proxima licao volte ao banco de erros e refaca os pontos fracos",
    markStatus: "Status atual",
    saveProgress: "Salvar progresso",
    markComplete: "Marcar concluido",
    saved: "Progresso salvo",
    loginFirst: "Entre primeiro",
  },
  ru: {
    path: "Учебный путь",
    open: "Открыть",
    completed: "Готово",
    start: "Начать",
    progress: "Прогресс",
    wrong: "Ошибки",
    backToPath: (direction) => `Назад к ${direction}`,
    estimated: (minutes) => `${minutes} мин`,
    exampleCount: (count) => `${count} примеров`,
    exerciseCount: (count) => `${count} заданий`,
    notCompleted: "Не завершено",
    nextLesson: (title) => `Далее ${title}`,
    explanation: "Объяснение",
    examples: "Примеры",
    noExamples: "Примеров пока нет",
    practice: "Практика и тест",
    noPractice: "Заданий пока нет",
    previous: "Предыдущий урок",
    next: "Следующий урок",
    firstLesson: "Это первый урок курса",
    courseDoneEyebrow: "После курса",
    reviewWrong: "Повторить ошибки",
    reviewWrongBody: "Если следующего урока нет вернитесь к ошибкам и повторите слабые места",
    markStatus: "Текущий статус",
    saveProgress: "Сохранить прогресс",
    markComplete: "Отметить готово",
    saved: "Прогресс сохранен",
    loginFirst: "Сначала войдите",
  },
  ar: {
    path: "مسار التعلم",
    open: "فتح",
    completed: "مكتمل",
    start: "ابدأ",
    progress: "التقدم",
    wrong: "دفتر الأخطاء",
    backToPath: (direction) => `العودة إلى مسار ${direction}`,
    estimated: (minutes) => `${minutes} دقيقة`,
    exampleCount: (count) => `${count} أمثلة`,
    exerciseCount: (count) => `${count} تدريبات`,
    notCompleted: "غير مكتمل",
    nextLesson: (title) => `التالي ${title}`,
    explanation: "الشرح",
    examples: "الأمثلة",
    noExamples: "لا توجد أمثلة بعد",
    practice: "تدريب واختبار",
    noPractice: "لا يوجد تدريب بعد",
    previous: "الدرس السابق",
    next: "الدرس التالي",
    firstLesson: "هذا أول درس في هذه الدورة",
    courseDoneEyebrow: "بعد الدورة",
    reviewWrong: "راجع دفتر الأخطاء",
    reviewWrongBody: "عند عدم وجود درس تال ارجع إلى دفتر الأخطاء وأعد حل نقاط الضعف",
    markStatus: "الحالة الحالية",
    saveProgress: "حفظ التقدم",
    markComplete: "وضع علامة مكتمل",
    saved: "تم حفظ التقدم",
    loginFirst: "سجل الدخول أولا",
  },
  hi: {
    path: "सीखने का मार्ग",
    open: "खोलें",
    completed: "पूरा",
    start: "शुरू",
    progress: "प्रगति",
    wrong: "गलती बैंक",
    backToPath: (direction) => `${direction} मार्ग पर लौटें`,
    estimated: (minutes) => `${minutes} मिनट`,
    exampleCount: (count) => `${count} उदाहरण`,
    exerciseCount: (count) => `${count} अभ्यास`,
    notCompleted: "पूरा नहीं",
    nextLesson: (title) => `अगला ${title}`,
    explanation: "व्याख्या",
    examples: "उदाहरण",
    noExamples: "अभी उदाहरण नहीं",
    practice: "अभ्यास और क्विज",
    noPractice: "अभी अभ्यास नहीं",
    previous: "पिछला पाठ",
    next: "अगला पाठ",
    firstLesson: "यह इस कोर्स का पहला पाठ है",
    courseDoneEyebrow: "कोर्स के बाद",
    reviewWrong: "गलती बैंक दोहराएं",
    reviewWrongBody: "अगला पाठ न हो तो गलती बैंक में लौटकर कमजोर हिस्से दोहराएं",
    markStatus: "वर्तमान स्थिति",
    saveProgress: "प्रगति सेव करें",
    markComplete: "पूरा मार्क करें",
    saved: "प्रगति सेव हुई",
    loginFirst: "पहले लॉग इन करें",
  },
  id: {
    path: "Jalur belajar",
    open: "Buka",
    completed: "Selesai",
    start: "Mulai",
    progress: "Progres",
    wrong: "Bank salah",
    backToPath: (direction) => `Kembali ke ${direction}`,
    estimated: (minutes) => `${minutes} menit`,
    exampleCount: (count) => `${count} contoh`,
    exerciseCount: (count) => `${count} latihan`,
    notCompleted: "Belum selesai",
    nextLesson: (title) => `Berikutnya ${title}`,
    explanation: "Penjelasan",
    examples: "Contoh",
    noExamples: "Belum ada contoh",
    practice: "Latihan dan kuis",
    noPractice: "Belum ada latihan",
    previous: "Pelajaran sebelumnya",
    next: "Pelajaran berikutnya",
    firstLesson: "Ini pelajaran pertama kursus ini",
    courseDoneEyebrow: "Setelah kursus",
    reviewWrong: "Ulas bank salah",
    reviewWrongBody: "Jika tidak ada pelajaran berikutnya kembali ke bank salah dan ulangi titik lemah",
    markStatus: "Status saat ini",
    saveProgress: "Simpan progres",
    markComplete: "Tandai selesai",
    saved: "Progres tersimpan",
    loginFirst: "Login dulu",
  },
  vi: {
    path: "Lộ trình học",
    open: "Mở",
    completed: "Đã xong",
    start: "Bắt đầu",
    progress: "Tiến độ",
    wrong: "Sổ câu sai",
    backToPath: (direction) => `Quay lại ${direction}`,
    estimated: (minutes) => `${minutes} phút`,
    exampleCount: (count) => `${count} ví dụ`,
    exerciseCount: (count) => `${count} bài tập`,
    notCompleted: "Chưa xong",
    nextLesson: (title) => `Tiếp ${title}`,
    explanation: "Giải thích",
    examples: "Ví dụ",
    noExamples: "Chưa có ví dụ",
    practice: "Luyện tập và quiz",
    noPractice: "Chưa có bài tập",
    previous: "Bài trước",
    next: "Bài tiếp",
    firstLesson: "Đây là bài đầu tiên của khóa",
    courseDoneEyebrow: "Sau khóa học",
    reviewWrong: "Ôn sổ câu sai",
    reviewWrongBody: "Khi không còn bài tiếp hãy quay lại sổ câu sai và làm lại điểm yếu",
    markStatus: "Trạng thái hiện tại",
    saveProgress: "Lưu tiến độ",
    markComplete: "Đánh dấu xong",
    saved: "Đã lưu tiến độ",
    loginFirst: "Hãy đăng nhập trước",
  },
  th: {
    path: "เส้นทางเรียน",
    open: "เปิด",
    completed: "เสร็จแล้ว",
    start: "เริ่ม",
    progress: "ความคืบหน้า",
    wrong: "คลังข้อผิด",
    backToPath: (direction) => `กลับไป ${direction}`,
    estimated: (minutes) => `${minutes} นาที`,
    exampleCount: (count) => `${count} ตัวอย่าง`,
    exerciseCount: (count) => `${count} แบบฝึก`,
    notCompleted: "ยังไม่เสร็จ",
    nextLesson: (title) => `ถัดไป ${title}`,
    explanation: "คำอธิบาย",
    examples: "ตัวอย่าง",
    noExamples: "ยังไม่มีตัวอย่าง",
    practice: "แบบฝึกและควิซ",
    noPractice: "ยังไม่มีแบบฝึก",
    previous: "บทก่อนหน้า",
    next: "บทถัดไป",
    firstLesson: "นี่คือบทแรกของคอร์สนี้",
    courseDoneEyebrow: "หลังจบคอร์ส",
    reviewWrong: "ทบทวนคลังข้อผิด",
    reviewWrongBody: "ถ้าไม่มีบทถัดไปให้กลับไปคลังข้อผิดและทำจุดอ่อนอีกครั้ง",
    markStatus: "สถานะปัจจุบัน",
    saveProgress: "บันทึกความคืบหน้า",
    markComplete: "ทำเครื่องหมายเสร็จ",
    saved: "บันทึกแล้ว",
    loginFirst: "เข้าสู่ระบบก่อน",
  },
  tr: {
    path: "Ogrenme yolu",
    open: "Ac",
    completed: "Tamamlandi",
    start: "Basla",
    progress: "Ilerleme",
    wrong: "Hata defteri",
    backToPath: (direction) => `${direction} yoluna don`,
    estimated: (minutes) => `${minutes} dk`,
    exampleCount: (count) => `${count} ornek`,
    exerciseCount: (count) => `${count} alistirma`,
    notCompleted: "Tamamlanmadi",
    nextLesson: (title) => `Sonraki ${title}`,
    explanation: "Aciklama",
    examples: "Ornekler",
    noExamples: "Henuz ornek yok",
    practice: "Alistirma ve quiz",
    noPractice: "Henuz alistirma yok",
    previous: "Onceki ders",
    next: "Sonraki ders",
    firstLesson: "Bu kursun ilk dersi",
    courseDoneEyebrow: "Kurstan sonra",
    reviewWrong: "Hata defterini tekrar et",
    reviewWrongBody: "Sonraki ders yoksa hata defterine don ve zayif noktalarini tekrar cozumle",
    markStatus: "Mevcut durum",
    saveProgress: "Ilerlemeyi kaydet",
    markComplete: "Tamamlandi isaretle",
    saved: "Ilerleme kaydedildi",
    loginFirst: "Once giris yap",
  },
  it: {
    path: "Percorso di studio",
    open: "Apri",
    completed: "Completato",
    start: "Inizia",
    progress: "Progresso",
    wrong: "Errori",
    backToPath: (direction) => `Torna a ${direction}`,
    estimated: (minutes) => `${minutes} min`,
    exampleCount: (count) => `${count} esempi`,
    exerciseCount: (count) => `${count} esercizi`,
    notCompleted: "Non completato",
    nextLesson: (title) => `Prossima ${title}`,
    explanation: "Spiegazione",
    examples: "Esempi",
    noExamples: "Ancora nessun esempio",
    practice: "Pratica e quiz",
    noPractice: "Ancora nessuna pratica",
    previous: "Lezione precedente",
    next: "Lezione successiva",
    firstLesson: "Questa e la prima lezione del corso",
    courseDoneEyebrow: "Dopo il corso",
    reviewWrong: "Ripassa errori",
    reviewWrongBody: "Quando non c'e una lezione successiva torna agli errori e rifai i punti deboli",
    markStatus: "Stato attuale",
    saveProgress: "Salva progresso",
    markComplete: "Segna completato",
    saved: "Progresso salvato",
    loginFirst: "Accedi prima",
  },
  nl: {
    path: "Leerpad",
    open: "Open",
    completed: "Voltooid",
    start: "Start",
    progress: "Voortgang",
    wrong: "Fouten",
    backToPath: (direction) => `Terug naar ${direction}`,
    estimated: (minutes) => `${minutes} min`,
    exampleCount: (count) => `${count} voorbeelden`,
    exerciseCount: (count) => `${count} oefeningen`,
    notCompleted: "Niet voltooid",
    nextLesson: (title) => `Volgende ${title}`,
    explanation: "Uitleg",
    examples: "Voorbeelden",
    noExamples: "Nog geen voorbeelden",
    practice: "Oefening en quiz",
    noPractice: "Nog geen oefening",
    previous: "Vorige les",
    next: "Volgende les",
    firstLesson: "Dit is de eerste les van deze cursus",
    courseDoneEyebrow: "Na deze cursus",
    reviewWrong: "Fouten herhalen",
    reviewWrongBody: "Als er geen volgende les is ga terug naar fouten en oefen zwakke punten opnieuw",
    markStatus: "Huidige status",
    saveProgress: "Voortgang opslaan",
    markComplete: "Markeer voltooid",
    saved: "Voortgang opgeslagen",
    loginFirst: "Log eerst in",
  },
  pl: {
    path: "Sciezka nauki",
    open: "Otworz",
    completed: "Ukonczone",
    start: "Start",
    progress: "Postep",
    wrong: "Bank bledow",
    backToPath: (direction) => `Wroc do ${direction}`,
    estimated: (minutes) => `${minutes} min`,
    exampleCount: (count) => `${count} przyklady`,
    exerciseCount: (count) => `${count} cwiczenia`,
    notCompleted: "Nieukonczone",
    nextLesson: (title) => `Dalej ${title}`,
    explanation: "Wyjasnienie",
    examples: "Przyklady",
    noExamples: "Brak przykladow",
    practice: "Cwiczenia i quiz",
    noPractice: "Brak cwiczen",
    previous: "Poprzednia lekcja",
    next: "Nastepna lekcja",
    firstLesson: "To pierwsza lekcja tego kursu",
    courseDoneEyebrow: "Po kursie",
    reviewWrong: "Powtorz bledy",
    reviewWrongBody: "Gdy nie ma nastepnej lekcji wroc do banku bledow i przerob slabe punkty",
    markStatus: "Obecny status",
    saveProgress: "Zapisz postep",
    markComplete: "Oznacz ukonczone",
    saved: "Postep zapisany",
    loginFirst: "Najpierw sie zaloguj",
  },
};

export function getLearnPageCopy(language: InterfaceLanguage) {
  return learnPageCopy[language];
}
