import type { InterfaceLanguage } from "@/lib/language";
import {
  getProgrammingLanguage,
  programmingBankPlan,
  type ProgrammingLanguageSlug,
  type ProgrammingQuestion,
} from "@/lib/programming-content";

type ResultState = {
  correct: boolean;
  message: string;
};

type KeyPreset = "typing" | "vim";

type TrackSegment = {
  id: "choice" | "fill" | "practical";
  label: string;
  shortLabel: string;
  start: number;
  end: number;
  count: number;
};

type LineageProfile = {
  family: string;
  roots: string[];
  relatives: ProgrammingLanguageSlug[];
  next: ProgrammingLanguageSlug[];
  useCase: string;
};

const typeLabel: Record<InterfaceLanguage, Record<ProgrammingQuestion["type"], string>> = {
  en: {
    MULTIPLE_CHOICE: "Choice",
    FILL_BLANK: "Fill blank",
    PRACTICAL: "Practical",
  },
  zh: {
    MULTIPLE_CHOICE: "选择",
    FILL_BLANK: "填空",
    PRACTICAL: "实操",
  },
  ja: {
    MULTIPLE_CHOICE: "選択",
    FILL_BLANK: "穴埋め",
    PRACTICAL: "実践",
  },
  ko: {
    MULTIPLE_CHOICE: "선택",
    FILL_BLANK: "빈칸",
    PRACTICAL: "실습",
  },
  es: {
    MULTIPLE_CHOICE: "opción",
    FILL_BLANK: "rellenar",
    PRACTICAL: "práctica",
  },
  fr: {
    MULTIPLE_CHOICE: "Choix",
    FILL_BLANK: "Texte manquant",
    PRACTICAL: "Pratique",
  },
  de: {
    MULTIPLE_CHOICE: "Auswahl",
    FILL_BLANK: "Luecke",
    PRACTICAL: "Praxis",
  },
  pt: {
    MULTIPLE_CHOICE: "Escolha",
    FILL_BLANK: "Lacuna",
    PRACTICAL: "Pratica",
  },
  ru: {
    MULTIPLE_CHOICE: "Выбор",
    FILL_BLANK: "Пропуск",
    PRACTICAL: "Практика",
  },
  ar: {
    MULTIPLE_CHOICE: "اختيار",
    FILL_BLANK: "فراغ",
    PRACTICAL: "عملي",
  },
  hi: {
    MULTIPLE_CHOICE: "विकल्प",
    FILL_BLANK: "रिक्त",
    PRACTICAL: "अभ्यास",
  },
  id: {
    MULTIPLE_CHOICE: "Pilihan",
    FILL_BLANK: "Isian",
    PRACTICAL: "Praktik",
  },
  vi: {
    MULTIPLE_CHOICE: "Lua chon",
    FILL_BLANK: "Dien cho trong",
    PRACTICAL: "Thuc hanh",
  },
  th: {
    MULTIPLE_CHOICE: "ตัวเลือก",
    FILL_BLANK: "เติมคำ",
    PRACTICAL: "ฝึกปฏิบัติ",
  },
  tr: {
    MULTIPLE_CHOICE: "Secim",
    FILL_BLANK: "Bosluk",
    PRACTICAL: "Pratik",
  },
  it: {
    MULTIPLE_CHOICE: "Scelta",
    FILL_BLANK: "Completa",
    PRACTICAL: "Pratica",
  },
  nl: {
    MULTIPLE_CHOICE: "Keuze",
    FILL_BLANK: "Invullen",
    PRACTICAL: "Praktijk",
  },
  pl: {
    MULTIPLE_CHOICE: "Wybor",
    FILL_BLANK: "Luka",
    PRACTICAL: "Praktyka",
  },
};

const zeroBaseSteps: Partial<Record<InterfaceLanguage, string[]>> & { en: string[]; zh: string[] } = {
  en: [
    "Read one rule",
    "Predict output",
    "Type from memory",
    "Run checklist",
    "Repeat with one change",
  ],
  zh: [
    "看一条规则",
    "先猜输出",
    "凭记忆敲",
    "跑检查器",
    "改一处重做",
  ],
  ja: [
    "規則を一つ読む",
    "出力を予測",
    "記憶で入力",
    "チェックを実行",
    "一つ変えて反復",
  ],
  ko: [
    "규칙 하나 읽기",
    "출력 예측",
    "기억으로 입력",
    "검사 실행",
    "하나 바꿔 반복",
  ],
  es: [
    "lee una regla",
    "predice la salida",
    "escribe de memoria",
    "ejecuta revisión",
    "repite con un cambio",
  ],
  fr: [
    "lire une regle",
    "prevoir la sortie",
    "taper de memoire",
    "lancer la verification",
    "recommencer avec un changement",
  ],
  de: [
    "eine Regel lesen",
    "Ausgabe vorhersagen",
    "aus dem Gedaechtnis tippen",
    "Pruefung ausfuehren",
    "mit einer Aenderung wiederholen",
  ],
  pt: [
    "ler uma regra",
    "prever a saida",
    "digitar de memoria",
    "rodar a verificacao",
    "repetir com uma mudanca",
  ],
  ru: [
    "прочитать одно правило",
    "предсказать вывод",
    "набрать по памяти",
    "запустить проверку",
    "повторить с одним изменением",
  ],
  ar: [
    "اقرأ قاعدة واحدة",
    "توقع الناتج",
    "اكتب من الذاكرة",
    "شغل الفحص",
    "كرر مع تغيير واحد",
  ],
  hi: [
    "एक नियम पढ़ें",
    "आउटपुट सोचें",
    "याद से टाइप करें",
    "जांच चलाएं",
    "एक बदलाव के साथ दोहराएं",
  ],
  id: [
    "baca satu aturan",
    "tebak keluaran",
    "ketik dari ingatan",
    "jalankan cek",
    "ulang dengan satu perubahan",
  ],
  vi: [
    "doc mot quy tac",
    "doan dau ra",
    "go bang tri nho",
    "chay kiem tra",
    "lap lai voi mot thay doi",
  ],
  th: [
    "อ่านกฎหนึ่งข้อ",
    "ทายผลลัพธ์",
    "พิมพ์จากความจำ",
    "รันการตรวจ",
    "ทำซ้ำโดยเปลี่ยนหนึ่งจุด",
  ],
  tr: [
    "bir kural oku",
    "ciktisini tahmin et",
    "hafizadan yaz",
    "kontrolu calistir",
    "bir degisiklikle tekrarla",
  ],
  it: [
    "leggi una regola",
    "prevedi l output",
    "scrivi a memoria",
    "esegui il controllo",
    "ripeti con una modifica",
  ],
  nl: [
    "lees een regel",
    "voorspel uitvoer",
    "typ uit geheugen",
    "draai controle",
    "herhaal met een wijziging",
  ],
  pl: [
    "przeczytaj jedna zasade",
    "przewidz wynik",
    "pisz z pamieci",
    "uruchom sprawdzanie",
    "powtorz z jedna zmiana",
  ],
};

type ProgrammingCopyType = {
  brand: string;
  languages: string;
  queue: string;
  expanding: string;
  zeroBase: string;
  session: string;
  correct: string;
  answered: string;
  workspace: string;
  nextUnsolved: string;
  reset: string;
  resetConfirm: (language: string) => string;
  statusSolved: string;
  statusReview: string;
  statusDraft: string;
  statusNew: string;
  question: string;
  questionShort: string;
  questionPalette: string;
  prev: string;
  next: string;
  submit: string;
  run: string;
  hint: string;
  answer: string;
  correctMessage: string;
  notYetMessage: string;
  wrongNote: string;
  codePlaceholder: string;
  fillPlaceholder: string;
  inspector: string;
  feedback: string;
  typingFirst: string;
  vimReview: string;
  runOutput: string;
  runEmpty: string;
  hints: string;
  hintEmpty: string;
  answerEmpty: string;
  shortcuts: string;
  shortcutItems: string[];
  vimShortcut: string;
  coachTitle: string;
  coachSubtitle: string;
  coachPlaceholder: string;
  coachPrompts: string[];
  reference: string;
  patternsFor: (fileName: string) => string;
  showOutput: string;
  hideOutput: string;
  output: string;
  tracks: {
    choice: { label: string; shortLabel: string };
    fill: { label: string; shortLabel: string };
    practical: { label: string; shortLabel: string };
  };
  roleFallback: (role: string) => string;
};

type ProgrammingRailSearchCopy = {
  label: string;
  placeholder: string;
  clear: string;
  noMatch: string;
  shortcut: string;
  count: (visible: number, total: number) => string;
};

const programmingRailSearchCopy: Record<InterfaceLanguage, ProgrammingRailSearchCopy> = {
  en: {
    label: "Find a language",
    placeholder: "Python JavaScript Rust SQL Bash",
    clear: "Clear",
    noMatch: "No matching language yet.",
    shortcut: "Enter opens the first match. Escape clears the search.",
    count: (visible, total) => `${visible} of ${total}`,
  },
  zh: {
    label: "搜索语言",
    placeholder: "Python 自动化 SQL 数据 Rust 安全",
    clear: "清空",
    noMatch: "暂时没有匹配的语言",
    shortcut: "Enter 打开第一个结果，Esc 清空搜索",
    count: (visible, total) => `${visible} / ${total}`,
  },
  ja: {
    label: "言語を探す",
    placeholder: "Python 自動化 SQL データ Rust 安全",
    clear: "クリア",
    noMatch: "一致する言語はまだありません。",
    shortcut: "Enter で最初の結果を開き、Esc でクリアします。",
    count: (visible, total) => `${visible} / ${total}`,
  },
  ko: {
    label: "언어 찾기",
    placeholder: "Python 자동화 SQL 데이터 Rust 안전",
    clear: "지우기",
    noMatch: "일치하는 언어가 아직 없습니다.",
    shortcut: "Enter 는 첫 결과를 열고 Esc 는 검색을 지웁니다.",
    count: (visible, total) => `${visible} / ${total}`,
  },
  es: {
    label: "Buscar lenguaje",
    placeholder: "Python automatizacion SQL datos Rust seguridad",
    clear: "Limpiar",
    noMatch: "No hay lenguajes coincidentes.",
    shortcut: "Enter abre el primer resultado. Escape limpia la busqueda.",
    count: (visible, total) => `${visible} de ${total}`,
  },
  fr: {
    label: "Trouver un langage",
    placeholder: "Python automatisation SQL donnees Rust securite",
    clear: "Effacer",
    noMatch: "Aucun langage correspondant.",
    shortcut: "Enter ouvre le premier resultat. Escape efface la recherche.",
    count: (visible, total) => `${visible} sur ${total}`,
  },
  de: {
    label: "Sprache suchen",
    placeholder: "Python automation SQL daten Rust sicherheit",
    clear: "Zuruecksetzen",
    noMatch: "Noch keine passende Sprache.",
    shortcut: "Enter oeffnet den ersten Treffer. Escape leert die Suche.",
    count: (visible, total) => `${visible} von ${total}`,
  },
  pt: {
    label: "Encontrar linguagem",
    placeholder: "Python automacao SQL dados Rust seguranca",
    clear: "Limpar",
    noMatch: "Nenhuma linguagem encontrada.",
    shortcut: "Enter abre o primeiro resultado. Escape limpa a busca.",
    count: (visible, total) => `${visible} de ${total}`,
  },
  ru: {
    label: "Найти язык",
    placeholder: "Python автоматизация SQL данные Rust безопасность",
    clear: "Сбросить",
    noMatch: "Подходящий язык пока не найден.",
    shortcut: "Enter открывает первый результат. Escape очищает поиск.",
    count: (visible, total) => `${visible} из ${total}`,
  },
  ar: {
    label: "ابحث عن لغة",
    placeholder: "Python أتمتة SQL بيانات Rust أمان",
    clear: "مسح",
    noMatch: "لا توجد لغة مطابقة بعد.",
    shortcut: "Enter يفتح أول نتيجة. Escape يمسح البحث.",
    count: (visible, total) => `${visible} من ${total}`,
  },
  hi: {
    label: "भाषा खोजें",
    placeholder: "Python automation SQL data Rust security",
    clear: "साफ करें",
    noMatch: "अभी कोई मेल खाती भाषा नहीं है।",
    shortcut: "Enter पहला परिणाम खोलता है. Escape search साफ करता है.",
    count: (visible, total) => `${visible} / ${total}`,
  },
  id: {
    label: "Cari bahasa",
    placeholder: "Python otomatisasi SQL data Rust aman",
    clear: "Bersihkan",
    noMatch: "Belum ada bahasa yang cocok.",
    shortcut: "Enter membuka hasil pertama. Escape membersihkan pencarian.",
    count: (visible, total) => `${visible} dari ${total}`,
  },
  vi: {
    label: "Tim ngon ngu",
    placeholder: "Python tu dong SQL du lieu Rust an toan",
    clear: "Xoa",
    noMatch: "Chua co ngon ngu phu hop.",
    shortcut: "Enter mo ket qua dau tien. Escape xoa tim kiem.",
    count: (visible, total) => `${visible} / ${total}`,
  },
  th: {
    label: "ค้นหาภาษา",
    placeholder: "Python automation SQL data Rust security",
    clear: "ล้าง",
    noMatch: "ยังไม่มีภาษาที่ตรงกัน",
    shortcut: "Enter เปิดผลลัพธ์แรก Escape ล้างการค้นหา",
    count: (visible, total) => `${visible} / ${total}`,
  },
  tr: {
    label: "Dil bul",
    placeholder: "Python otomasyon SQL veri Rust guvenlik",
    clear: "Temizle",
    noMatch: "Henuz eslesen dil yok.",
    shortcut: "Enter ilk sonucu acar. Escape aramayi temizler.",
    count: (visible, total) => `${visible} / ${total}`,
  },
  it: {
    label: "Trova linguaggio",
    placeholder: "Python automazione SQL dati Rust sicurezza",
    clear: "Pulisci",
    noMatch: "Nessun linguaggio corrispondente.",
    shortcut: "Enter apre il primo risultato. Escape pulisce la ricerca.",
    count: (visible, total) => `${visible} di ${total}`,
  },
  nl: {
    label: "Taal zoeken",
    placeholder: "Python automatisering SQL data Rust veiligheid",
    clear: "Wissen",
    noMatch: "Nog geen passende taal.",
    shortcut: "Enter opent het eerste resultaat. Escape wist de zoekopdracht.",
    count: (visible, total) => `${visible} van ${total}`,
  },
  pl: {
    label: "Znajdz jezyk",
    placeholder: "Python automatyzacja SQL dane Rust bezpieczenstwo",
    clear: "Wyczysc",
    noMatch: "Brak pasujacego jezyka.",
    shortcut: "Enter otwiera pierwszy wynik. Escape czysci wyszukiwanie.",
    count: (visible, total) => `${visible} z ${total}`,
  },
};

const baseProgrammingCopy: Record<"en" | "zh", ProgrammingCopyType> = {
  en: {
    brand: "Code Practice",
    languages: "Languages",
    queue: "Queue",
    expanding: "Expanding",
    zeroBase: "Zero base path",
    session: "Session",
    correct: "Correct",
    answered: "answered",
    workspace: "Workspace",
    nextUnsolved: "Next unsolved",
    reset: "Reset",
    resetConfirm: (language: string) => `Reset ${language} local practice state?`,
    statusSolved: "solved",
    statusReview: "review",
    statusDraft: "draft",
    statusNew: "new",
    question: "Question",
    questionShort: "Q",
    questionPalette: "Question palette",
    prev: "Prev",
    next: "Next",
    submit: "Submit",
    run: "Run",
    hint: "Hint",
    answer: "Answer",
    correctMessage: "Correct",
    notYetMessage: "Not yet. Check a hint or compare with the answer.",
    wrongNote: "Hints stay out of the way until you try once.",
    codePlaceholder: "Type your code here",
    fillPlaceholder: "Type the missing answer",
    inspector: "Inspector",
    feedback: "Feedback",
    typingFirst: "Typing first",
    vimReview: "Vim review",
    runOutput: "Run output",
    runEmpty: "Run checks the sample output or required parts.",
    hints: "Hints",
    hintEmpty: "Try once first. Then open a hint if you need one.",
    answerEmpty: "Use Answer when you want to compare your work with a clean version.",
    shortcuts: "Shortcuts",
    shortcutItems: ["Ctrl Enter submit", "Alt R run", "Alt H hint", "Alt A answer", "Alt arrows move", "1 2 3 4 choices"],
    vimShortcut: "J K move",
    coachTitle: "Programming companion",
    coachSubtitle: "One hint at a time. It reads the current question answer and language context.",
    coachPlaceholder: "Ask for a hint bug check explanation or next drill",
    coachPrompts: ["Give one hint", "Explain the concept", "Check my answer", "Make a tiny drill"],
    reference: "Reference",
    patternsFor: (fileName: string) => `Patterns for ${fileName}`,
    showOutput: "Show output",
    hideOutput: "Hide output",
    output: "Output",
    tracks: {
      choice: { label: "Multiple choice", shortLabel: "Choice" },
      fill: { label: "Fill blank", shortLabel: "Fill" },
      practical: { label: "Practical", shortLabel: "Build" },
    },
    roleFallback: (role: string) => role,
  },
  zh: {
    brand: "编程刷题",
    languages: "语言",
    queue: "题型队列",
    expanding: "持续扩充",
    zeroBase: "零基础路径",
    session: "本轮进度",
    correct: "正确",
    answered: "已做",
    workspace: "训练台",
    nextUnsolved: "下一道未做",
    reset: "重置",
    resetConfirm: (language: string) => `重置 ${language} 的本地练习记录吗`,
    statusSolved: "已掌握",
    statusReview: "待复盘",
    statusDraft: "已作答",
    statusNew: "新题",
    question: "题号",
    questionShort: "题",
    questionPalette: "题号面板",
    prev: "上一题",
    next: "下一题",
    submit: "提交",
    run: "运行",
    hint: "提示",
    answer: "看答案",
    correctMessage: "答对了",
    notYetMessage: "还差一点 先看一个提示 或直接对照答案",
    wrongNote: "提示会等你先尝试一次后再介入",
    codePlaceholder: "在这里写代码",
    fillPlaceholder: "填入缺失答案",
    inspector: "检查器",
    feedback: "反馈",
    typingFirst: "打字优先",
    vimReview: "Vim 复盘",
    runOutput: "运行反馈",
    runEmpty: "运行会检查样例输出或实操关键词",
    hints: "提示",
    hintEmpty: "先做一次 再一点点打开提示",
    answerEmpty: "想对照标准写法时再点看答案",
    shortcuts: "快捷键",
    shortcutItems: ["Ctrl Enter 提交", "Alt R 运行", "Alt H 提示", "Alt A 答案", "Alt 方向键切题", "1 2 3 4 选项"],
    vimShortcut: "J K 切题",
    coachTitle: "编程陪练",
    coachSubtitle: "只给当前题相关的提示 先帮你想清楚 不直接灌答案",
    coachPlaceholder: "让它给提示 查 bug 讲概念 或出一道小练习",
    coachPrompts: ["给一个提示", "讲清这个概念", "检查我的答案", "出一道小练习"],
    reference: "参考",
    patternsFor: (fileName: string) => `${fileName} 常用模式`,
    showOutput: "显示输出",
    hideOutput: "收起输出",
    output: "输出",
    tracks: {
      choice: { label: "选择题", shortLabel: "选择" },
      fill: { label: "填空题", shortLabel: "填空" },
      practical: { label: "实操题", shortLabel: "实操" },
    },
    roleFallback: (role: string) => role,
  },
};

function programmingCopyFromEnglish(overrides: Partial<ProgrammingCopyType>): ProgrammingCopyType {
  return {
    ...baseProgrammingCopy.en,
    ...overrides,
    tracks: {
      choice: overrides.tracks?.choice ?? baseProgrammingCopy.en.tracks.choice,
      fill: overrides.tracks?.fill ?? baseProgrammingCopy.en.tracks.fill,
      practical: overrides.tracks?.practical ?? baseProgrammingCopy.en.tracks.practical,
    },
  };
}

const programmingCopy: Record<InterfaceLanguage, ProgrammingCopyType> = {
  en: baseProgrammingCopy.en,
  zh: baseProgrammingCopy.zh,
  ja: {
    brand: "コード練習",
    languages: "言語",
    queue: "キュー",
    expanding: "拡張中",
    zeroBase: "ゼロベース",
    session: "セッション",
    correct: "正解",
    answered: "回答済み",
    workspace: "ワークスペース",
    nextUnsolved: "次の未解決",
    reset: "リセット",
    resetConfirm: (language: string) => `${language} の練習状態をリセットしますか？`,
    statusSolved: "解決済み",
    statusReview: "復習",
    statusDraft: "下書き",
    statusNew: "新規",
    question: "問題",
    questionShort: "問",
    questionPalette: "問題パレット",
    prev: "前へ",
    next: "次へ",
    submit: "提出",
    run: "実行",
    hint: "ヒント",
    answer: "答え",
    correctMessage: "正解",
    notYetMessage: "まだです。ヒントを確認するか答えと比較してください。",
    wrongNote: "ヒントは一度試した後に表示されます。",
    codePlaceholder: "ここにコードを入力",
    fillPlaceholder: "答えを入力",
    inspector: "インスペクター",
    feedback: "フィードバック",
    typingFirst: "タイピング優先",
    vimReview: "Vim 復習",
    runOutput: "実行結果",
    runEmpty: "実行はサンプル出力または必要な部分をチェックします。",
    hints: "ヒント",
    hintEmpty: "まず一度試してください。必要ならヒントを開きます。",
    answerEmpty: "答えは自分の作業と比較したいときに使います。",
    shortcuts: "ショートカット",
    shortcutItems: ["Ctrl Enter 提出", "Alt R 実行", "Alt H ヒント", "Alt A 答え", "Alt 矢印 移動", "1 2 3 4 選択"],
    vimShortcut: "J K 移動",
    coachTitle: "プログラミング コンパニオン",
    coachSubtitle: "一度に一つのヒント。現在の問題、答え、言語コンテキストを読みます。",
    coachPlaceholder: "ヒント、バグチェック、説明、または次のドリルを依頼",
    coachPrompts: ["ヒントを一つ", "概念を説明", "答えをチェック", "小さなドリルを作成"],
    reference: "参考",
    patternsFor: (fileName: string) => `${fileName} のパターン`,
    showOutput: "出力を表示",
    hideOutput: "出力を隠す",
    output: "出力",
    tracks: {
      choice: { label: "選択問題", shortLabel: "選択" },
      fill: { label: "穴埋め", shortLabel: "穴埋め" },
      practical: { label: "実践", shortLabel: "実践" },
    },
    roleFallback: (role: string) => role,
  },
  ko: {
    brand: "코드 연습",
    languages: "언어",
    queue: "큐",
    expanding: "확장 중",
    zeroBase: "제로 베이스",
    session: "세션",
    correct: "정답",
    answered: "답변함",
    workspace: "작업 공간",
    nextUnsolved: "다음 미해결",
    reset: "초기화",
    resetConfirm: (language: string) => `${language} 연습 상태를 초기화하시겠습니까?`,
    statusSolved: "해결됨",
    statusReview: "복습",
    statusDraft: "초안",
    statusNew: "새로운",
    question: "문제",
    questionShort: "문항",
    questionPalette: "문제 팔레트",
    prev: "이전",
    next: "다음",
    submit: "제출",
    run: "실행",
    hint: "힌트",
    answer: "답",
    correctMessage: "정답",
    notYetMessage: "아직 아닙니다. 힌트를 확인하거나 답과 비교하세요.",
    wrongNote: "힌트는 한 번 시도한 후에 표시됩니다.",
    codePlaceholder: "여기에 코드 입력",
    fillPlaceholder: "답 입력",
    inspector: "검사기",
    feedback: "피드백",
    typingFirst: "타이핑 우선",
    vimReview: "Vim 복습",
    runOutput: "실행 결과",
    runEmpty: "실행은 샘플 출력 또는 필요한 부분을 확인합니다.",
    hints: "힌트",
    hintEmpty: "먼저 한 번 시도하세요. 필요하면 힌트를 엽니다.",
    answerEmpty: "답은 자신의 작업과 비교하고 싶을 때 사용합니다.",
    shortcuts: "단축키",
    shortcutItems: ["Ctrl Enter 제출", "Alt R 실행", "Alt H 힌트", "Alt A 답", "Alt 화살표 이동", "1 2 3 4 선택"],
    vimShortcut: "J K 이동",
    coachTitle: "프로그래밍 동반자",
    coachSubtitle: "한 번에 하나의 힌트. 현재 문제, 답, 언어 컨텍스트를 읽습니다.",
    coachPlaceholder: "힌트, 버그 체크, 설명 또는 다음 드릴 요청",
    coachPrompts: ["힌트 하나", "개념 설명", "답 확인", "작은 드릴 만들기"],
    reference: "참고",
    patternsFor: (fileName: string) => `${fileName} 패턴`,
    showOutput: "출력 표시",
    hideOutput: "출력 숨기기",
    output: "출력",
    tracks: {
      choice: { label: "선택 문제", shortLabel: "선택" },
      fill: { label: "빈칸 채우기", shortLabel: "빈칸" },
      practical: { label: "실습", shortLabel: "실습" },
    },
    roleFallback: (role: string) => role,
  },
  es: {
    brand: "Práctica de código",
    languages: "Lenguajes",
    queue: "Cola",
    expanding: "en expansión",
    zeroBase: "desde cero",
    session: "sesión",
    correct: "correctas",
    answered: "respondidas",
    workspace: "espacio de trabajo",
    nextUnsolved: "siguiente sin resolver",
    reset: "reiniciar",
    resetConfirm: (language: string) => `¿Reiniciar el progreso de ${language}?`,
    statusSolved: "resuelto",
    statusReview: "repasar",
    statusDraft: "borrador",
    statusNew: "nuevo",
    question: "pregunta",
    questionShort: "P",
    questionPalette: "paleta de preguntas",
    prev: "anterior",
    next: "siguiente",
    submit: "enviar",
    run: "probar",
    hint: "pista",
    answer: "respuesta",
    correctMessage: "correcto",
    notYetMessage: "todavía no. Prueba una pista o compara con la respuesta.",
    wrongNote: "las pistas se abren después de intentarlo.",
    codePlaceholder: "escribe tu código aquí",
    fillPlaceholder: "escribe la respuesta",
    inspector: "inspector",
    feedback: "retroalimentación",
    typingFirst: "tecleo primero",
    vimReview: "repaso Vim",
    runOutput: "salida de prueba",
    runEmpty: "la prueba revisa la salida de ejemplo o las partes requeridas.",
    hints: "pistas",
    hintEmpty: "intenta una vez. Luego abre una pista si la necesitas.",
    answerEmpty: "usa la respuesta solo para comparar tu trabajo.",
    shortcuts: "atajos",
    shortcutItems: ["Ctrl Enter enviar", "Alt R probar", "Alt H pista", "Alt A respuesta", "Alt flecha mover", "1 2 3 4 elegir"],
    vimShortcut: "J K mover",
    coachTitle: "Compañero de programación",
    coachSubtitle: "Una pista a la vez. Lee la pregunta, tu respuesta y el contexto del lenguaje.",
    coachPlaceholder: "pide una pista, revisión de bug, explicación o siguiente ejercicio",
    coachPrompts: ["Dame una pista", "Explica el concepto", "Revisa mi respuesta", "Crea un mini ejercicio"],
    reference: "referencia",
    patternsFor: (fileName: string) => `patrones para ${fileName}`,
    showOutput: "mostrar salida",
    hideOutput: "ocultar salida",
    output: "salida",
    tracks: {
      choice: { label: "opción múltiple", shortLabel: "opción" },
      fill: { label: "rellenar hueco", shortLabel: "rellenar" },
      practical: { label: "práctica", shortLabel: "práctica" },
    },
    roleFallback: (role: string) => role,
  },
  fr: programmingCopyFromEnglish({
    brand: "Pratique de code",
    languages: "Langages",
    queue: "File",
    expanding: "en expansion",
    zeroBase: "parcours debutant",
    session: "session",
    correct: "correct",
    answered: "repondu",
    workspace: "atelier",
    nextUnsolved: "suivant non resolu",
    reset: "reinitialiser",
    resetConfirm: (language: string) => `Reinitialiser la progression locale de ${language} ?`,
    statusSolved: "resolu",
    statusReview: "a revoir",
    statusDraft: "brouillon",
    statusNew: "nouveau",
    question: "question",
    questionPalette: "palette de questions",
    prev: "precedent",
    next: "suivant",
    submit: "valider",
    run: "tester",
    hint: "indice",
    answer: "reponse",
    correctMessage: "correct",
    notYetMessage: "pas encore. Ouvre un indice ou compare avec la reponse.",
    wrongNote: "les indices restent caches jusqu a ton premier essai.",
    codePlaceholder: "ecris ton code ici",
    fillPlaceholder: "ecris la reponse manquante",
    inspector: "inspecteur",
    feedback: "retour",
    typingFirst: "frappe d abord",
    vimReview: "revision Vim",
    runOutput: "sortie du test",
    runEmpty: "le test verifie la sortie exemple ou les elements requis.",
    hints: "indices",
    hintEmpty: "essaie une fois. Puis ouvre un indice si besoin.",
    answerEmpty: "utilise la reponse seulement pour comparer ton travail.",
    shortcuts: "raccourcis",
    shortcutItems: ["Ctrl Enter valider", "Alt R tester", "Alt H indice", "Alt A reponse", "Alt fleches naviguer", "1 2 3 4 choix"],
    vimShortcut: "J K naviguer",
    coachTitle: "compagnon de programmation",
    coachSubtitle: "un indice a la fois. Il lit la question, ta reponse et le contexte du langage.",
    coachPlaceholder: "demande un indice, une verification de bug, une explication ou un exercice",
    coachPrompts: ["donne un indice", "explique le concept", "verifie ma reponse", "cree un mini exercice"],
    reference: "reference",
    patternsFor: (fileName: string) => `modeles pour ${fileName}`,
    showOutput: "voir la sortie",
    hideOutput: "cacher la sortie",
    output: "sortie",
    tracks: {
      choice: { label: "choix multiple", shortLabel: "choix" },
      fill: { label: "texte manquant", shortLabel: "trou" },
      practical: { label: "pratique", shortLabel: "code" },
    },
  }),
  de: programmingCopyFromEnglish({
    brand: "Code Praxis",
    languages: "Sprachen",
    queue: "Aufgaben",
    expanding: "wachsend",
    zeroBase: "Start bei null",
    session: "Sitzung",
    correct: "richtig",
    answered: "beantwortet",
    workspace: "Arbeitsbereich",
    nextUnsolved: "naechste offene",
    reset: "zuruecksetzen",
    resetConfirm: (language: string) => `Lokalen Uebungsstand fuer ${language} zuruecksetzen?`,
    statusSolved: "geloest",
    statusReview: "pruefen",
    statusDraft: "entwurf",
    statusNew: "neu",
    question: "frage",
    questionPalette: "fragenpalette",
    prev: "zurueck",
    next: "weiter",
    submit: "absenden",
    run: "testen",
    hint: "hinweis",
    answer: "antwort",
    correctMessage: "richtig",
    notYetMessage: "noch nicht. Nimm einen Hinweis oder vergleiche mit der Antwort.",
    wrongNote: "Hinweise erscheinen erst nach einem eigenen Versuch.",
    codePlaceholder: "schreibe deinen Code hier",
    fillPlaceholder: "fehlende Antwort eingeben",
    inspector: "pruefer",
    feedback: "feedback",
    typingFirst: "tippen zuerst",
    vimReview: "Vim review",
    runOutput: "testausgabe",
    runEmpty: "der Test prueft Beispielausgabe oder benoetigte Teile.",
    hints: "hinweise",
    hintEmpty: "versuche es einmal. Oeffne dann bei Bedarf einen Hinweis.",
    answerEmpty: "nutze die Antwort nur zum Vergleichen.",
    shortcuts: "tastenkombinationen",
    shortcutItems: ["Ctrl Enter absenden", "Alt R testen", "Alt H hinweis", "Alt A antwort", "Alt pfeile wechseln", "1 2 3 4 auswahl"],
    vimShortcut: "J K wechseln",
    coachTitle: "Programmier Begleiter",
    coachSubtitle: "ein Hinweis nach dem anderen. Er liest Frage, Antwort und Sprachkontext.",
    coachPlaceholder: "frage nach Hinweis, Bugcheck, Erklaerung oder Miniuebung",
    coachPrompts: ["gib einen Hinweis", "erklaere das Konzept", "pruefe meine Antwort", "erstelle eine Miniuebung"],
    reference: "referenz",
    patternsFor: (fileName: string) => `muster fuer ${fileName}`,
    showOutput: "ausgabe zeigen",
    hideOutput: "ausgabe verbergen",
    output: "ausgabe",
    tracks: {
      choice: { label: "multiple choice", shortLabel: "wahl" },
      fill: { label: "luecke fuellen", shortLabel: "luecke" },
      practical: { label: "praxis", shortLabel: "code" },
    },
  }),
  pt: programmingCopyFromEnglish({
    brand: "Pratica de codigo",
    languages: "Linguagens",
    queue: "Fila",
    expanding: "em expansao",
    zeroBase: "do zero",
    session: "sessao",
    correct: "correto",
    answered: "respondidas",
    workspace: "bancada",
    nextUnsolved: "proxima aberta",
    reset: "reiniciar",
    resetConfirm: (language: string) => `Reiniciar o treino local de ${language}?`,
    statusSolved: "resolvido",
    statusReview: "revisar",
    statusDraft: "rascunho",
    statusNew: "novo",
    question: "questao",
    questionPalette: "painel de questoes",
    prev: "anterior",
    next: "proxima",
    submit: "enviar",
    run: "testar",
    hint: "dica",
    answer: "resposta",
    correctMessage: "correto",
    notYetMessage: "ainda nao. Veja uma dica ou compare com a resposta.",
    wrongNote: "as dicas aparecem depois da primeira tentativa.",
    codePlaceholder: "digite seu codigo aqui",
    fillPlaceholder: "digite a resposta",
    inspector: "inspetor",
    feedback: "retorno",
    typingFirst: "digitar primeiro",
    vimReview: "revisao Vim",
    runOutput: "saida do teste",
    runEmpty: "o teste verifica a saida exemplo ou as partes exigidas.",
    hints: "dicas",
    hintEmpty: "tente uma vez. Depois abra uma dica se precisar.",
    answerEmpty: "use a resposta apenas para comparar seu trabalho.",
    shortcuts: "atalhos",
    shortcutItems: ["Ctrl Enter enviar", "Alt R testar", "Alt H dica", "Alt A resposta", "Alt setas mover", "1 2 3 4 opcoes"],
    vimShortcut: "J K mover",
    coachTitle: "companheiro de programacao",
    coachSubtitle: "uma dica por vez. Ele le a questao, sua resposta e o contexto.",
    coachPlaceholder: "peca dica, revisao de bug, explicacao ou novo exercicio",
    coachPrompts: ["me de uma dica", "explique o conceito", "verifique minha resposta", "crie um mini exercicio"],
    reference: "referencia",
    patternsFor: (fileName: string) => `padroes para ${fileName}`,
    showOutput: "mostrar saida",
    hideOutput: "ocultar saida",
    output: "saida",
    tracks: {
      choice: { label: "multipla escolha", shortLabel: "escolha" },
      fill: { label: "preencher lacuna", shortLabel: "lacuna" },
      practical: { label: "pratica", shortLabel: "codigo" },
    },
  }),
  ru: programmingCopyFromEnglish({
    brand: "Практика кода",
    languages: "Языки",
    queue: "Очередь",
    expanding: "пополняется",
    zeroBase: "с нуля",
    session: "сессия",
    correct: "верно",
    answered: "отвечено",
    workspace: "рабочая зона",
    nextUnsolved: "следующая открытая",
    reset: "сброс",
    resetConfirm: (language: string) => `Сбросить локальную практику ${language}?`,
    statusSolved: "решено",
    statusReview: "повторить",
    statusDraft: "черновик",
    statusNew: "новый",
    question: "вопрос",
    questionPalette: "панель вопросов",
    prev: "назад",
    next: "вперед",
    submit: "проверить",
    run: "тест",
    hint: "подсказка",
    answer: "ответ",
    correctMessage: "верно",
    notYetMessage: "пока нет. Открой подсказку или сравни с ответом.",
    wrongNote: "подсказки появляются после первой попытки.",
    codePlaceholder: "пиши код здесь",
    fillPlaceholder: "введи ответ",
    inspector: "проверка",
    feedback: "обратная связь",
    typingFirst: "сначала печатай",
    vimReview: "Vim повтор",
    runOutput: "результат теста",
    runEmpty: "тест проверяет пример вывода или нужные части.",
    hints: "подсказки",
    hintEmpty: "сначала попробуй. Затем открой подсказку.",
    answerEmpty: "ответ нужен только для сравнения с твоей работой.",
    shortcuts: "горячие клавиши",
    shortcutItems: ["Ctrl Enter проверить", "Alt R тест", "Alt H подсказка", "Alt A ответ", "Alt стрелки переход", "1 2 3 4 выбор"],
    vimShortcut: "J K переход",
    coachTitle: "помощник по коду",
    coachSubtitle: "одна подсказка за раз. Он читает вопрос, твой ответ и контекст языка.",
    coachPlaceholder: "попроси подсказку, проверку бага, объяснение или упражнение",
    coachPrompts: ["дай подсказку", "объясни концепт", "проверь ответ", "сделай мини упражнение"],
    reference: "справка",
    patternsFor: (fileName: string) => `шаблоны для ${fileName}`,
    showOutput: "показать вывод",
    hideOutput: "скрыть вывод",
    output: "вывод",
    tracks: {
      choice: { label: "выбор ответа", shortLabel: "выбор" },
      fill: { label: "заполнить пропуск", shortLabel: "пропуск" },
      practical: { label: "практика", shortLabel: "код" },
    },
  }),
  ar: {
    brand: "تدريب البرمجة",
    languages: "اللغات",
    queue: "قائمة التدريب",
    expanding: "قيد التوسيع",
    zeroBase: "من الصفر",
    session: "الجلسة",
    correct: "صحيح",
    answered: "مجابة",
    workspace: "مساحة العمل",
    nextUnsolved: "التالي غير المحلول",
    reset: "إعادة ضبط",
    resetConfirm: (language: string) => `هل تريد إعادة ضبط تدريب ${language}؟`,
    statusSolved: "محلول",
    statusReview: "مراجعة",
    statusDraft: "مسودة",
    statusNew: "جديد",
    question: "السؤال",
    questionShort: "س",
    questionPalette: "لوحة الأسئلة",
    prev: "السابق",
    next: "التالي",
    submit: "إرسال",
    run: "اختبار",
    hint: "تلميح",
    answer: "الإجابة",
    correctMessage: "صحيح",
    notYetMessage: "ليس بعد. جرّب تلميحا أو قارن بالإجابة.",
    wrongNote: "تظهر التلميحات بعد محاولة الحل.",
    codePlaceholder: "اكتب الكود هنا",
    fillPlaceholder: "اكتب الإجابة",
    inspector: "الفاحص",
    feedback: "ملاحظات",
    typingFirst: "الكتابة أولا",
    vimReview: "مراجعة Vim",
    runOutput: "نتيجة الاختبار",
    runEmpty: "الاختبار يفحص ناتج المثال أو الأجزاء المطلوبة.",
    hints: "تلميحات",
    hintEmpty: "حاول مرة واحدة. ثم افتح تلميحا عند الحاجة.",
    answerEmpty: "استخدم الإجابة للمقارنة مع عملك فقط.",
    shortcuts: "اختصارات",
    shortcutItems: ["Ctrl Enter إرسال", "Alt R اختبار", "Alt H تلميح", "Alt A إجابة", "Alt سهم للتنقل", "1 2 3 4 اختيار"],
    vimShortcut: "J K تنقل",
    coachTitle: "مساعد البرمجة",
    coachSubtitle: "تلميح واحد في كل مرة. يقرأ السؤال وإجابتك وسياق اللغة.",
    coachPlaceholder: "اطلب تلميحا أو فحص خطأ أو شرحا أو تمرينا جديدا",
    coachPrompts: ["أعطني تلميحا", "اشرح المفهوم", "افحص إجابتي", "اصنع تمرينا صغيرا"],
    reference: "مرجع",
    patternsFor: (fileName: string) => `أنماط ${fileName}`,
    showOutput: "إظهار الناتج",
    hideOutput: "إخفاء الناتج",
    output: "الناتج",
    tracks: {
      choice: { label: "اختيار من متعدد", shortLabel: "اختيار" },
      fill: { label: "ملء الفراغ", shortLabel: "فراغ" },
      practical: { label: "تطبيق عملي", shortLabel: "عملي" },
    },
    roleFallback: (role: string) => role,
  },
  hi: programmingCopyFromEnglish({
    brand: "कोड अभ्यास",
    languages: "भाषाएं",
    queue: "अभ्यास सूची",
    expanding: "बढ़ रहा है",
    zeroBase: "शून्य से",
    session: "सत्र",
    correct: "सही",
    answered: "उत्तर",
    workspace: "वर्कस्पेस",
    nextUnsolved: "अगला बाकी",
    reset: "रीसेट",
    resetConfirm: (language: string) => `${language} का स्थानीय अभ्यास रीसेट करें?`,
    statusSolved: "हल",
    statusReview: "दोहराएं",
    statusDraft: "मसौदा",
    statusNew: "नया",
    question: "प्रश्न",
    questionPalette: "प्रश्न पैनल",
    prev: "पिछला",
    next: "अगला",
    submit: "जांचें",
    run: "चलाएं",
    hint: "संकेत",
    answer: "उत्तर",
    correctMessage: "सही",
    notYetMessage: "अभी नहीं. संकेत खोलें या उत्तर से मिलाएं.",
    wrongNote: "संकेत पहली कोशिश के बाद खुलते हैं.",
    codePlaceholder: "यहां कोड लिखें",
    fillPlaceholder: "उत्तर लिखें",
    inspector: "जांच",
    feedback: "प्रतिक्रिया",
    typingFirst: "पहले टाइप",
    vimReview: "Vim दोहराव",
    runOutput: "चलाने का परिणाम",
    runEmpty: "जांच sample output या जरूरी हिस्से देखती है.",
    hints: "संकेत",
    hintEmpty: "पहले खुद कोशिश करें. फिर संकेत खोलें.",
    answerEmpty: "उत्तर सिर्फ तुलना के लिए खोलें.",
    shortcuts: "शॉर्टकट",
    shortcutItems: ["Ctrl Enter जांच", "Alt R चलाएं", "Alt H संकेत", "Alt A उत्तर", "Alt arrows बदलें", "1 2 3 4 विकल्प"],
    vimShortcut: "J K बदलें",
    coachTitle: "प्रोग्रामिंग साथी",
    coachSubtitle: "एक बार में एक संकेत. यह प्रश्न, आपका उत्तर और भाषा संदर्भ पढ़ता है.",
    coachPlaceholder: "संकेत, bug check, समझाना या नया अभ्यास मांगें",
    coachPrompts: ["एक संकेत दें", "concept समझाएं", "मेरा उत्तर जांचें", "छोटा अभ्यास बनाएं"],
    reference: "संदर्भ",
    patternsFor: (fileName: string) => `${fileName} के pattern`,
    showOutput: "output दिखाएं",
    hideOutput: "output छिपाएं",
    output: "output",
    tracks: {
      choice: { label: "बहुविकल्प", shortLabel: "विकल्प" },
      fill: { label: "रिक्त भरें", shortLabel: "रिक्त" },
      practical: { label: "व्यावहारिक", shortLabel: "कोड" },
    },
  }),
  id: programmingCopyFromEnglish({
    brand: "Latihan kode",
    languages: "Bahasa",
    queue: "Antrian",
    expanding: "terus bertambah",
    zeroBase: "mulai dari nol",
    session: "sesi",
    correct: "benar",
    answered: "dijawab",
    workspace: "ruang kerja",
    nextUnsolved: "berikutnya",
    reset: "reset",
    resetConfirm: (language: string) => `Reset latihan lokal ${language}?`,
    statusSolved: "selesai",
    statusReview: "ulang",
    statusDraft: "draf",
    statusNew: "baru",
    question: "soal",
    questionPalette: "panel soal",
    prev: "sebelum",
    next: "lanjut",
    submit: "cek",
    run: "uji",
    hint: "petunjuk",
    answer: "jawaban",
    correctMessage: "benar",
    notYetMessage: "belum. Buka petunjuk atau bandingkan dengan jawaban.",
    wrongNote: "petunjuk muncul setelah kamu mencoba.",
    codePlaceholder: "tulis kode di sini",
    fillPlaceholder: "tulis jawaban",
    inspector: "pemeriksa",
    feedback: "umpan balik",
    typingFirst: "ketik dulu",
    vimReview: "review Vim",
    runOutput: "hasil uji",
    runEmpty: "uji memeriksa output contoh atau bagian wajib.",
    hints: "petunjuk",
    hintEmpty: "coba sekali dulu. Lalu buka petunjuk.",
    answerEmpty: "gunakan jawaban hanya untuk membandingkan pekerjaanmu.",
    shortcuts: "pintasan",
    shortcutItems: ["Ctrl Enter cek", "Alt R uji", "Alt H petunjuk", "Alt A jawaban", "Alt panah pindah", "1 2 3 4 pilihan"],
    vimShortcut: "J K pindah",
    coachTitle: "teman pemrograman",
    coachSubtitle: "satu petunjuk tiap kali. Ia membaca soal, jawabanmu, dan konteks bahasa.",
    coachPlaceholder: "minta petunjuk, cek bug, penjelasan, atau latihan kecil",
    coachPrompts: ["beri satu petunjuk", "jelaskan konsep", "cek jawaban saya", "buat latihan kecil"],
    reference: "referensi",
    patternsFor: (fileName: string) => `pola untuk ${fileName}`,
    showOutput: "tampilkan output",
    hideOutput: "sembunyikan output",
    output: "output",
    tracks: {
      choice: { label: "pilihan ganda", shortLabel: "pilihan" },
      fill: { label: "isi kosong", shortLabel: "isian" },
      practical: { label: "praktik", shortLabel: "kode" },
    },
  }),
  vi: programmingCopyFromEnglish({
    brand: "Luyen code",
    languages: "Ngon ngu",
    queue: "Hang bai",
    expanding: "dang mo rong",
    zeroBase: "tu con so 0",
    session: "phien hoc",
    correct: "dung",
    answered: "da lam",
    workspace: "ban luyen",
    nextUnsolved: "bai chua lam",
    reset: "dat lai",
    resetConfirm: (language: string) => `Dat lai tien do ${language}?`,
    statusSolved: "da giai",
    statusReview: "on lai",
    statusDraft: "nhap",
    statusNew: "moi",
    question: "cau",
    questionPalette: "bang cau hoi",
    prev: "truoc",
    next: "tiep",
    submit: "kiem tra",
    run: "thu chay",
    hint: "goi y",
    answer: "dap an",
    correctMessage: "dung",
    notYetMessage: "chua dung. Mo goi y hoac so voi dap an.",
    wrongNote: "goi y chi hien sau khi ban thu lam.",
    codePlaceholder: "viet code o day",
    fillPlaceholder: "nhap dap an",
    inspector: "kiem tra",
    feedback: "phan hoi",
    typingFirst: "go truoc",
    vimReview: "on Vim",
    runOutput: "ket qua chay",
    runEmpty: "thu chay kiem tra output mau hoac phan bat buoc.",
    hints: "goi y",
    hintEmpty: "hay thu mot lan. Sau do mo goi y neu can.",
    answerEmpty: "chi xem dap an khi muon doi chieu.",
    shortcuts: "phim tat",
    shortcutItems: ["Ctrl Enter kiem tra", "Alt R chay", "Alt H goi y", "Alt A dap an", "Alt mui ten doi bai", "1 2 3 4 chon"],
    vimShortcut: "J K doi bai",
    coachTitle: "tro ly lap trinh",
    coachSubtitle: "moi lan mot goi y. Doc cau hoi, dap an cua ban va ngu canh ngon ngu.",
    coachPlaceholder: "xin goi y, kiem bug, giai thich hoac bai tap nho",
    coachPrompts: ["cho mot goi y", "giai thich khai niem", "kiem tra dap an", "tao bai tap nho"],
    reference: "tham khao",
    patternsFor: (fileName: string) => `mau cho ${fileName}`,
    showOutput: "hien output",
    hideOutput: "an output",
    output: "output",
    tracks: {
      choice: { label: "trac nghiem", shortLabel: "chon" },
      fill: { label: "dien khuyet", shortLabel: "dien" },
      practical: { label: "thuc hanh", shortLabel: "code" },
    },
  }),
  th: programmingCopyFromEnglish({
    brand: "ฝึกเขียนโค้ด",
    languages: "ภาษา",
    queue: "คิวฝึก",
    expanding: "กำลังเพิ่ม",
    zeroBase: "เริ่มจากศูนย์",
    session: "เซสชัน",
    correct: "ถูก",
    answered: "ตอบแล้ว",
    workspace: "พื้นที่ฝึก",
    nextUnsolved: "ข้อถัดไป",
    reset: "รีเซ็ต",
    resetConfirm: (language: string) => `รีเซ็ตการฝึก ${language} หรือไม่`,
    statusSolved: "ผ่านแล้ว",
    statusReview: "ทบทวน",
    statusDraft: "ร่าง",
    statusNew: "ใหม่",
    question: "ข้อ",
    questionPalette: "แผงข้อ",
    prev: "ก่อนหน้า",
    next: "ถัดไป",
    submit: "ตรวจ",
    run: "ทดสอบ",
    hint: "คำใบ้",
    answer: "คำตอบ",
    correctMessage: "ถูกต้อง",
    notYetMessage: "ยังไม่ใช่ เปิดคำใบ้หรือเทียบกับคำตอบ",
    wrongNote: "คำใบ้จะเปิดหลังจากลองทำก่อน",
    codePlaceholder: "เขียนโค้ดที่นี่",
    fillPlaceholder: "พิมพ์คำตอบ",
    inspector: "ตัวตรวจ",
    feedback: "ผลตอบกลับ",
    typingFirst: "พิมพ์ก่อน",
    vimReview: "ทบทวน Vim",
    runOutput: "ผลทดสอบ",
    runEmpty: "การทดสอบจะดู output ตัวอย่างหรือส่วนที่ต้องมี",
    hints: "คำใบ้",
    hintEmpty: "ลองทำหนึ่งครั้งก่อน แล้วค่อยเปิดคำใบ้",
    answerEmpty: "เปิดคำตอบเมื่ออยากเทียบงานของคุณ",
    shortcuts: "ปุ่มลัด",
    shortcutItems: ["Ctrl Enter ตรวจ", "Alt R ทดสอบ", "Alt H คำใบ้", "Alt A คำตอบ", "Alt ลูกศร เปลี่ยนข้อ", "1 2 3 4 ตัวเลือก"],
    vimShortcut: "J K เปลี่ยนข้อ",
    coachTitle: "ผู้ช่วยเขียนโปรแกรม",
    coachSubtitle: "ให้คำใบ้ทีละข้อ อ่านโจทย์ คำตอบ และบริบทภาษา",
    coachPlaceholder: "ขอคำใบ้ ตรวจ bug อธิบาย หรือสร้างแบบฝึก",
    coachPrompts: ["ให้คำใบ้หนึ่งข้อ", "อธิบายแนวคิด", "ตรวจคำตอบ", "สร้างแบบฝึกสั้น"],
    reference: "อ้างอิง",
    patternsFor: (fileName: string) => `รูปแบบของ ${fileName}`,
    showOutput: "แสดง output",
    hideOutput: "ซ่อน output",
    output: "output",
    tracks: {
      choice: { label: "ปรนัย", shortLabel: "เลือก" },
      fill: { label: "เติมคำ", shortLabel: "เติม" },
      practical: { label: "ปฏิบัติ", shortLabel: "โค้ด" },
    },
  }),
  tr: programmingCopyFromEnglish({
    brand: "Kod Pratigi",
    languages: "Diller",
    queue: "Sira",
    expanding: "genisliyor",
    zeroBase: "sifirdan",
    session: "oturum",
    correct: "dogru",
    answered: "cevaplandi",
    workspace: "calisma alani",
    nextUnsolved: "siradaki bos",
    reset: "sifirla",
    resetConfirm: (language: string) => `${language} yerel pratik durumunu sifirla?`,
    statusSolved: "cozuldu",
    statusReview: "tekrar",
    statusDraft: "taslak",
    statusNew: "yeni",
    question: "soru",
    questionPalette: "soru paneli",
    prev: "onceki",
    next: "sonraki",
    submit: "kontrol",
    run: "test",
    hint: "ipucu",
    answer: "cevap",
    correctMessage: "dogru",
    notYetMessage: "henuz degil. Ipucu ac veya cevapla karsilastir.",
    wrongNote: "ipuclari ilk denemeden sonra gelir.",
    codePlaceholder: "kodunu buraya yaz",
    fillPlaceholder: "cevabi yaz",
    inspector: "denetleyici",
    feedback: "geri bildirim",
    typingFirst: "once yaz",
    vimReview: "Vim tekrar",
    runOutput: "test sonucu",
    runEmpty: "test ornek ciktiyi veya gerekli parcalari kontrol eder.",
    hints: "ipuclari",
    hintEmpty: "once bir kez dene. Gerekirse ipucu ac.",
    answerEmpty: "cevabi sadece karsilastirmak icin kullan.",
    shortcuts: "kisayollar",
    shortcutItems: ["Ctrl Enter kontrol", "Alt R test", "Alt H ipucu", "Alt A cevap", "Alt oklar gec", "1 2 3 4 secim"],
    vimShortcut: "J K gec",
    coachTitle: "programlama yardimcisi",
    coachSubtitle: "her seferinde bir ipucu. Soruyu, cevabini ve dil baglamini okur.",
    coachPlaceholder: "ipucu, hata kontrolu, aciklama veya yeni alistirma iste",
    coachPrompts: ["bir ipucu ver", "kavrami acikla", "cevabimi kontrol et", "mini alistirma yap"],
    reference: "referans",
    patternsFor: (fileName: string) => `${fileName} kaliplari`,
    showOutput: "ciktiyi goster",
    hideOutput: "ciktiyi gizle",
    output: "cikti",
    tracks: {
      choice: { label: "coktan secmeli", shortLabel: "secim" },
      fill: { label: "bosluk doldur", shortLabel: "bosluk" },
      practical: { label: "pratik", shortLabel: "kod" },
    },
  }),
  it: programmingCopyFromEnglish({
    brand: "Pratica codice",
    languages: "Linguaggi",
    queue: "Coda",
    expanding: "in crescita",
    zeroBase: "da zero",
    session: "sessione",
    correct: "corretto",
    answered: "risposte",
    workspace: "laboratorio",
    nextUnsolved: "prossima aperta",
    reset: "reset",
    resetConfirm: (language: string) => `Azzerare la pratica locale di ${language}?`,
    statusSolved: "risolto",
    statusReview: "ripasso",
    statusDraft: "bozza",
    statusNew: "nuovo",
    question: "domanda",
    questionPalette: "pannello domande",
    prev: "precedente",
    next: "successiva",
    submit: "controlla",
    run: "testa",
    hint: "indizio",
    answer: "risposta",
    correctMessage: "corretto",
    notYetMessage: "non ancora. Apri un indizio o confronta con la risposta.",
    wrongNote: "gli indizi restano nascosti finche provi una volta.",
    codePlaceholder: "scrivi il codice qui",
    fillPlaceholder: "scrivi la risposta",
    inspector: "ispettore",
    feedback: "feedback",
    typingFirst: "scrivi prima",
    vimReview: "ripasso Vim",
    runOutput: "output test",
    runEmpty: "il test controlla output esempio o parti richieste.",
    hints: "indizi",
    hintEmpty: "prova una volta. Poi apri un indizio.",
    answerEmpty: "usa la risposta solo per confrontare il tuo lavoro.",
    shortcuts: "scorciatoie",
    shortcutItems: ["Ctrl Enter controlla", "Alt R testa", "Alt H indizio", "Alt A risposta", "Alt frecce cambia", "1 2 3 4 scelta"],
    vimShortcut: "J K cambia",
    coachTitle: "compagno di programmazione",
    coachSubtitle: "un indizio alla volta. Legge domanda, risposta e contesto.",
    coachPlaceholder: "chiedi indizio, controllo bug, spiegazione o esercizio",
    coachPrompts: ["dammi un indizio", "spiega il concetto", "controlla la risposta", "crea un esercizio"],
    reference: "riferimento",
    patternsFor: (fileName: string) => `schemi per ${fileName}`,
    showOutput: "mostra output",
    hideOutput: "nascondi output",
    output: "output",
    tracks: {
      choice: { label: "scelta multipla", shortLabel: "scelta" },
      fill: { label: "riempi spazio", shortLabel: "spazio" },
      practical: { label: "pratica", shortLabel: "codice" },
    },
  }),
  nl: programmingCopyFromEnglish({
    brand: "Code oefenen",
    languages: "Talen",
    queue: "Rij",
    expanding: "groeit",
    zeroBase: "vanaf nul",
    session: "sessie",
    correct: "goed",
    answered: "beantwoord",
    workspace: "werkplek",
    nextUnsolved: "volgende open",
    reset: "reset",
    resetConfirm: (language: string) => `Lokale oefenstand voor ${language} resetten?`,
    statusSolved: "opgelost",
    statusReview: "herhalen",
    statusDraft: "concept",
    statusNew: "nieuw",
    question: "vraag",
    questionPalette: "vragenpaneel",
    prev: "vorige",
    next: "volgende",
    submit: "controleer",
    run: "test",
    hint: "hint",
    answer: "antwoord",
    correctMessage: "goed",
    notYetMessage: "nog niet. Open een hint of vergelijk met het antwoord.",
    wrongNote: "hints verschijnen pas na je eerste poging.",
    codePlaceholder: "schrijf je code hier",
    fillPlaceholder: "typ het antwoord",
    inspector: "controle",
    feedback: "feedback",
    typingFirst: "eerst typen",
    vimReview: "Vim herhaling",
    runOutput: "testuitvoer",
    runEmpty: "de test controleert voorbeeldoutput of vereiste delen.",
    hints: "hints",
    hintEmpty: "probeer eerst een keer. Open daarna een hint.",
    answerEmpty: "gebruik het antwoord alleen om te vergelijken.",
    shortcuts: "sneltoetsen",
    shortcutItems: ["Ctrl Enter controleer", "Alt R test", "Alt H hint", "Alt A antwoord", "Alt pijlen wissel", "1 2 3 4 keuze"],
    vimShortcut: "J K wissel",
    coachTitle: "programmeer maatje",
    coachSubtitle: "een hint per keer. Leest vraag, jouw antwoord en taalcontext.",
    coachPlaceholder: "vraag hint, bugcheck, uitleg of nieuwe oefening",
    coachPrompts: ["geef een hint", "leg het concept uit", "controleer mijn antwoord", "maak een mini oefening"],
    reference: "referentie",
    patternsFor: (fileName: string) => `patronen voor ${fileName}`,
    showOutput: "toon output",
    hideOutput: "verberg output",
    output: "output",
    tracks: {
      choice: { label: "meerkeuze", shortLabel: "keuze" },
      fill: { label: "gat invullen", shortLabel: "invullen" },
      practical: { label: "praktijk", shortLabel: "code" },
    },
  }),
  pl: programmingCopyFromEnglish({
    brand: "Praktyka kodu",
    languages: "Jezyki",
    queue: "Kolejka",
    expanding: "rosnie",
    zeroBase: "od zera",
    session: "sesja",
    correct: "dobrze",
    answered: "odpowiedziano",
    workspace: "warsztat",
    nextUnsolved: "nastepne otwarte",
    reset: "reset",
    resetConfirm: (language: string) => `Zresetowac lokalna praktyke ${language}?`,
    statusSolved: "rozwiazane",
    statusReview: "powtorka",
    statusDraft: "szkic",
    statusNew: "nowe",
    question: "pytanie",
    questionPalette: "panel pytan",
    prev: "wstecz",
    next: "dalej",
    submit: "sprawdz",
    run: "test",
    hint: "podpowiedz",
    answer: "odpowiedz",
    correctMessage: "dobrze",
    notYetMessage: "jeszcze nie. Otworz podpowiedz albo porownaj z odpowiedzia.",
    wrongNote: "podpowiedzi pojawiaja sie po pierwszej probie.",
    codePlaceholder: "napisz kod tutaj",
    fillPlaceholder: "wpisz odpowiedz",
    inspector: "inspektor",
    feedback: "informacja",
    typingFirst: "najpierw pisz",
    vimReview: "powtorka Vim",
    runOutput: "wynik testu",
    runEmpty: "test sprawdza output przykladu lub wymagane czesci.",
    hints: "podpowiedzi",
    hintEmpty: "najpierw sproboj. Potem otworz podpowiedz.",
    answerEmpty: "uzyj odpowiedzi tylko do porownania pracy.",
    shortcuts: "skroty",
    shortcutItems: ["Ctrl Enter sprawdz", "Alt R test", "Alt H podpowiedz", "Alt A odpowiedz", "Alt strzalki zmien", "1 2 3 4 wybor"],
    vimShortcut: "J K zmien",
    coachTitle: "towarzysz programowania",
    coachSubtitle: "jedna podpowiedz naraz. Czyta pytanie, odpowiedz i kontekst.",
    coachPlaceholder: "popros o podpowiedz, bugcheck, wyjasnienie lub cwiczenie",
    coachPrompts: ["daj podpowiedz", "wyjasnij koncept", "sprawdz odpowiedz", "stworz mini cwiczenie"],
    reference: "referencja",
    patternsFor: (fileName: string) => `wzorce dla ${fileName}`,
    showOutput: "pokaz output",
    hideOutput: "ukryj output",
    output: "output",
    tracks: {
      choice: { label: "wybor wielokrotny", shortLabel: "wybor" },
      fill: { label: "uzupelnij luke", shortLabel: "luka" },
      practical: { label: "praktyka", shortLabel: "kod" },
    },
  }),
};

const languageRoleZh: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "浏览器应用 自动化 和 API 胶水层",
  typescript: "适合产品级规模的类型化 JavaScript",
  python: "自动化 数据脚本 和后端 API",
  cpp: "高性能 系统 算法 和竞赛",
  java: "后端 Android 企业开发 和类型化面向对象",
  go: "云服务 命令行 并发 和 API",
  rust: "安全系统 高性能 和可靠工具链",
  sql: "数据查询 产品分析 和数据库",
  "html-css": "页面结构 样式 和响应式界面",
  bash: "终端自动化 部署 和文件流程",
  csharp: "dotnet 后端 桌面 游戏 和企业应用",
  php: "Web 后端 CMS 和服务端渲染",
};

const languageRoleJa: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "Web アプリ、自動化、API 連携に使う言語",
  typescript: "大きな JavaScript 製品を型で安全にする言語",
  python: "自動化、データ処理、バックエンド API に使う言語",
  cpp: "性能、システム、アルゴリズムを学ぶための言語",
  java: "バックエンド、Android、企業開発で使う言語",
  go: "クラウドサービス、CLI、並行処理に向く言語",
  rust: "安全性と性能を両立するシステム言語",
  sql: "データを検索、集計、更新するための言語",
  "html-css": "Web ページの構造と見た目を作る基礎",
  bash: "ターミナル操作とファイル処理を自動化する言語",
};

const languageRoleEs: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "lenguaje para apps web, automatización y APIs",
  typescript: "JavaScript con tipos para productos grandes",
  python: "automatización, datos y APIs de backend",
  cpp: "rendimiento, sistemas, memoria y algoritmos",
  java: "backend, Android y desarrollo empresarial",
  go: "servicios cloud, CLI y concurrencia",
  rust: "sistemas seguros con alto rendimiento",
  sql: "consultar, agregar y actualizar datos",
  "html-css": "estructura visual y estilos de páginas web",
  bash: "automatizar terminal, archivos y despliegues",
};

const languageRoleKo: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "웹 앱 자동화 API 연결에 쓰는 언어",
  typescript: "큰 JavaScript 제품을 타입으로 안전하게 만드는 언어",
  python: "자동화 데이터 처리 백엔드 API에 쓰는 언어",
  cpp: "성능 시스템 메모리 알고리즘을 배우는 언어",
  java: "백엔드 Android 기업 개발에 쓰는 언어",
  go: "클라우드 서비스 CLI 동시성에 적합한 언어",
  rust: "안전성과 성능을 함께 추구하는 시스템 언어",
  sql: "데이터를 조회 집계 업데이트하는 언어",
  "html-css": "웹 페이지 구조와 스타일을 만드는 기초",
  bash: "터미널 파일 배포 작업을 자동화하는 언어",
};

const languageRoleAr: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "تطبيقات الويب والأتمتة وربط الواجهات",
  typescript: "منتجات JavaScript أكبر مع عقود أنواع واضحة",
  python: "الأتمتة والبيانات وواجهات backend",
  cpp: "الأداء والأنظمة والذاكرة والخوارزميات",
  java: "الخوادم و Android والتطبيقات المؤسسية",
  go: "خدمات السحابة وأدوات CLI والتزامن",
  rust: "لغة أنظمة آمنة وعالية الأداء",
  sql: "البحث في البيانات وتجميعها وتحديثها",
  "html-css": "بناء هيكل الصفحة وشكلها",
  bash: "أتمتة الطرفية والملفات والنشر",
};

const languageHabitZh: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "先用 console.log 和开发者工具看清值，再抽象",
  typescript: "让类型错误告诉你缺了哪个数据契约",
  python: "每次转换数据后都打印一次数据形状",
  cpp: "编译前先手动跟踪内存、下标和容器状态",
};

const languageHabitJa: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "抽象化する前に console.log と開発者ツールで値を確認する",
  typescript: "型エラーから足りないデータ契約を読む",
  python: "データを変換するたびに形を小さく確認する",
  cpp: "コンパイル前にメモリ、添字、コンテナ状態を手で追う",
};

const languageHabitEs: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "mira valores con console.log y herramientas de desarrollo antes de abstraer",
  typescript: "deja que los tipos indiquen el contrato que falta",
  python: "comprueba la forma de los datos después de cada transformación",
  cpp: "rastrea memoria, índices y contenedores antes de compilar",
};

const languageHabitKo: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "추상화 전에 console.log 와 개발자 도구로 값을 확인합니다",
  typescript: "타입 오류가 알려주는 빠진 데이터 계약을 읽습니다",
  python: "데이터를 변환할 때마다 형태를 작게 확인합니다",
  cpp: "컴파일 전에 메모리 인덱스 컨테이너 상태를 손으로 추적합니다",
};

const languageHabitAr: Partial<Record<ProgrammingLanguageSlug, string>> = {
  javascript: "افحص القيم عبر console.log وأدوات المطور قبل التجريد",
  typescript: "دع أخطاء الأنواع تكشف عقد البيانات الناقص",
  python: "افحص شكل البيانات بعد كل تحويل",
  cpp: "تتبع الذاكرة والفهارس والحاويات قبل التجميع",
};

function genericRoleForInterface(activeLanguage: ReturnType<typeof getProgrammingLanguage>, language: InterfaceLanguage) {
  const title = activeLanguage.title;
  const roles: Partial<Record<InterfaceLanguage, string>> = {
    zh: `从零学习 ${title} 的核心语法 运行方式 和基础实战`,
    ja: `${title} をゼロから学ぶための基本構文、実行、実践`,
    ko: `${title} 를 처음부터 배우기 위한 기본 문법 실행 실습`,
    es: `ruta practica para aprender ${title} desde cero`,
    fr: `parcours pratique pour apprendre ${title} depuis zero`,
    de: `praktischer Lernpfad fuer ${title} von null an`,
    pt: `trilha pratica para aprender ${title} do zero`,
    ru: `практический путь для изучения ${title} с нуля`,
    ar: `مسار عملي لتعلم ${title} من الصفر`,
    hi: `${title} को शून्य से सीखने का व्यावहारिक रास्ता`,
    id: `jalur praktis untuk belajar ${title} dari nol`,
    vi: `lo trinh thuc hanh de hoc ${title} tu con so 0`,
    th: `เส้นทางฝึก ${title} ตั้งแต่ศูนย์`,
    tr: `${title} icin sifirdan pratik ogrenme yolu`,
    it: `percorso pratico per imparare ${title} da zero`,
    nl: `praktisch leerpad om ${title} vanaf nul te leren`,
    pl: `praktyczna sciezka nauki ${title} od zera`,
  };
  return roles[language] ?? activeLanguage.role;
}

function genericHabitForInterface(activeLanguage: ReturnType<typeof getProgrammingLanguage>, language: InterfaceLanguage) {
  const title = activeLanguage.title;
  const habits: Partial<Record<InterfaceLanguage, string>> = {
    zh: `每学一个 ${title} 小语法 立刻写一个最小例子并运行`,
    ja: `${title} の小さな構文を一つ学んだら、すぐ最小例を入力して実行する`,
    ko: `${title} 작은 문법 하나를 배우면 바로 최소 예제를 입력하고 실행합니다`,
    es: `aprende una pieza pequena de ${title}, escribe un ejemplo minimo y ejecútalo`,
    fr: `apprends une petite piece de ${title}, tape un exemple minimal et execute-le`,
    de: `lerne ein kleines ${title} Stueck, tippe ein Minimalbeispiel und fuehre es aus`,
    pt: `aprenda uma parte pequena de ${title}, digite um exemplo minimo e execute`,
    ru: `изучи маленькую часть ${title}, набери минимальный пример и запусти`,
    ar: `تعلم جزءا صغيرا من ${title} ثم اكتب مثالا صغيرا وشغله`,
    hi: `${title} का छोटा हिस्सा सीखें, minimal example टाइप करें और चलाएं`,
    id: `pelajari satu bagian kecil ${title}, ketik contoh minimal, lalu jalankan`,
    vi: `hoc mot phan nho cua ${title}, go vi du toi thieu roi chay`,
    th: `เรียน ${title} ทีละส่วนเล็ก แล้วพิมพ์ตัวอย่างสั้นและรัน`,
    tr: `${title} icin kucuk bir parca ogren, minimal ornek yaz ve calistir`,
    it: `impara un piccolo pezzo di ${title}, scrivi un esempio minimo ed eseguilo`,
    nl: `leer een klein deel van ${title}, typ een minimaal voorbeeld en voer het uit`,
    pl: `poznaj maly fragment ${title}, wpisz minimalny przyklad i uruchom go`,
  };
  return habits[language] ?? activeLanguage.dailyHabit;
}

const methodZh: Record<string, string> = {
  "Recall from memory": "回忆输出",
  "Trace the code": "手动跟踪",
  "Type it yourself": "亲手敲一遍",
  "Mix topics": "混合练习",
  "Hints after trying": "先做后看提示",
  "Build small things": "做小作品",
};

const methodBodyZh: Record<string, string> = {
  "Recall from memory": "看完一个小点后 合上提示自己写出来",
  "Trace the code": "运行前先逐行写出变量变化",
  "Type it yourself": "少复制 多打字 每次只修一个小错",
  "Mix topics": "语法 数据结构 调试 小项目交替练",
  "Hints after trying": "先独立尝试 再一次只打开一个提示",
  "Build small things": "把每个知识块变成脚本 页面 查询或工具",
};

const methodI18n: Partial<Record<InterfaceLanguage, {
  title: Record<string, string>;
  body: Record<string, string>;
}>> = {
  zh: { title: methodZh, body: methodBodyZh },
  ja: {
    title: {
      "Recall from memory": "記憶から書く",
      "Trace the code": "コードを追跡",
      "Type it yourself": "自分で入力",
      "Mix topics": "トピックを混ぜる",
      "Hints after trying": "試してからヒント",
      "Build small things": "小さく作る",
    },
    body: {
      "Recall from memory": "小さな概念を見たら閉じて自分で再現します",
      "Trace the code": "実行前に変数の変化を一行ずつ追います",
      "Type it yourself": "コピーを減らし一つずつエラーを直します",
      "Mix topics": "構文 データ構造 デバッグ 小作品を交互に練習します",
      "Hints after trying": "先に自分で試しヒントは一つずつ開きます",
      "Build small things": "知識をスクリプト ページ クエリ ツールに変えます",
    },
  },
  ko: {
    title: {
      "Recall from memory": "기억으로 출력",
      "Trace the code": "코드 추적",
      "Type it yourself": "직접 입력",
      "Mix topics": "주제 섞기",
      "Hints after trying": "시도 후 힌트",
      "Build small things": "작게 만들기",
    },
    body: {
      "Recall from memory": "작은 개념을 본 뒤 닫고 직접 다시 써 봅니다",
      "Trace the code": "실행 전에 변수 변화를 한 줄씩 추적합니다",
      "Type it yourself": "복사를 줄이고 작은 오류를 하나씩 고칩니다",
      "Mix topics": "문법 자료구조 디버깅 작은 프로젝트를 번갈아 연습합니다",
      "Hints after trying": "먼저 직접 시도하고 힌트는 하나씩 엽니다",
      "Build small things": "지식을 스크립트 페이지 쿼리 도구로 바꿉니다",
    },
  },
  es: {
    title: {
      "Recall from memory": "recordar de memoria",
      "Trace the code": "seguir el código",
      "Type it yourself": "escribirlo tú",
      "Mix topics": "mezclar temas",
      "Hints after trying": "pistas después de intentar",
      "Build small things": "crear cosas pequeñas",
    },
    body: {
      "Recall from memory": "mira un concepto pequeño y luego recréalo sin mirar",
      "Trace the code": "antes de ejecutar escribe cómo cambian las variables",
      "Type it yourself": "copia menos y corrige un error pequeño cada vez",
      "Mix topics": "alterna sintaxis estructuras depuración y mini proyectos",
      "Hints after trying": "intenta solo y abre una pista cada vez",
      "Build small things": "convierte cada bloque en script página consulta o herramienta",
    },
  },
  ar: {
    title: {
      "Recall from memory": "استدعاء من الذاكرة",
      "Trace the code": "تتبع الكود",
      "Type it yourself": "اكتبه بنفسك",
      "Mix topics": "اخلط المواضيع",
      "Hints after trying": "تلميحات بعد المحاولة",
      "Build small things": "ابن أشياء صغيرة",
    },
    body: {
      "Recall from memory": "اقرأ فكرة صغيرة ثم أغلقها واكتبها من الذاكرة",
      "Trace the code": "قبل التشغيل اكتب كيف تتغير المتغيرات سطرا بسطر",
      "Type it yourself": "قلل النسخ وأصلح خطأ صغيرا كل مرة",
      "Mix topics": "بدل بين القواعد وهياكل البيانات والتصحيح والمشاريع الصغيرة",
      "Hints after trying": "حاول وحدك أولا ثم افتح تلميحا واحدا",
      "Build small things": "حوّل كل فكرة إلى سكربت أو صفحة أو استعلام أو أداة",
    },
  },
};

const trackSegments: TrackSegment[] = [
  {
    id: "choice",
    label: "Multiple choice",
    shortLabel: "Choice",
    start: 1,
    end: programmingBankPlan.multipleChoice,
    count: programmingBankPlan.multipleChoice,
  },
  {
    id: "fill",
    label: "Fill blank",
    shortLabel: "Fill",
    start: programmingBankPlan.multipleChoice + 1,
    end: programmingBankPlan.multipleChoice + programmingBankPlan.fillBlank,
    count: programmingBankPlan.fillBlank,
  },
  {
    id: "practical",
    label: "Practical",
    shortLabel: "Build",
    start: programmingBankPlan.multipleChoice + programmingBankPlan.fillBlank + 1,
    end: programmingBankPlan.perLanguage,
    count: programmingBankPlan.practical,
  },
];

function roleForInterface(activeLanguage: ReturnType<typeof getProgrammingLanguage>, language: InterfaceLanguage) {
  if (language === "zh") return languageRoleZh[activeLanguage.slug] ?? genericRoleForInterface(activeLanguage, language);
  if (language === "ja") return languageRoleJa[activeLanguage.slug] ?? genericRoleForInterface(activeLanguage, language);
  if (language === "ko") return languageRoleKo[activeLanguage.slug] ?? genericRoleForInterface(activeLanguage, language);
  if (language === "es") return languageRoleEs[activeLanguage.slug] ?? genericRoleForInterface(activeLanguage, language);
  if (language === "ar") return languageRoleAr[activeLanguage.slug] ?? genericRoleForInterface(activeLanguage, language);
  return genericRoleForInterface(activeLanguage, language);
}

function habitForInterface(activeLanguage: ReturnType<typeof getProgrammingLanguage>, language: InterfaceLanguage) {
  if (language === "zh") return languageHabitZh[activeLanguage.slug] ?? genericHabitForInterface(activeLanguage, language);
  if (language === "ja") return languageHabitJa[activeLanguage.slug] ?? genericHabitForInterface(activeLanguage, language);
  if (language === "ko") return languageHabitKo[activeLanguage.slug] ?? genericHabitForInterface(activeLanguage, language);
  if (language === "es") return languageHabitEs[activeLanguage.slug] ?? genericHabitForInterface(activeLanguage, language);
  if (language === "ar") return languageHabitAr[activeLanguage.slug] ?? genericHabitForInterface(activeLanguage, language);
  return genericHabitForInterface(activeLanguage, language);
}

export {
  genericHabitForInterface,
  genericRoleForInterface,
  habitForInterface,
  methodI18n,
  programmingCopy,
  programmingRailSearchCopy,
  roleForInterface,
  trackSegments,
  typeLabel,
  zeroBaseSteps,
};

export type { KeyPreset, LineageProfile, ProgrammingCopyType, ProgrammingRailSearchCopy, ResultState };
