import type { InterfaceLanguage } from "@/lib/language";

const tutorialI18n: Partial<Record<InterfaceLanguage, Record<string, string>>> = {
  zh: {
    "Values and variables": "值和变量",
    "Functions": "函数",
    "Async APIs": "异步接口",
    "Program output": "程序输出",
    "Values and names": "值和命名",
    "Functions and collections": "函数和集合",
    "Prefer const first": "优先用 const",
    "Use let only when the value changes": "只有值会变化时才用 let",
    "Inspect values with console.log": "用 console.log 检查值",
    "Name functions with verbs": "函数名用动词",
    "Return values instead of printing inside every function": "优先 return 结果 不要每个函数都打印",
    "Keep one function focused": "一个函数只做一件事",
    "Check network errors": "检查网络错误",
    "Await the promise before reading data": "读取数据前先 await Promise",
    "Keep API parsing separate": "把接口解析单独放清楚",
    "Run the smallest file first": "先跑最小文件",
    "Print one known value": "先打印一个确定值",
    "Check the output before adding more code": "加代码前先看输出",
    "Give values readable names": "给值起可读名字",
    "Keep one idea per line while learning": "学习时一行只放一个想法",
    "Trace the value before changing it": "改值前先追踪它",
    "Keep functions small": "函数保持小",
    "Return useful values": "返回有用的值",
    "Use the common collection before reaching for frameworks": "先用常见集合 不急着上框架",
  },
  ja: {
    "Values and variables": "値と変数",
    "Functions": "関数",
    "Async APIs": "非同期 API",
    "Program output": "プログラム出力",
    "Values and names": "値と名前",
    "Functions and collections": "関数とコレクション",
    "Prefer const first": "まず const を使う",
    "Use let only when the value changes": "値が変わる時だけ let を使う",
    "Inspect values with console.log": "console.log で値を確認する",
    "Name functions with verbs": "関数名は動詞で始める",
    "Return values instead of printing inside every function": "各関数で出力せず値を返す",
    "Keep one function focused": "一つの関数は一つの役割にする",
    "Check network errors": "ネットワークエラーを確認する",
    "Await the promise before reading data": "データを読む前に Promise を待つ",
    "Keep API parsing separate": "API 解析を分ける",
    "Typed values": "型付きの値",
    "Interfaces": "インターフェース",
    "Narrowing": "型の絞り込み",
    "Variables": "変数",
    "Loops": "ループ",
    "Input output": "入出力",
    "Types": "型",
    "STL": "STL",
    "Class entry": "class の入口",
    "Objects": "オブジェクト",
    "Program shape": "プログラムの形",
    "Errors": "エラー",
    "Entry": "エントリ",
    "Bindings": "束縛",
    "Result": "Result の扱い",
    "Select": "列の選択",
    "Filter": "データを絞り込む",
    "Group": "データを集計する",
    "Semantic HTML": "意味のある HTML",
    "Layout": "レイアウト",
    "Responsive": "レスポンシブ",
    "Commands": "コマンド",
    "Pipes": "パイプ",
    "Scripts": "スクリプト",
    "Program": "プログラム",
    "Classes": "クラス",
    "Arrays": "配列",
    "Type public data shapes": "公開データの形には型を付ける",
    "Let local inference work": "局所的な型推論を活かす",
    "Fix red squiggles early": "型エラーは早めに直す",
    "Interfaces describe object shape": "interface はオブジェクトの形を表す",
    "Prefer exact fields": "必要なフィールドを正確に書く",
    "Use readable names": "読みやすい名前を使う",
    "Check before using": "使う前に確認する",
    "Use typeof and in": "typeof と in を使う",
    "Avoid any when learning": "学習中は any に逃げない",
    "Indentation matters": "インデントは重要",
    "Use descriptive names": "説明的な名前を使う",
    "Print intermediate values": "途中の値を出力する",
    "Use def to name work": "def で処理に名前を付ける",
    "Indent the body": "本体を正しくインデントする",
    "Return the result": "結果を返す",
    "Loop over values directly": "値を直接ループする",
    "Use enumerate when index matters": "番号が必要なら enumerate を使う",
    "Keep loop bodies short": "ループ本体は短く保つ",
    "Include the right headers": "必要な header を入れる",
    "Use cout for output": "出力には cout を使う",
    "Return from main": "main から return する",
    "Choose the right type": "適切な型を選ぶ",
    "Watch integer division": "整数除算に注意する",
    "Initialize variables": "変数を初期化する",
    "Know the container behavior": "コンテナの動きを理解する",
    "Use size for count": "個数には size を使う",
    "Trace push pop operations": "push と pop の動きを追う",
    "The file starts from a class": "ファイルは class から始まる",
    "main is the entry point": "main は入口",
    "System.out.println prints": "System.out.println は出力する",
    "Declare types explicitly": "型を明示して宣言する",
    "Use String with capital S": "大文字 S の String を使う",
    "Initialize before use": "使う前に初期化する",
    "Constructor initializes fields": "constructor はフィールドを初期化する",
    "this means current object": "this は現在のオブジェクトを指す",
    "Methods hold behavior": "method は振る舞いを持つ",
    "Every executable uses package main": "実行可能な Go は package main を使う",
    "main starts the program": "main がプログラムを開始する",
    "fmt.Println prints": "fmt.Println は出力する",
    "Use := inside functions": "関数内では := を使う",
    "Use var for package scope": "package スコープでは var を使う",
    "Prefer explicit errors": "明示的なエラーを優先する",
    "Errors are values": "エラーも値として扱う",
    "Check err quickly": "err はすぐ確認する",
    "Return early": "早めに return する",
    "Run the smallest file first": "最小のファイルから実行する",
    "Print one known value": "まず確実な値を一つ出力する",
    "Check the output before adding more code": "コードを増やす前に出力を確認する",
    "Give values readable names": "値に読みやすい名前を付ける",
    "Keep one idea per line while learning": "学習中は一行に一つの考えを書く",
    "Trace the value before changing it": "値を変える前に流れを追う",
    "Keep functions small": "関数を小さく保つ",
    "Return useful values": "役に立つ値を返す",
    "Use the common collection before reaching for frameworks": "framework の前に基本コレクションを使う",
    "println! is a macro": "println! はマクロ",
    "Use braces for blocks": "ブロックには波かっこを使う",
    "Bindings are immutable by default": "束縛は標準で変更不可",
    "Use mut only when needed": "必要な時だけ mut を使う",
    "Borrow instead of cloning blindly": "むやみに clone せず借用する",
    "Use Result for recoverable errors": "回復できるエラーには Result を使う",
    "Handle Err": "Err を処理する",
    "Use question mark in functions returning Result": "Result を返す関数では ? を使える",
    "Select only needed columns": "必要な列だけを選ぶ",
    "Read from one table first": "まず一つのテーブルから読む",
    "Add limits while exploring": "試す時は LIMIT を付ける",
    "WHERE filters rows": "WHERE は行を絞り込む",
    "ORDER BY sorts": "ORDER BY は並べ替える",
    "LIMIT protects exploration": "LIMIT は探索時の読み過ぎを防ぐ",
    "Aggregate after filtering": "絞り込み後に集計する",
    "Group by non aggregate columns": "集計しない列で group by する",
    "Name metrics clearly": "指標に分かりやすい名前を付ける",
    "Use semantic tags": "意味のあるタグを使う",
    "Labels belong with inputs": "label は input と組み合わせる",
    "Buttons are for actions": "操作には button を使う",
    "Use gap for spacing": "間隔には gap を使う",
    "Define stable widths": "安定した幅を決める",
    "Avoid layout shift": "レイアウトのずれを避ける",
    "Test small screens": "小さい画面で確認する",
    "Avoid viewport scaled fonts": "画面幅連動の文字サイズを避ける",
    "Keep controls reachable": "操作部品を押しやすく保つ",
    "Quote variables": "変数を引用符で囲む",
    "Start with echo": "echo から始める",
    "Run in a small folder first": "まず小さなフォルダで実行する",
    "Pipe output to the next command": "出力を次のコマンドへ渡す",
    "Use rg or grep for search": "検索には rg か grep を使う",
    "Count with wc": "wc で数える",
    "Use set -e for safer scripts": "安全な script には set -e を使う",
    "Quote paths": "path を引用符で囲む",
    "Dry run before deleting": "削除前に dry run する",
    "Top level statements keep beginners moving": "top level statements は初心者が始めやすい",
    "Use Console.WriteLine": "Console.WriteLine を使う",
    "Keep namespaces clear": "namespace を分かりやすく保つ",
    "Use explicit types first": "最初は明示的な型を使う",
    "Learn var after basics": "基礎の後で var を学ぶ",
    "Prefer readable names": "読みやすい名前を優先する",
    "Properties expose data": "property はデータを公開する",
    "Constructors set defaults": "constructor は初期値を設定する",
    "Variables start with dollar sign": "変数はドル記号で始まる",
    "echo outputs text": "echo は文字列を出力する",
    "End statements with semicolons": "文はセミコロンで終える",
    "Use function for reusable work": "再利用する処理には function を使う",
    "Validate input": "入力を検証する",
    "Return values": "値を返す",
    "Associative arrays use keys": "連想配列は key を使う",
    "foreach loops through arrays": "foreach は配列を順に処理する",
    "Escape output in HTML": "HTML 出力は escape する",
  },
  ko: {
    "Values and variables": "값과 변수",
    "Functions": "함수",
    "Async APIs": "비동기 API",
    "Program output": "프로그램 출력",
    "Values and names": "값과 이름",
    "Functions and collections": "함수와 컬렉션",
    "Prefer const first": "먼저 const 를 사용",
    "Use let only when the value changes": "값이 바뀔 때만 let 사용",
    "Inspect values with console.log": "console.log 로 값 확인",
    "Name functions with verbs": "함수 이름은 동사로",
    "Return values instead of printing inside every function": "모든 함수에서 출력하지 말고 값을 반환",
    "Keep one function focused": "함수 하나는 한 가지 일만",
  },
  es: {
    "Values and variables": "valores y variables",
    "Functions": "funciones",
    "Async APIs": "API asincronas",
    "Program output": "salida del programa",
    "Values and names": "valores y nombres",
    "Functions and collections": "funciones y colecciones",
    "Prefer const first": "prefiere const primero",
    "Use let only when the value changes": "usa let solo si el valor cambia",
    "Inspect values with console.log": "inspecciona valores con console.log",
    "Name functions with verbs": "nombra funciones con verbos",
    "Return values instead of printing inside every function": "devuelve valores en vez de imprimir dentro de cada funcion",
    "Keep one function focused": "mantén cada funcion enfocada",
  },
  ar: {
    "Values and variables": "القيم والمتغيرات",
    "Functions": "الدوال",
    "Async APIs": "واجهات غير متزامنة",
    "Typed values": "قيم ذات أنواع",
    "Interfaces": "واجهات",
    "Narrowing": "تضييق النوع",
    "Variables": "المتغيرات",
    "Loops": "الحلقات",
    "Input output": "الإدخال والإخراج",
    "Types": "الأنواع",
    "STL": "مكتبة STL",
    "Class entry": "مدخل class",
    "Objects": "الكائنات",
    "Program shape": "شكل البرنامج",
    "Errors": "الأخطاء",
    "Entry": "نقطة الدخول",
    "Bindings": "الربط والقيم",
    "Result": "نتائج الأخطاء",
    "Select": "اختيار البيانات",
    "Filter": "تصفية البيانات",
    "Group": "تجميع البيانات",
    "Semantic HTML": "HTML دلالي",
    "Layout": "التخطيط",
    "Responsive": "التجاوب",
    "Commands": "الأوامر",
    "Pipes": "الأنابيب",
    "Scripts": "السكربتات",
    "Program": "البرنامج",
    "Classes": "الكلاسات",
    "Arrays": "المصفوفات",
    "Program output": "ناتج البرنامج",
    "Values and names": "القيم والأسماء",
    "Functions and collections": "الدوال والمجموعات",
    "Prefer const first": "ابدأ ب const",
    "Use let only when the value changes": "استخدم let فقط عندما تتغير القيمة",
    "Inspect values with console.log": "افحص القيم باستخدام console.log",
    "Name functions with verbs": "سم الدوال بأفعال واضحة",
    "Return values instead of printing inside every function": "ارجع القيم بدل الطباعة داخل كل دالة",
    "Keep one function focused": "اجعل كل دالة مركزة على مهمة واحدة",
    "Check network errors": "افحص أخطاء الشبكة",
    "Await the promise before reading data": "انتظر Promise قبل قراءة البيانات",
    "Keep API parsing separate": "افصل تحليل API عن باقي الكود",
    "Type public data shapes": "حدد أنواع أشكال البيانات العامة",
    "Let local inference work": "دع الاستنتاج المحلي يعمل",
    "Fix red squiggles early": "أصلح أخطاء النوع مبكرا",
    "Interfaces describe object shape": "interfaces تصف شكل الكائن",
    "Prefer exact fields": "فضل الحقول الدقيقة",
    "Use readable names": "استخدم أسماء واضحة",
    "Check before using": "افحص قبل الاستخدام",
    "Use typeof and in": "استخدم typeof و in",
    "Avoid any when learning": "تجنب any أثناء التعلم",
    "Indentation matters": "المسافات البادئة مهمة",
    "Use descriptive names": "استخدم أسماء وصفية",
    "Print intermediate values": "اطبع القيم الوسيطة",
    "Use def to name work": "استخدم def لتسمية العمل",
    "Indent the body": "أدخل جسم الدالة بمسافة صحيحة",
    "Return the result": "ارجع النتيجة",
    "Loop over values directly": "مر على القيم مباشرة",
    "Use enumerate when index matters": "استخدم enumerate عندما يهم الفهرس",
    "Keep loop bodies short": "اجعل جسم الحلقة قصيرا",
    "Include the right headers": "أضف ملفات header الصحيحة",
    "Use cout for output": "استخدم cout للإخراج",
    "Return from main": "ارجع من main",
    "Choose the right type": "اختر النوع المناسب",
    "Watch integer division": "انتبه لقسمة الأعداد الصحيحة",
    "Initialize variables": "هيئ المتغيرات",
    "Know the container behavior": "افهم سلوك الحاوية",
    "Use size for count": "استخدم size للعد",
    "Trace push pop operations": "تتبع عمليات push و pop",
    "The file starts from a class": "الملف يبدأ من class",
    "System.out.println prints": "System.out.println تطبع",
    "Declare types explicitly": "صرح بالأنواع بوضوح",
    "Use String with capital S": "استخدم String بحرف S كبير",
    "Initialize before use": "هيئ قبل الاستخدام",
    "Constructor initializes fields": "constructor يهيئ الحقول",
    "this means current object": "this تعني الكائن الحالي",
    "Methods hold behavior": "methods تحمل السلوك",
    "Every executable uses package main": "كل برنامج تنفيذي يستخدم package main",
    "main starts the program": "main تبدأ البرنامج",
    "fmt.Println prints": "fmt.Println تطبع",
    "Use := inside functions": "استخدم := داخل الدوال",
    "Use var for package scope": "استخدم var لنطاق package",
    "Prefer explicit errors": "فضل الأخطاء الصريحة",
    "Errors are values": "الأخطاء قيم",
    "Check err quickly": "افحص err بسرعة",
    "Return early": "ارجع مبكرا",
    "Run the smallest file first": "شغل أصغر ملف أولا",
    "Print one known value": "اطبع قيمة معروفة واحدة",
    "Check the output before adding more code": "افحص الناتج قبل إضافة كود أكثر",
    "Give values readable names": "أعط القيم أسماء واضحة",
    "Keep one idea per line while learning": "اجعل كل سطر يحمل فكرة واحدة أثناء التعلم",
    "Trace the value before changing it": "تتبع القيمة قبل تغييرها",
    "Keep functions small": "اجعل الدوال صغيرة",
    "Return useful values": "ارجع قيما مفيدة",
    "Use the common collection before reaching for frameworks": "استخدم المجموعة الشائعة قبل اللجوء إلى الأطر",
    "main is the entry point": "main هي نقطة الدخول",
    "println! is a macro": "println! ماكرو للطباعة",
    "Use braces for blocks": "استخدم الأقواس لتحديد الكتل",
    "Bindings are immutable by default": "الربط ثابت افتراضيا",
    "Use mut only when needed": "استخدم mut عند الحاجة فقط",
    "Borrow instead of cloning blindly": "استعر القيمة بدل نسخها بلا سبب",
    "Use Result for recoverable errors": "استخدم Result للأخطاء القابلة للمعالجة",
    "Handle Err": "عالج حالة Err",
    "Use question mark in functions returning Result": "استخدم ? داخل الدوال التي ترجع Result",
    "Select only needed columns": "اختر الأعمدة المطلوبة فقط",
    "Read from one table first": "اقرأ من جدول واحد أولا",
    "Add limits while exploring": "أضف LIMIT أثناء الاستكشاف",
    "WHERE filters rows": "WHERE تصفي الصفوف",
    "ORDER BY sorts": "ORDER BY يرتب النتائج",
    "LIMIT protects exploration": "LIMIT يحمي الاستكشاف من النتائج الضخمة",
    "Aggregate after filtering": "اجمع البيانات بعد التصفية",
    "Group by non aggregate columns": "اجمع حسب الأعمدة غير المحسوبة",
    "Name metrics clearly": "سم المقاييس بوضوح",
    "Use semantic tags": "استخدم وسوما دلالية",
    "Labels belong with inputs": "اربط labels بالمدخلات",
    "Buttons are for actions": "الأزرار للإجراءات",
    "Use gap for spacing": "استخدم gap للمسافات",
    "Define stable widths": "حدد عروضا ثابتة",
    "Avoid layout shift": "تجنب قفز التخطيط",
    "Test small screens": "اختبر الشاشات الصغيرة",
    "Avoid viewport scaled fonts": "تجنب خطوطا تكبر مع عرض الشاشة",
    "Keep controls reachable": "اجعل الأزرار قابلة للوصول",
    "Quote variables": "ضع المتغيرات بين علامات اقتباس",
    "Start with echo": "ابدأ بـ echo",
    "Run in a small folder first": "شغل أولا داخل مجلد صغير",
    "Pipe output to the next command": "مرر الإخراج إلى الأمر التالي",
    "Use rg or grep for search": "استخدم rg أو grep للبحث",
    "Count with wc": "عد باستخدام wc",
    "Use set -e for safer scripts": "استخدم set -e لسكربتات أكثر أمانا",
    "Quote paths": "ضع المسارات بين علامات اقتباس",
    "Dry run before deleting": "جرب بدون حذف قبل التنفيذ الحقيقي",
    "Top level statements keep beginners moving": "تعليمات top level تساعد المبتدئ على البدء",
    "Use Console.WriteLine": "استخدم Console.WriteLine",
    "Keep namespaces clear": "اجعل namespaces واضحة",
    "Use explicit types first": "ابدأ بالأنواع الصريحة",
    "Learn var after basics": "تعلم var بعد الأساسيات",
    "Prefer readable names": "فضل الأسماء المقروءة",
    "Properties expose data": "properties تعرض البيانات",
    "Constructors set defaults": "constructors تضبط القيم الابتدائية",
    "Variables start with dollar sign": "المتغيرات تبدأ بعلامة الدولار",
    "echo outputs text": "echo يخرج النص",
    "End statements with semicolons": "أنه الجمل بفواصل منقوطة",
    "Use function for reusable work": "استخدم function للعمل القابل لإعادة الاستخدام",
    "Validate input": "تحقق من المدخلات",
    "Return values": "ارجع القيم",
    "Associative arrays use keys": "المصفوفات الترابطية تستخدم المفاتيح",
    "foreach loops through arrays": "foreach تمر على المصفوفات",
    "Escape output in HTML": "نظف الإخراج قبل HTML",
  },
};

const compactTutorialI18n: Partial<Record<InterfaceLanguage, Record<string, string>>> = {
  fr: {
    "Values and variables": "valeurs et variables",
    "Functions": "fonctions",
    "Async APIs": "API asynchrones",
    "Program output": "sortie du programme",
    "Values and names": "valeurs et noms",
    "Functions and collections": "fonctions et collections",
    "Prefer const first": "prefere const d abord",
    "Use let only when the value changes": "utilise let seulement quand la valeur change",
    "Inspect values with console.log": "inspecte les valeurs avec console.log",
    "Name functions with verbs": "nomme les fonctions avec des verbes",
    "Return values instead of printing inside every function": "retourne les valeurs au lieu de tout afficher",
    "Keep one function focused": "garde chaque fonction concentree",
  },
  de: {
    "Values and variables": "werte und variablen",
    "Functions": "funktionen",
    "Async APIs": "asynchrone APIs",
    "Program output": "programmausgabe",
    "Values and names": "werte und namen",
    "Functions and collections": "funktionen und sammlungen",
    "Prefer const first": "bevorzuge zuerst const",
    "Use let only when the value changes": "nutze let nur wenn sich der wert aendert",
    "Inspect values with console.log": "pruefe werte mit console.log",
    "Name functions with verbs": "benenne funktionen mit verben",
    "Return values instead of printing inside every function": "gib werte zurueck statt in jeder funktion zu drucken",
    "Keep one function focused": "halte jede funktion fokussiert",
  },
  pt: {
    "Values and variables": "valores e variaveis",
    "Functions": "funcoes",
    "Async APIs": "APIs assincronas",
    "Program output": "saida do programa",
    "Values and names": "valores e nomes",
    "Functions and collections": "funcoes e colecoes",
    "Prefer const first": "prefira const primeiro",
    "Use let only when the value changes": "use let apenas quando o valor muda",
    "Inspect values with console.log": "inspecione valores com console.log",
    "Name functions with verbs": "nomeie funcoes com verbos",
    "Return values instead of printing inside every function": "retorne valores em vez de imprimir em toda funcao",
    "Keep one function focused": "mantenha cada funcao focada",
  },
  ru: {
    "Values and variables": "значения и переменные",
    "Functions": "функции",
    "Async APIs": "асинхронные API",
    "Program output": "вывод программы",
    "Values and names": "значения и имена",
    "Functions and collections": "функции и коллекции",
    "Prefer const first": "сначала предпочитай const",
    "Use let only when the value changes": "используй let только когда значение меняется",
    "Inspect values with console.log": "проверяй значения через console.log",
    "Name functions with verbs": "называй функции глаголами",
    "Return values instead of printing inside every function": "возвращай значения вместо печати внутри каждой функции",
    "Keep one function focused": "держи одну функцию сфокусированной",
  },
  hi: {
    "Values and variables": "values और variables",
    "Functions": "functions",
    "Async APIs": "async APIs",
    "Program output": "program output",
    "Values and names": "values और names",
    "Functions and collections": "functions और collections",
    "Prefer const first": "पहले const चुनें",
    "Use let only when the value changes": "let तभी इस्तेमाल करें जब value बदले",
    "Inspect values with console.log": "console.log से value देखें",
    "Name functions with verbs": "function names में verbs रखें",
    "Return values instead of printing inside every function": "हर function में print करने के बजाय value return करें",
    "Keep one function focused": "एक function को एक काम पर रखें",
  },
  id: {
    "Values and variables": "nilai dan variabel",
    "Functions": "fungsi",
    "Async APIs": "API async",
    "Program output": "output program",
    "Values and names": "nilai dan nama",
    "Functions and collections": "fungsi dan koleksi",
    "Prefer const first": "utamakan const",
    "Use let only when the value changes": "pakai let hanya saat nilai berubah",
    "Inspect values with console.log": "periksa nilai dengan console.log",
    "Name functions with verbs": "beri nama fungsi dengan kata kerja",
    "Return values instead of printing inside every function": "kembalikan nilai daripada selalu mencetak",
    "Keep one function focused": "jaga fungsi tetap fokus",
  },
  vi: {
    "Values and variables": "gia tri va bien",
    "Functions": "ham",
    "Async APIs": "API bat dong bo",
    "Program output": "dau ra chuong trinh",
    "Values and names": "gia tri va ten",
    "Functions and collections": "ham va tap hop",
    "Prefer const first": "uu tien const truoc",
    "Use let only when the value changes": "chi dung let khi gia tri thay doi",
    "Inspect values with console.log": "kiem tra gia tri bang console.log",
    "Name functions with verbs": "dat ten ham bang dong tu",
    "Return values instead of printing inside every function": "tra ve gia tri thay vi in trong moi ham",
    "Keep one function focused": "giu moi ham tap trung mot viec",
  },
  th: {
    "Values and variables": "ค่าและตัวแปร",
    "Functions": "ฟังก์ชัน",
    "Async APIs": "API แบบ async",
    "Program output": "ผลลัพธ์ของโปรแกรม",
    "Values and names": "ค่าและชื่อ",
    "Functions and collections": "ฟังก์ชันและ collection",
    "Prefer const first": "เริ่มด้วย const ก่อน",
    "Use let only when the value changes": "ใช้ let เมื่อค่าต้องเปลี่ยนเท่านั้น",
    "Inspect values with console.log": "ตรวจค่าด้วย console.log",
    "Name functions with verbs": "ตั้งชื่อ function ด้วยคำกริยา",
    "Return values instead of printing inside every function": "return ค่าแทนการ print ในทุก function",
    "Keep one function focused": "ให้ function หนึ่งทำงานเดียว",
  },
  tr: {
    "Values and variables": "degerler ve degiskenler",
    "Functions": "fonksiyonlar",
    "Async APIs": "async APIler",
    "Program output": "program ciktisi",
    "Values and names": "degerler ve isimler",
    "Functions and collections": "fonksiyonlar ve koleksiyonlar",
    "Prefer const first": "once const tercih et",
    "Use let only when the value changes": "let sadece deger degisince kullan",
    "Inspect values with console.log": "degerleri console.log ile incele",
    "Name functions with verbs": "fonksiyonlari fiillerle adlandir",
    "Return values instead of printing inside every function": "her fonksiyonda yazdirmak yerine deger return et",
    "Keep one function focused": "bir fonksiyonu tek ise odakla",
  },
  it: {
    "Values and variables": "valori e variabili",
    "Functions": "funzioni",
    "Async APIs": "API asincrone",
    "Program output": "output del programma",
    "Values and names": "valori e nomi",
    "Functions and collections": "funzioni e collezioni",
    "Prefer const first": "preferisci const prima",
    "Use let only when the value changes": "usa let solo quando il valore cambia",
    "Inspect values with console.log": "controlla i valori con console.log",
    "Name functions with verbs": "nomina le funzioni con verbi",
    "Return values instead of printing inside every function": "restituisci valori invece di stampare in ogni funzione",
    "Keep one function focused": "mantieni ogni funzione focalizzata",
  },
  nl: {
    "Values and variables": "waarden en variabelen",
    "Functions": "functies",
    "Async APIs": "async APIs",
    "Program output": "programma output",
    "Values and names": "waarden en namen",
    "Functions and collections": "functies en collecties",
    "Prefer const first": "kies eerst const",
    "Use let only when the value changes": "gebruik let alleen als de waarde verandert",
    "Inspect values with console.log": "bekijk waarden met console.log",
    "Name functions with verbs": "geef functies werkwoordnamen",
    "Return values instead of printing inside every function": "return waarden in plaats van printen in elke functie",
    "Keep one function focused": "houd een functie gefocust",
  },
  pl: {
    "Values and variables": "wartosci i zmienne",
    "Functions": "funkcje",
    "Async APIs": "asynchroniczne API",
    "Program output": "wyjscie programu",
    "Values and names": "wartosci i nazwy",
    "Functions and collections": "funkcje i kolekcje",
    "Prefer const first": "najpierw wybieraj const",
    "Use let only when the value changes": "uzywaj let tylko gdy wartosc sie zmienia",
    "Inspect values with console.log": "sprawdzaj wartosci przez console.log",
    "Name functions with verbs": "nazywaj funkcje czasownikami",
    "Return values instead of printing inside every function": "zwracaj wartosci zamiast drukowac w kazdej funkcji",
    "Keep one function focused": "utrzymaj jedna funkcje skupiona",
  },
};

function tutorialText(text: string, language: InterfaceLanguage) {
  return tutorialI18n[language]?.[text] ?? compactTutorialI18n[language]?.[text] ?? text;
}

const tutorialFocusI18n: Partial<Record<InterfaceLanguage, Record<string, string>>> = {
  zh: {
    "const let string number boolean object array": "常量 变量 字符串 数字 布尔 对象 数组",
    "input output return reusable actions": "输入 输出 return 可复用动作",
    "fetch promise await error handling": "fetch Promise await 错误处理",
  },
  ja: {
    "const let string number boolean object array": "値 変数 文字列 数値 真偽値 オブジェクト 配列",
    "input output return reusable actions": "入力 出力 return 再利用できる処理",
    "fetch promise await error handling": "fetch Promise await エラー処理",
    "names lists dictionaries strings": "名前 リスト 辞書 文字列",
    "def parameters return": "def 引数 return",
    "for ranges lists dictionaries": "for range リスト 辞書",
    "columns table rows": "列 テーブル 行",
    "where order limit": "where order limit",
    "count sum avg group by": "count sum avg group by",
    "fn main println macro": "fn main と println! マクロ",
    "let mut ownership borrowing": "let mut 所有権 借用",
    "match Ok Err question mark": "match Ok Err 疑問符演算子",
  },
  ko: {
    "const let string number boolean object array": "값 변수 문자열 숫자 불리언 객체 배열",
    "input output return reusable actions": "입력 출력 return 재사용 동작",
    "fetch promise await error handling": "fetch Promise await 오류 처리",
  },
  es: {
    "const let string number boolean object array": "valores variables texto números booleanos objetos arreglos",
    "input output return reusable actions": "entrada salida return acciones reutilizables",
    "fetch promise await error handling": "fetch Promise await manejo de errores",
  },
  fr: {
    "const let string number boolean object array": "valeurs variables texte nombres booleens objets tableaux",
    "input output return reusable actions": "entree sortie return actions reutilisables",
    "fetch promise await error handling": "fetch Promise await gestion des erreurs",
  },
  de: {
    "const let string number boolean object array": "werte variablen text zahlen booleans objekte arrays",
    "input output return reusable actions": "eingabe ausgabe return wiederverwendbare aktionen",
    "fetch promise await error handling": "fetch Promise await fehlerbehandlung",
  },
  pt: {
    "const let string number boolean object array": "valores variaveis texto numeros booleanos objetos arrays",
    "input output return reusable actions": "entrada saida return acoes reutilizaveis",
    "fetch promise await error handling": "fetch Promise await tratamento de erros",
  },
  ru: {
    "const let string number boolean object array": "значения переменные строки числа boolean объекты массивы",
    "input output return reusable actions": "вход выход return переиспользуемые действия",
    "fetch promise await error handling": "fetch Promise await обработка ошибок",
  },
  ar: {
    "const let string number boolean object array": "القيم والمتغيرات والنصوص والأرقام والقوائم والكائنات",
    "input output return reusable actions": "مدخلات مخرجات return وأفعال قابلة لإعادة الاستخدام",
    "fetch promise await error handling": "fetch و Promise و await ومعالجة الأخطاء",
    "fn main println macro": "fn main و println! وماكرو الطباعة",
    "let mut ownership borrowing": "let و mut والملكية والاستعارة",
    "match Ok Err question mark": "match و Ok و Err وعلامة السؤال",
  },
  hi: {
    "const let string number boolean object array": "मान variable string number boolean object array",
    "input output return reusable actions": "इनपुट आउटपुट return दोबारा इस्तेमाल होने वाले काम",
    "fetch promise await error handling": "fetch Promise await और error handling",
  },
  id: {
    "const let string number boolean object array": "nilai variabel teks angka boolean objek array",
    "input output return reusable actions": "input output return aksi yang bisa dipakai ulang",
    "fetch promise await error handling": "fetch Promise await penanganan error",
  },
  vi: {
    "const let string number boolean object array": "gia tri bien chuoi so boolean doi tuong mang",
    "input output return reusable actions": "dau vao dau ra return hanh dong dung lai",
    "fetch promise await error handling": "fetch Promise await xu ly loi",
  },
  th: {
    "const let string number boolean object array": "ค่า ตัวแปร ข้อความ ตัวเลข boolean object array",
    "input output return reusable actions": "input output return งานที่ใช้ซ้ำได้",
    "fetch promise await error handling": "fetch Promise await การจัดการ error",
  },
  tr: {
    "const let string number boolean object array": "degerler degiskenler metin sayilar boolean nesneler diziler",
    "input output return reusable actions": "girdi cikti return yeniden kullanilabilir eylemler",
    "fetch promise await error handling": "fetch Promise await hata yonetimi",
  },
  it: {
    "const let string number boolean object array": "valori variabili testo numeri boolean oggetti array",
    "input output return reusable actions": "input output return azioni riutilizzabili",
    "fetch promise await error handling": "fetch Promise await gestione errori",
  },
  nl: {
    "const let string number boolean object array": "waarden variabelen tekst getallen boolean objecten arrays",
    "input output return reusable actions": "input output return herbruikbare acties",
    "fetch promise await error handling": "fetch Promise await foutafhandeling",
  },
  pl: {
    "const let string number boolean object array": "wartosci zmienne tekst liczby boolean obiekty tablice",
    "input output return reusable actions": "wejscie wyjscie return akcje wielokrotnego uzycia",
    "fetch promise await error handling": "fetch Promise await obsluga bledow",
  },
};

function tutorialFocusText(text: string, language: InterfaceLanguage) {
  return tutorialFocusI18n[language]?.[text] ?? text;
}

export { tutorialFocusText, tutorialText };
